// GENERATED by tools/lzss-gallery-assets.py; do not edit.
#ifndef LZSS_GALLERY_LAYOUT_H
#define LZSS_GALLERY_LAYOUT_H
#define GALLERY_FONT16_SECTION ".gallery_15.02"
#define GALLERY_FONT8_SECTION ".gallery_07.02"
#endif
