// Interactive SNES Mandelbrot — a real-time Mode 7 fly-around (#321 M2).
//
// The 128x128 Mandelbrot is PRECOMPUTED host-side, tiled into Mode 7 character order, and baked
// into ROM (examples/snes/mandel_image.h, generated by tools/mandel-bake.c). At boot the ROM just
// DMAs that character data straight ROM->VRAM and clears the tilemap — so the Mandelbrot appears
// INSTANTLY (no on-console fractal compute, and no on-console de-linearize loop either; both are
// the slow black-screen parts). The interactivity is Mode 7 hardware pan/zoom/rotate, 60 fps:
//
//   D-pad ........ pan        L / R .... zoom out / in      Y / A .... rotate
//   Select ....... cycle palette         Start .... reset view
//
// What this exercises for +mos-a16: the on-target fractal math is already proven differentially
// (dev/run.sh k_mandel / mandel-far). The NEW codegen customer is the PER-FRAME view->matrix math
// in examples/snes/view.h — four 16x16->32 fixed-point multiplies (the Mode 7 affine matrix) plus
// the pan/zoom/rotate state machine. It is gated by a host==target differential: the ROM logs the
// pad values it actually read (pad_log[]) and a rolling CRC of the per-frame view state + matrix
// (view_crc); dev/jgxcheck.cpp replays view.h over that ground-truth log and asserts an identical
// CRC. Capture: dev/run.sh mandel-interactive.
//
// The upload is a plain ROM->VRAM DMA (no far pointer), so this builds BOTH default-8bit and
// +mos-a16 — a host==default==+mos-a16 differential. See
// docs/plans/2026-06-25-321-interactive-mandelbrot-mode7.md.
#include <snes.h>
#include "mode7.h"
#include "../65816/mandel.h"   // img_hash16 (fast boot gate over the baked character data)
#include "view.h"              // pure view math + (via mandel_image.h) MANDEL_CHR/PAL/SINCOS

#define PADLOG_N 64            // bounded, fully-logged test window (frames). 64 u16 = 128 B WRAM.

// WRAM proof channels (near, low WRAM .bss). Read by the emulator harness; volatile so the
// per-frame writes are not optimised away.
volatile uint16_t corpus_result;        // CRC16 of the baked MANDEL_CHR (boot gate == host ref)
volatile uint16_t view_crc;             // rolling CRC of per-frame view state + Mode 7 matrix
volatile uint8_t  nframes;              // frames folded into view_crc (capped at PADLOG_N)
volatile uint16_t pad_log[PADLOG_N];    // ground-truth pad reads, for the host replay

static const uint8_t m7_zero = 0;       // fixed-source byte for the tilemap clear DMA

// Rewrite CGRAM with the palette rotated by `shift` (the Select-cycled colour effect). Called
// inside vblank (<= MANDEL_NCOL words), so no mid-frame CGRAM glitch.
static void cycle_palette(uint8_t shift) {
  REG_CGADD = 0;
  for (uint8_t i = 0; i < MANDEL_NCOL; i++) {
    uint8_t j = (uint8_t)(i + shift);
    if (j >= MANDEL_NCOL) j = (uint8_t)(j - MANDEL_NCOL);
    uint16_t c = MANDEL_PAL[j];
    REG_CGDATA = (uint8_t)(c & 0xFF);
    REG_CGDATA = (uint8_t)(c >> 8);
  }
}

// Push the current view to the PPU: Mode 7 matrix (precomputed in `m`), pan via BG scroll, and
// the palette rotation. Hardware-only — the pure math it consumes lives in view.h.
static void apply_view(const view_t *v, const int16_t m[4]) {
  m7_set_matrix(m[0], m[1], m[2], m[3]);
  m7_set_scroll((uint16_t)v->cx, (uint16_t)v->cy);
  cycle_palette(v->pal);
}

int main(void) {
  snes_ppu_reset_blank();

  // Instant upload: character data ROM->VRAM (high bytes), tilemap clear + identity (16x16 tiles).
  m7_dma_chr(0x00, (uint16_t)(uintptr_t)MANDEL_CHR, (uint16_t)(MANDEL_IMG_W * MANDEL_IMG_H));
  m7_tilemap_clear(0x00, (uint16_t)(uintptr_t)&m7_zero, M7_TILEMAP_WORDS);
  m7_tilemap_identity(MANDEL_IMG_W / 8, MANDEL_IMG_H / 8);
  m7_cgram_load(MANDEL_PAL, MANDEL_NCOL);

  m7_begin();                            // Mode 7, BG1 main screen (still force-blanked)
  m7_set_center(64, 64);                  // pivot rotation around the image centre

  view_t v; view_reset(&v);
  int16_t m[4];
  view_matrix(&v, m);
  apply_view(&v, m);                      // initial view
  m7_show();                             // release force-blank — INSTANT Mandelbrot (just a DMA)

  // Boot gate: hash the displayed character data and assert == host reference. A fast rolling
  // hash (not CRC16) so this one-shot finishes in a few frames with the image already on screen,
  // rather than stalling the demo (a full CRC16 over 16 KiB is seconds under +mos-a16).
  corpus_result = img_hash16(MANDEL_CHR, (uint16_t)(MANDEL_IMG_W * MANDEL_IMG_H));

  uint16_t vc = 0xFFFF;
  uint8_t  nf = 0;
  for (;;) {                             // steady-state 60 fps: view + Mode 7 matrix + palette
    snes_wait_vblank();
    uint16_t pad = snes_read_pad1();
    view_step(&v, pad);
    view_matrix(&v, m);
    apply_view(&v, m);
    if (nf < PADLOG_N) {                  // first PADLOG_N frames: the verifiable view-math window
      pad_log[nf] = pad;
      vc = view_fold(vc, &v, m);
      nf++;
      view_crc = vc;
      nframes = nf;
    }
  }
}
