// seamdemo.c — Act 1 of the ExHiROM three-act boundary synthesis cartridge.
//
// "The cartridge is the program." A 16-opcode bytecode VM executes a stream that
// spans the whole 6 MiB image: one ~256-byte chapter per 32 KiB slot, JFAR-chained
// in ascending FILE order, so the VM's 24-bit program counter marches the entire
// cartridge. The centrepiece is that counter rolling file $3FFFFF -> $400000 --
// CPU $FF:FFFF -> $40:0000, the non-monotonic device seam -- where the generator
// hand-laid a SYNC instruction whose OPCODE is the last byte of physical ROM 1 and
// whose OPERAND is the first byte of physical ROM 2. One VM instruction split
// across two mask ROMs; this ROM detects it and holds a freeze-frame beat on it.
//
// Nothing here knows an address. Every opcode value, the file->CPU translation
// table, the entry point, the seam offset and the expected fold come from
// seamdemo-data.h, generated by tools/snes-seamdemo-gen.py from the authoritative
// model tools/snes_cartmap.py. The VM itself is examples/65816/seamdemo_vm.h,
// shared verbatim with the host harness tools/seamdemo-sim.c. The contract is the
// "P0 design" section of
// docs/plans/2026-08-01-exhirom-three-act-synthesis-cart.md.
//
// Codegen under test -- the heaviest sustained indirect-control-flow load any demo
// here puts on the #320/#321 backend:
//   * every opcode is a FAR fetch (indirect-long `lda [dp]`, a 24-bit cursor that
//     must not lose its bank byte across the device seam),
//   * dispatch is a dense 16-way switch, which must lower to a jump table
//     (JMP (abs,X) -- the JMPIdxIndir pseudo), and
//   * the ALU ops go through a function-pointer table (jsr __call_indir).
// dev/seamdemo.sh asserts all three in the disassembly.
//
// +mos-a16 only: a runtime far pointer is a 32-bit value and 32-bit value
// legalization exists only under +mos-a16 -- same reason as cartsize-canary.c and
// examples/65816/far_indir.c. The differential is host oracle == +mos-a16 @ bsnes-jg.
//
// Built + gated by dev/seamdemo.sh (host: dev/run.sh seamdemo).

#include <snes.h>
#include <stdint.h>

#define CANVAS_FLUSH_TILES 96    // the VM draws in bursts; 96*16 = 1.5 KB/v-blank
#include "snesgfx/display.h"
#include "snesgfx/bitmap_canvas.h"
#include "snesgfx/text_layer.h"
#include "snesgfx/title_layer.h"

// Generated: VMOP_*/VMALU_*, seamdemo_xlat_*, seamdemo_dir16, SEAMDEMO_ACT1_*,
// SEAMDEMO_SEAM0_FILE, SEAMDEMO_DATA_OFF, SEAMDEMO_SLOT.
#include "seamdemo-data.h"
#include "mode7.h"
#include "sincos.h"

#define FAR __attribute__((address_space(2)))

// --- pacing --------------------------------------------------------------
// MEASURED on target (bsnes-jg, SlowROM 2.68 MHz), not estimated. Isolating the
// cost with -DSEAMDEMO_NO_DRAW / -DSEAMDEMO_NO_HUD showed drawing is ~5.6x the
// VM and the HUD is free. For the SHIPPING payload:
//
//   VM alone, no drawing .......... 52   ops/frame  (-DSEAMDEMO_NO_DRAW)
//   shipping build ................ 5.69 ops/frame
//   act length .................... ~2,050 frames = ~34 s
//                                   (bisected: act1_laps is 0 at frame 2,000,
//                                    1 at frame 2,100)
//
// Drawing does NOT scale linearly with segment count -- the canvas dirty-tile
// flush is budgeted at CANVAS_FLUSH_TILES per v-blank, so past some density it is
// a throughput wall, not a per-line cost. Don't fit a two-parameter model here;
// measure the payload you are shipping.
//
// The FIRST cut of the P0 payload (256-byte chapters, MOVE 2 times in 9) came to
// 65,961 ops / 12,729 segments = a ~245 s act against the plan's 20-30 s. That is
// not tunable from this file -- op count and MOVE density are the generator's --
// so P0 was regenerated against these measurements: 48-byte chapters and one MOVE
// slot per instruction menu give 10,494 ops / 367 segments.
//
// OPS_PER_FRAME is matched to the ACHIEVABLE rate, not to the duration target.
// The first build asked for 64 ops when only ~4.5 fit in a frame, so every loop
// iteration overran v-blank by ~14x and the PC ticker updated once every 14
// frames. At 8 the iteration fits one or two frames and the ticker is smooth.
// It stays a runtime dial for fine trim, as does the SYNC cadence.
#define OPS_PER_FRAME 8
// Act 2's cadence, MEASURED. At one node per frame the walk is draw-bound at
// ~1.9 frames/node -- Act 2's edges are far cheaper than Act 1's, because they
// join two points in the address-space picture rather than sweeping a turtle
// across the canvas -- so 374 nodes came to ~700 frames = ~12 s, under the
// plan's 20-30 s. The payload is fixed at this phase (the CRCs must not move),
// so the dial is the cadence: advance the walk once every ACT2_FRAME_DIV frames.
// 374 x 4 = ~1,500 frames = ~25 s, and 4 > 1.9 so the divider binds rather than
// the flush.
#define ACT2_FRAME_DIV 4
#define SEAM_BEAT_FRAMES 90      // 1.5 s freeze-frame on the device seam
#define VERDICT_FRAMES 150       // verdict hold before the act loops

#define CANVAS_CHR 0x0000
#define CANVAS_MAP 0x4000
#define BOX_COL 8                // 16-tile canvas at cols 8..23  (screen px 64..191)
#define BOX_ROW 6                // rows 6..21
#define HUD_TOP_ROW 1
#define HUD_BOT_ROW 25

// Sampled from the $7E WRAM mirror by the emulator gates.
volatile uint16_t corpus_result;   // P1: == act1_crc. P2/P3 replace it with fold(act1,act2,act3).
volatile uint16_t act1_crc;
volatile uint16_t act1_status;
volatile uint16_t act1_seam_hits;  // times the split instruction at the device seam executed
volatile uint16_t act1_laps;
volatile uint16_t act2_crc;
volatile uint16_t act2_status;
volatile uint16_t act2_nodes;       // nodes walked in the completed lap
volatile uint16_t act2_seam_edges;  // ... of which crossed the physical device boundary
volatile uint16_t act3_crc;
volatile uint16_t act3_status;
volatile uint16_t act3_pages;       // pages the camera swept in the completed lap
volatile uint16_t cycle_status;     // 0 once a full three-act cycle has verified
volatile uint16_t cycles;           // completed three-act cycles
// Pacing instrumentation, updated every frame: a WRAM dump at frame N gives the
// real ops/frame INCLUDING all display cost, which is the number that decides
// how long the act takes. (The SEAMDEMO_BENCH build measures the VM alone.)
volatile unsigned long act1_ops;
volatile uint16_t demo_frames;  // frames across the whole cycle, not just act 1
volatile unsigned long bench_ops;  // SEAMDEMO_BENCH only: ops executed in 60 v-blanks

// ---------------------------------------------------------------- far reads
//
// The VM's PC is a FILE offset; the cartridge is addressed by a 24-bit CPU
// address. The generated table says far = file + delta over two ranges. Those
// three numbers are lifted into plain statics at boot rather than indexed per
// fetch: the table is checked to be the assumed two-entry, base-zero shape
// (SEAMVM_ST_XLAT) so the specialisation is proven, not assumed.
static unsigned long xlat_split, xlat_delta_lo, xlat_delta_hi;

static inline unsigned long far_of(unsigned long file) {
  return file + (file < xlat_split ? xlat_delta_lo : xlat_delta_hi);
}

// `file` is a live runtime value, so this cannot constant-fold to absolute-long;
// it stays the indirect-long `lda [dp]` a real far cursor uses. Asserted in the
// gate's disasm step.
static inline uint8_t rom_mem8(unsigned long file) {
  return *(FAR const uint8_t *)far_of(file);
}

// The canvas MOVE draws into, reached through the VM's opaque ctx pointer.
// SEAMDEMO_NO_DRAW / SEAMDEMO_NO_HUD exist for the pacing measurement in
// dev/seamdemo.sh: the act's duration is dominated by the display path, not the
// VM, and isolating the two is the only way to size OPS_PER_FRAME honestly.
#define SEAMVM_MEM8(f) rom_mem8(f)
#ifndef SEAMDEMO_NO_DRAW
#define SEAMVM_DRAW(ctx, x0, y0, x1, y1, pen)                                    \
  canvas_line((BitmapCanvas *)(ctx), (int16_t)(x0), (int16_t)(y0), (int16_t)(x1), \
              (int16_t)(y1), (pen))
#endif
#include "../65816/seamdemo_vm.h"

// Act 2 addresses the cartridge by 24-bit CPU address directly -- no file->CPU
// translation, because a mirror-addressed node IS the test.
static inline uint8_t rom_far8(unsigned long far) {
  return *(FAR const uint8_t *)far;
}
#define SEAMGRAPH_FAR8(a) rom_far8(a)
#ifndef SEAMDEMO_NO_DRAW
#define SEAMGRAPH_EDGE(ctx, x0, y0, x1, y1, accent)                              \
  canvas_line((BitmapCanvas *)(ctx), (int16_t)(x0), (int16_t)(y0), (int16_t)(x1), \
              (int16_t)(y1), (uint8_t)((accent) ? 3u : 1u))
#endif
#include "../65816/seamdemo_graph.h"

// ---------------------------------------------------------------- act 3
// Mode 7 flyover over the cart-spanning atlas. The traversal (and therefore the
// fold) is seamdemo_atlas.h; everything below is rendering.
//
// A page upload is 4 KiB of Mode 7 character data, and Mode 7 char data is TILED
// (tile t occupies VRAM words t*64..t*64+63, 8x8 texels) while the payload's page
// is LINEAR row-major. The payload cannot be re-ordered -- it is frozen and the
// CRCs must not move -- so the de-tiling happens on the way to VRAM, as 64 short
// DMAs of 8 bytes each, one tile-row per v-blank across the 8 frames the camera
// spends on a page. Reading the 4096 bytes with far loads instead would cost
// ~4.6 frames per page (~875 frames over the act); the DMAs cost ~0.7.
static volatile uint16_t m7_page_slot;   // page whose upload is in flight
static volatile uint8_t m7_page_row;     // next tile-row to push (0..7), 8 = idle

#define SEAMATLAS_FILE8(o) rom_mem8(o)
#define SEAMATLAS_PAGE(ctx, slot) (m7_page_slot = (slot), m7_page_row = 0)
#include "../65816/seamdemo_atlas.h"

// ---------------------------------------------------------------- the app
#define MODE_RUN 0
#define MODE_SEAM 1
#define MODE_VERDICT 2

typedef struct {
  Display screen;
  BitmapCanvas canvas;
  TextLayer text;
  SeamVm vm;
  SeamGraph gr;
  SeamAtlas at;
  uint8_t act;            // 1 or 2 -- which act is on screen (3 runs its own loop)
  uint8_t cycle_ok;       // a full three-act cycle has verified
  uint8_t tick;           // act-2 cadence divider
  uint16_t pause;
  uint16_t laps;
  uint8_t mode;
  uint8_t pass;
} App;

// BG3 2bpp palette. 0 = black, then the three pen hues; the seam beat swaps in
// the accent set so the crossing reads as an event, not a caption.
static const uint16_t PAL_RUN[4] = {
    SNES_RGB(0, 0, 0), SNES_RGB(10, 24, 31), SNES_RGB(31, 26, 8), SNES_RGB(28, 10, 31),
};
// Act 2's web: dim blue for an ordinary edge, hot orange for one that crosses
// the physical device seam -- the accent the mockup asks for.
static const uint16_t PAL_WEB[4] = {
    SNES_RGB(0, 0, 2), SNES_RGB(8, 16, 28), SNES_RGB(18, 24, 31), SNES_RGB(31, 14, 2),
};
// The backdrop goes green ONLY after a full three-act cycle has verified -- the
// plan's "green once all three acts have folded correctly at least once".
static const uint16_t PAL_RUN_OK[4] = {
    SNES_RGB(0, 8, 3), SNES_RGB(10, 24, 31), SNES_RGB(31, 26, 8), SNES_RGB(28, 10, 31),
};
static const uint16_t PAL_SEAM[4] = {
    SNES_RGB(6, 0, 0), SNES_RGB(31, 31, 31), SNES_RGB(31, 20, 0), SNES_RGB(31, 6, 0),
};

static char hud_top[TEXT_COLS + 1];
static char hud_bot[TEXT_COLS + 1];
static const char HEXD[17] = "0123456789ABCDEF";

// Everything on the HUD is HEX, deliberately. The first cut printed OPS and SEG
// in decimal, which is ~17 32-bit divide/modulo pairs per frame; __udivmodsi4 on
// a 2.68 MHz 65816 is well over a thousand cycles each, and the HUD alone was
// eating ~3/4 of the frame -- the VM ran at 3.8 ops/frame with the decimal HUD
// and 24 ops/frame without it. put_hex is shifts and masks only.
static void put_hex16(char *d, uint16_t v, uint8_t digits) {
  for (uint8_t i = digits; i-- > 0;) {
    d[i] = HEXD[(uint8_t)(v & 0x0Fu)];
    v >>= 4;
  }
}

static void put_str(char *d, const char *s) {
  while (*s) *d++ = *s++;
}

static void hud_build(App *a) {
  for (uint8_t i = 0; i < TEXT_COLS; i++) {
    hud_top[i] = ' ';
    hud_bot[i] = ' ';
  }
  hud_top[TEXT_COLS] = 0;
  hud_bot[TEXT_COLS] = 0;

  if (a->act == 2) {
    // Act 2's top bar is the node's own CPU address -- which is also its position
    // in the web, since the canvas axes ARE bank and offset.
    unsigned long p = a->gr.p;
    put_str(hud_top, "NODE $");
    put_hex16(hud_top + 6, (uint16_t)(p >> 16), 2);
    hud_top[8] = ':';
    put_hex16(hud_top + 9, (uint16_t)p, 4);
    put_str(hud_top + 15, "N=$");
    put_hex16(hud_top + 18, a->gr.visited, 4);
    put_str(hud_top + 22, "/$");
    put_hex16(hud_top + 24, SEAMDEMO_ACT2_NODES, 4);

    if (a->mode == MODE_VERDICT) {
      // The verdict strip: both folds so far plus the cumulative one. Act 3's
      // column fills in from the previous cycle, so after one full loop the strip
      // carries all three.
      put_str(hud_bot, "1:");
      put_hex16(hud_bot + 2, a->vm.crc, 4);
      put_str(hud_bot + 7, "2:");
      put_hex16(hud_bot + 9, a->gr.crc, 4);
      put_str(hud_bot + 14, "3:");
      put_hex16(hud_bot + 16, act3_crc, 4);
      put_str(hud_bot + 21, "SUM:");
      put_hex16(hud_bot + 25, corpus_result, 4);
    } else {
      put_str(hud_bot, "EDGE=$");
      put_hex16(hud_bot + 6, a->gr.edges, 4);
      put_str(hud_bot + 11, "SEAM=$");
      put_hex16(hud_bot + 17, a->gr.seam_edges, 4);
      put_str(hud_bot + 22, "MIR=$");
      put_hex16(hud_bot + 27, a->gr.mirror_edges, 4);
    }
    text_puts(&a->text, 0, 0, hud_top);
    text_puts(&a->text, 1, 0, hud_bot);
    return;
  }

  // Act 1: the 24-bit PC in BOTH forms -- the file offset the stream is written
  // in, and the CPU bank:address the cartridge is decoded at. The device seam is
  // exactly the point where those two stop moving together.
  unsigned long pc = a->vm.pc;
  unsigned long far = far_of(pc);
  put_str(hud_top, "F=");
  put_hex16(hud_top + 2, (uint16_t)(pc >> 16), 2);
  put_hex16(hud_top + 4, (uint16_t)pc, 4);
  put_str(hud_top + 9, "C=");
  put_hex16(hud_top + 11, (uint16_t)(far >> 16), 2);
  hud_top[13] = ':';
  put_hex16(hud_top + 14, (uint16_t)far, 4);
  put_str(hud_top + 19, "SLOT=");
  put_hex16(hud_top + 24, (uint16_t)(pc >> 15), 2);

  if (a->mode == MODE_SEAM) {
    put_str(hud_bot, "SEAM $FF:FFFF -> $40:0000");
  } else if (a->mode == MODE_VERDICT) {
    put_str(hud_bot, "ACT1 CRC=");
    put_hex16(hud_bot + 9, a->vm.crc, 4);
    put_str(hud_bot + 14, a->pass ? "  VERIFIED" : "  MISMATCH");
  } else {
    put_str(hud_bot, "OPS=$");
    put_hex16(hud_bot + 5, (uint16_t)(a->vm.ops >> 16), 1);
    put_hex16(hud_bot + 6, (uint16_t)a->vm.ops, 4);
    put_str(hud_bot + 11, "SEG=$");
    put_hex16(hud_bot + 16, a->vm.nseg, 4);
    put_str(hud_bot + 21, "LAP=$");
    put_hex16(hud_bot + 26, a->laps, 2);
  }
  text_puts(&a->text, 0, 0, hud_top);
  text_puts(&a->text, 1, 0, hud_bot);
}

// ---------------------------------------------------------------- mode 7
// The atlas texel is (terrain << 4) | (pattern & 0x0F): the high nibble is smooth
// terrain, the low nibble the discriminating file-offset hash. So the palette
// ramps on the high nibble and dithers slightly on the low one -- the picture
// reads as terrain, and every texel still carries its decode probe.
static uint16_t m7_pal[256];

static void m7_build_palette(void) {
  for (uint16_t i = 0; i < 256u; i++) {
    uint8_t band = (uint8_t)(i >> 4);        // 0..15 terrain height
    uint8_t dith = (uint8_t)(i & 0x0Fu);     // 0..15 hash dither
    uint8_t r, g, b;
    if (band < 5u) {                          // water
      r = 0u; g = (uint8_t)(4u + band); b = (uint8_t)(14u + band * 2u);
    } else if (band < 11u) {                  // land
      r = (uint8_t)(4u + band); g = (uint8_t)(10u + band); b = (uint8_t)(4u + band / 2u);
    } else {                                  // rock -> snow
      r = (uint8_t)(12u + band); g = (uint8_t)(12u + band); b = (uint8_t)(12u + band);
    }
    uint8_t d = (uint8_t)(dith >> 2);         // +0..3, a gentle dither
    r = (uint8_t)((r + d) & 31u); g = (uint8_t)((g + d) & 31u); b = (uint8_t)((b + d) & 31u);
    m7_pal[i] = SNES_RGB(r, g, b);
  }
}

// The 128x128 Mode 7 tile grid is tiled with the 64 tiles of the current page, so
// the camera flies over a repeating field of whatever page it is on. Written once
// per act, under force-blank.
static void m7_build_tilemap(uint8_t *scratch) {
  for (uint8_t ty = 0; ty < 8u; ty++)
    for (uint16_t tx = 0; tx < 128u; tx++)
      scratch[(uint16_t)ty * 128u + tx] = (uint8_t)(ty * 8u + (tx & 7u));
  for (uint8_t row = 0; row < 128u; row++) {
    REG_VMAIN = VMAIN_INC_LOW_1;
    REG_VMADD = (uint16_t)((uint16_t)row * 128u);
    REG_DMAP0 = 0x00;                       // A->B, incrementing source
    REG_BBAD0 = 0x18;                       // $2118 VMDATAL (low bytes = tilemap)
    uint16_t src = (uint16_t)(uintptr_t)&scratch[(uint16_t)(row & 7u) * 128u];
    REG_A1T0L = (uint8_t)src; REG_A1T0H = (uint8_t)(src >> 8); REG_A1B0 = 0x00;
    REG_DAS0L = 128u; REG_DAS0H = 0u;
    REG_MDMAEN = 0x01;
  }
}

// Push one tile-row (8 tiles) of the pending page into Mode 7 character data.
// MUST be called inside v-blank. 64 DMAs of 8 bytes; see the note above.
static void m7_push_tile_row(uint16_t slot, uint8_t ty) {
  unsigned long base = far_of((unsigned long)slot * (unsigned long)SEAMDEMO_SLOT)
                       + (unsigned long)SEAMDEMO_DATA_OFF;
  uint8_t bank = (uint8_t)(base >> 16);
  for (uint8_t tx = 0; tx < 8u; tx++) {
    uint16_t tile = (uint16_t)((uint16_t)ty * 8u + tx);
    for (uint8_t row = 0; row < 8u; row++) {
      REG_VMAIN = VMAIN_INC_HIGH_1;
      REG_VMADD = (uint16_t)(tile * 64u + (uint16_t)row * 8u);
      REG_DMAP0 = 0x00;
      REG_BBAD0 = 0x19;                     // $2119 VMDATAH (high bytes = char data)
      unsigned long src = base + (unsigned long)((uint16_t)ty * 8u + row) * 64u
                          + (unsigned long)tx * 8u;
      REG_A1T0L = (uint8_t)src; REG_A1T0H = (uint8_t)(src >> 8); REG_A1B0 = bank;
      REG_DAS0L = 8u; REG_DAS0H = 0u;
      REG_MDMAEN = 0x01;
    }
  }
}

// 3040 samples at 2 per frame is ~1,520 frames = ~25 s, and it leaves the camera
// 8 frames on each page -- exactly the 8 tile-rows a page upload is split into.
#define ACT3_SAMPLES_PER_FRAME 2
#define ACT3_SPIN 1

// Act 3 takes the screen over: Mode 7 needs BG1 and the whole of VRAM
// $0000-$3FFF interleaved, which is where the BG3 canvas lives. It runs its own
// frame loop (the m7splash precedent) and returns force-blanked; the caller
// rebuilds the BG3 world with app_init() for the next cycle.
static void act3_run(App *a) {
  REG_NMITIMEN = 0u;                        // no NMI during the bulk VRAM writes
  REG_HDMAEN = 0u;
  REG_INIDISP = INIDISP_FORCE_BLANK;

  m7_build_palette();
  // The canvas chr buffer is 4 KiB of WRAM that Act 3 does not otherwise use, and
  // app_init() re-initialises it for the next cycle -- so it is the tilemap
  // scratch rather than a second 4 KiB static.
  m7_build_tilemap(a->canvas.chr);

  REG_CGADD = 0u;
  for (uint16_t i = 0; i < 256u; i++) {
    REG_CGDATA = (uint8_t)m7_pal[i];
    REG_CGDATA = (uint8_t)(m7_pal[i] >> 8);
  }

  m7_begin();                               // BGMODE 7, BG1 only, wrap
  m7_set_center(128u, 112u);
  m7_set_scroll(0u, 0u);
  m7_set_matrix((int16_t)0x100, 0, 0, (int16_t)0x100);
  REG_NMITIMEN = NMITIMEN_NMI | NMITIMEN_AUTOJOY;

  // Idle BEFORE init: seamatlas_init fires SEAMATLAS_PAGE itself if slot 0 is
  // reserved, and setting this afterwards would drop that first page's upload.
  // (Not reachable with the current skip list of {129, 130}, but the ordering
  // should not depend on that.)
  m7_page_row = 8u;
  seamatlas_init(&a->at);

  uint8_t angle = 0u;
  uint16_t drift = 0u;
  while (!a->at.done) {
    for (uint8_t n = 0; n < ACT3_SAMPLES_PER_FRAME && !a->at.done; n++)
      seamatlas_step(&a->at, a);

    angle = (uint8_t)(angle + ACT3_SPIN);
    drift = (uint16_t)(drift + 3u);
    int16_t co = SINCOS[(uint8_t)(angle + 64u)];
    int16_t si = SINCOS[angle];

    (void)REG_RDNMI;
    snes_wait_vblank();
    // v-blank only: the transform first, then at most one tile-row of the page.
    m7_set_matrix(co, (int16_t)-si, si, co);
    m7_set_scroll(drift, (uint16_t)(drift >> 1));
    if (m7_page_row < 8u) {
      m7_push_tile_row(m7_page_slot, m7_page_row);
      m7_page_row++;
    }
    REG_INIDISP = INIDISP_ON;
  }

  REG_INIDISP = INIDISP_FORCE_BLANK;
  REG_NMITIMEN = 0u;
}

static void app_init(App *a) {
  display_init(&a->screen);
  canvas_init(&a->canvas, CANVAS_CHR, CANVAS_MAP, BOX_COL, BOX_ROW);
  text_init(&a->text, CANVAS_MAP, HUD_TOP_ROW, HUD_BOT_ROW);
  display_add(&a->screen, (Drawable *)&a->canvas);
  display_add(&a->screen, (Drawable *)&a->text);
  upq_push_cgram(&a->screen.q, 0, a->cycle_ok ? PAL_RUN_OK : PAL_RUN, 0x00,
                 (uint8_t)sizeof PAL_RUN);
}

// Lift the generated file->CPU table into the three numbers far_of() uses, and
// prove the table really has the assumed shape. Also proves, ON CONSOLE, that the
// byte the generator claims it laid at the device seam is actually there -- which
// is the P0 contract's central assertion, checked by the thing that has to rely
// on it.
static uint16_t boot_checks(void) {
  uint16_t st = 0;
  if (SEAMDEMO_XLAT_COUNT != 2 || seamdemo_xlat_lo[0] != 0UL
      || seamdemo_xlat_lo[1] != seamdemo_xlat_hi[0]
      || seamdemo_xlat_hi[1] != SEAMDEMO_IMAGE_BYTES) {
    st |= SEAMVM_ST_XLAT;
  }
  xlat_split = seamdemo_xlat_hi[0];
  xlat_delta_lo = seamdemo_xlat_delta[0];
  xlat_delta_hi = seamdemo_xlat_delta[1];
  if (rom_mem8(SEAMDEMO_SEAM0_FILE - 1UL) != VMOP_SYNC) st |= SEAMVM_ST_SEAM_SHAPE;
  return st;
}

#if SEAMDEMO_BENCH

// Pacing measurement (dev/seamdemo.sh step 5b): run the VM flat out and count how
// many ops fit in 60 v-blanks. The HVBJOY poll between ops is inside the measured
// cost, so the answer is a LOWER bound on the achievable ops/frame -- the safe
// direction to size OPS_PER_FRAME against.
int main(void) {
  static App a;
  static SeamVm bv;
  snes_ppu_reset_blank();
  app_init(&a);
  bv.status = boot_checks();
  seamvm_init(&bv);

  uint16_t frames = 0;
  uint8_t was = (uint8_t)(REG_HVBJOY & HVBJOY_VBLANK);
  unsigned long n = 0;
  while (frames < 60 && !bv.halted) {
    seamvm_step(&bv, &a.canvas);
    n++;
    uint8_t now = (uint8_t)(REG_HVBJOY & HVBJOY_VBLANK);
    if (now && !was) frames++;
    was = now;
  }
  bench_ops = n;
  act1_status = bv.status;
  corpus_result = (uint16_t)(n / 60u);
  act1_crc = (uint16_t)(n / 60u);
  for (;;) __asm__ volatile("wai");
  return 0;
}

#else

int main(void) {
  static App a;

  // FIRST, before anything touches the screen: force-blank and zero every PPU
  // control register. bsnes-jg fills the ones a ROM never writes with
  // clock()-seeded noise, so without this the picture differs on every boot while
  // the WRAM verdict stays perfectly deterministic -- the failure mode the
  // cartsize canary spent a whole plan on (811c1f8). display_init() calls it too;
  // this call is the one guaranteed to precede everything.
  snes_ppu_reset_blank();

  app_init(&a);

  static TitleLayer title;
  title_begin16(&a.screen, &title, "SEAM DEMO", "ACT 1 - THE CARTRIDGE IS THE PROGRAM");
  uint16_t boot_st = boot_checks();
  title_end(&a.screen, &title, 110);

  seamvm_init(&a.vm);
  a.vm.status = boot_st;
  a.gr.status = 0;
  a.act = 1;
  a.tick = 0;
  a.cycle_ok = 0;
  a.at.status = 0;
  a.mode = MODE_RUN;
  a.pause = 0;
  a.laps = 0;
  a.pass = 0;
  act1_status = boot_st;
  act1_seam_hits = 0;
  act1_laps = 0;

  for (;;) {
    if (a.pause) {
      a.pause--;
      if (a.pause == 0) {
        if (a.mode == MODE_VERDICT) {
          canvas_clear(&a.canvas);
          if (a.act == 1) {
            // Hand off to Act 2 -- the plan's three-act cycle. P3 replaces the
            // wrap-around below with the hand-off to Act 3.
            a.act = 2;
            a.tick = 0;
            seamgraph_init(&a.gr);
            upq_push_cgram(&a.screen.q, 0, PAL_WEB, 0x00, (uint8_t)sizeof PAL_WEB);
          } else {
            // Act 2's verdict is up; run Act 3, then start the next cycle.
            // act3_run() takes the screen over (Mode 7 needs the VRAM the BG3
            // canvas occupies) and returns force-blanked.
            act3_run(&a);
            uint16_t h3 = seamatlas_final_crc(&a.at);
            if (h3 != SEAMDEMO_ACT3_CRC) a.at.status |= SEAMATLAS_ST_CRC;
            if (a.at.samples != SEAMDEMO_ACT3_SAMPLES) a.at.status |= SEAMATLAS_ST_PAGES;
            act3_crc = h3;
            act3_status = a.at.status;
            act3_pages = a.at.pages;

            // The full three-act fold. This is the value the plan says latches
            // after one complete cycle, and it is recomputed identically on every
            // later cycle, so it never moves once correct.
            corpus_result = seamvm_fold(
                seamvm_fold(seamvm_fold(seamvm_fold(seamvm_fold(seamvm_fold(0,
                    (uint8_t)(act1_crc & 0xFFu)), (uint8_t)(act1_crc >> 8)),
                    (uint8_t)(act2_crc & 0xFFu)), (uint8_t)(act2_crc >> 8)),
                    (uint8_t)(h3 & 0xFFu)), (uint8_t)(h3 >> 8));

            uint16_t cyc = (uint16_t)(a.vm.status | a.gr.status | a.at.status);
            if (corpus_result != SEAMDEMO_CORPUS_RESULT) cyc |= 0x8000u;
            cycle_status = cyc;
            a.cycle_ok = (uint8_t)(cyc == 0u);
            cycles = (uint16_t)(cycles + 1u);

            // Rebuild the BG3 world Act 3 overwrote. display_init() re-asserts
            // force-blank and resets the VRAM allocator, so the re-reserve is
            // legal again and the first display_frame below releases the blank.
            app_init(&a);
            a.act = 1;
            a.laps = (uint16_t)(a.laps + 1u);
            act1_laps = a.laps;
            uint16_t keep = a.vm.status;
            seamvm_init(&a.vm);
            a.vm.status = keep;
          }
        } else {
          upq_push_cgram(&a.screen.q, 0, a.cycle_ok ? PAL_RUN_OK : PAL_RUN, 0x00,
                         (uint8_t)sizeof PAL_RUN);
        }
        a.mode = MODE_RUN;
      }
    } else if (a.act == 1) {
      for (uint8_t n = OPS_PER_FRAME; n != 0; n--) {
        seamvm_step(&a.vm, &a.canvas);
        if (a.vm.seam_hit) {
          a.vm.seam_hit = 0;
          act1_seam_hits = (uint16_t)(act1_seam_hits + 1u);
          a.mode = MODE_SEAM;
          a.pause = SEAM_BEAT_FRAMES;
          upq_push_cgram(&a.screen.q, 0, PAL_SEAM, 0x00, (uint8_t)sizeof PAL_SEAM);
          break;
        }
        if (a.vm.halted) break;
        if (a.vm.ops > SEAMDEMO_ACT1_OP_BUDGET) {
          a.vm.status |= SEAMVM_ST_BUDGET;
          a.vm.halted = 1;
          break;
        }
        if (a.vm.yield) {
          a.pause = a.vm.yield;
          a.vm.yield = 0;
          break;
        }
      }
      if (a.vm.halted && a.mode != MODE_VERDICT) {
        uint16_t h = seamvm_final_crc(&a.vm);
        a.vm.crc = h;
        if (h != SEAMDEMO_ACT1_CRC) a.vm.status |= SEAMVM_ST_CRC;
        a.pass = (uint8_t)(a.vm.status == 0);
        act1_crc = h;
        act1_status = a.vm.status;
        a.mode = MODE_VERDICT;
        a.pause = VERDICT_FRAMES;
      }
    } else {
      a.tick++;
      if (a.tick >= ACT2_FRAME_DIV) {
        a.tick = 0;
        if (!a.gr.done) seamgraph_step(&a.gr, &a.canvas);
      }
      if (a.gr.done && a.mode != MODE_VERDICT) {
        uint16_t h = seamgraph_final_crc(&a.gr);
        a.gr.crc = h;
        if (h != SEAMDEMO_ACT2_CRC) a.gr.status |= SEAMGRAPH_ST_CRC;
        a.pass = (uint8_t)((a.gr.status == 0) && (a.vm.status == 0));
        act2_crc = h;
        act2_status = a.gr.status;
        act2_nodes = a.gr.visited;
        act2_seam_edges = a.gr.seam_edges;
        // P2: the corpus channel carries acts 1 and 2. P3 replaces this with the
        // full three-act fold (SEAMDEMO_CORPUS_RESULT).
        corpus_result = seamvm_fold(
            seamvm_fold(seamvm_fold(seamvm_fold(0, (uint8_t)(act1_crc & 0xFFu)),
                                    (uint8_t)(act1_crc >> 8)),
                        (uint8_t)(h & 0xFFu)),
            (uint8_t)(h >> 8));
        a.mode = MODE_VERDICT;
        a.pause = VERDICT_FRAMES;
      }
    }

#ifndef SEAMDEMO_NO_HUD
    hud_build(&a);
#endif
    act1_ops = a.vm.ops;
    demo_frames = (uint16_t)(demo_frames + 1u);
    display_frame(&a.screen);
  }
  return 0;
}

#endif
