#!/usr/bin/env bash
# dev/regen-patch-0004.sh — regenerate patches/llvm-mos/0004-320-far-cc.patch from the
# live (directly-edited) vendor/llvm-mos tree, via the isolated-worktree DELTA method.
#
# 0004 is the #320 Inc 4 Phase 2 far-pointer CALLING CONVENTION (the off-by-default
# +mos-farcc-* variants + farPtrCC() + the gated far-ptr CC rule + the Imag32
# register-bank coverage). It is its OWN patch — stacked on 0001+0002+0003 — rather
# than folded into 0001, because the far-ptr-COPY-through fix adds Imag32 to the
# AnyRegBank line that 0002 (a16, Increment 1b) ALSO edits (Ac16); a single shared
# line can't be split between 0001 and 0002 by the diff-reapply method that
# regen-patch-0001.sh / regen-patch.sh use. Stacking after 0002 sidesteps that:
# 0004's hunks may freely reference a16/xy16 context (Ac16, FeatureIndex16). It is
# behaviorally a16-INDEPENDENT (every far-CC rule is gated on a +mos-farcc-* feature
# that is off by default — proven byte-identical), only its PATCH CONTEXT touches
# a16 lines. dev/toolchain.sh applies patches/llvm-mos/*.patch in glob order, so 0004
# is auto-applied after 0003.
#
# Method (DELTA — mirrors regen-patch-0001.sh). The OLD approach built a baseline of
# "every patch EXCEPT 0004" and mirrored the whole live MOS dir over it. That broke when
# 0008 (mos-dp-arg-cc) landed: 0008's CC rule is authored ON TOP of 0004's far-CC table in
# MOSCallingConv.td, so 0008 will not `git apply` onto a 0004-less baseline — you simply
# cannot construct that baseline. The delta method never applies a later patch onto a
# 0004-less tree:
#   1. [recon] a worktree with the FULL committed stack 0001..0009 applied; save 0004's files.
#   2. [delta] diff(recon's 0004 files, live) = the NEW uncommitted far-CC edits. EMPTY when
#      simply regenerating the committed 0004 (the committed stack already == live) — NOT an
#      error.
#   3. [gen] a worktree = pristine + 0001+0002+0003 committed (0004's authored baseline);
#      apply the committed 0004 + the delta; `git diff --cached` -> new 0004. Only 0004 is
#      applied here, so 0005..0009's hunks to shared files (MOSCallingConv.td, …) never leak
#      in. (A NON-empty delta re-applies because far-CC edits anchor on 0004's own code, which
#      the 0001+0002+0003+0004 tree has; an edit in a region only 0005..0009 touch would need
#      a manual rebase — surfaces as a `git apply` failure here, not a silent corruption.)
#   4. [verify] apply 0001+0002+0003 + new 0004 + 0005..0009 to a fresh pristine worktree; the
#      reapplied MOS dir must equal the live vendor MOS dir (recursive diff — the safety net
#      for any far-CC file not in FARCC_FILES).
#
# Worktrees are created/used/removed ONE AT A TIME (a full llvm-mos checkout is ~2 GB; three
# at once overflows a small /tmp). Runs on the HOST (needs git + diff; no container). See
# docs/plans/2026-06-21-320-far-cc-variants-bcd-and-measure.md §Verification.
set -euo pipefail

usage() { echo "Usage: dev/regen-patch-0004.sh   # regenerate + round-trip-verify patches/llvm-mos/0004-320-far-cc.patch"; exit 0; }
[ "${1-}" = "-h" ] || [ "${1-}" = "--help" ] && usage

# ─── OBSOLETE (2026-07-26) ── fail loudly before touching anything ────────────────
# The two-tier patch model made per-patch regeneration from the live tree impossible:
# 0002-321-accum16.patch is regenerated by dev/regen-patch.sh as a FULL rsync mirror
# of llvm/lib/Target/MOS/, so it already contains every MOS-dir hunk of 0004-0017.
# This script's additive baseline (pristine + 0001 + narrow-0002 + ...) no longer
# exists: stacking 0004+ onto the comprehensive 0002 double-applies and fails, and
# the 0003/0008 steps it applies were DELETED (merged upstream as PR #562/#563).
# The standalone patch files remain FROZEN upstream-PR artifacts; to refresh one at
# posting time, rebase the patch file itself against the then-current upstream base
# by hand. Live-tree changes are captured only via dev/regen-patch.sh (0002).
# See docs/plans/2026-07-25-llvm-mos-fork-patch-stack-upstream-rebase.md and
# docs/plans/2026-07-26-zp-alloc-imag32-csr-rename-fix.md ("folded" note).
echo "OBSOLETE: per-patch regeneration is impossible under the two-tier patch model" >&2
echo "  (0002 is a comprehensive MOS-dir mirror; 0003/0008 are deleted, merged upstream)." >&2
echo "  The 0004+ patch files are frozen upstream-PR artifacts - edit/rebase them directly." >&2
echo "  Live-tree changes are captured via dev/regen-patch.sh (0002). Details: this header." >&2
exit 2


ROOT="$(cd "$(dirname "$0")/.." && pwd)"
VENDOR="$ROOT/vendor/llvm-mos"
PATCHES="$ROOT/patches/llvm-mos"
P1="$PATCHES/0001-320-far-addrspace.patch"
P2="$PATCHES/0002-321-accum16.patch"
P3="$PATCHES/0003-late-opt-txy-dead-flag.patch"   # upstream-bound F4 fix; optional
P4="$PATCHES/0004-320-far-cc.patch"
P5="$PATCHES/0005-320-far-ptr-value-legalize.patch"
P6="$PATCHES/0006-320-packed24.patch"
P7="$PATCHES/0007-65816-near-abs-bank-relax.patch"
P8="$PATCHES/0008-mos-dp-arg-cc.patch"
P9="$PATCHES/0009-321-a16-pressure-incdec.patch"
MOSREL="llvm/lib/Target/MOS"

# Every file 0004 adds/modifies (repo-relative) — all under the MOS dir. Diff'd individually
# for the delta; the recursive MOS verify below is the safety net for any far-CC file not
# listed here. Append a file if a future far-CC increment touches a new one.
FARCC_FILES=(
  "$MOSREL/MOSCallLowering.cpp"
  "$MOSREL/MOSCallingConv.cpp"
  "$MOSREL/MOSCallingConv.h"
  "$MOSREL/MOSCallingConv.td"
  "$MOSREL/MOSFeatures.td"
  "$MOSREL/MOSISelLowering.cpp"
  "$MOSREL/MOSISelLowering.h"
  "$MOSREL/MOSRegisterBanks.td"
  "$MOSREL/MOSSubtarget.h"
)

# The FULL committed stack, in apply order (0001..0009). P3 is optional (applied only if present).
STACK_FULL=("$P1" "$P2" "$P3" "$P4" "$P5" "$P6" "$P7" "$P8" "$P9")
# The patches 0004 stacks ON (everything strictly BELOW it), in apply order.
BASELINE_BELOW=("$P1" "$P2" "$P3")

# apply_seq <worktree> <patch...> — git-apply each in order; P3 is skipped if absent.
apply_seq() {
  local wt="$1"; shift; local p
  for p in "$@"; do
    [ "$p" = "$P3" ] && { [ -f "$P3" ] && git -C "$wt" apply "$P3"; continue; }
    git -C "$wt" apply "$p"
  done
}

[ -d "$VENDOR/.git" ] || { echo "FATAL: no vendor/llvm-mos checkout (run dev/run.sh toolchain)"; exit 1; }

PRISTINE="$(git -C "$VENDOR" rev-parse HEAD)"
echo "==> pristine vendor HEAD: $(git -C "$VENDOR" rev-parse --short HEAD)"

SAVE="$(mktemp -d)"; FARCC_DELTA="$(mktemp)"; WT=""
cleanup() {
  [ -n "$WT" ] && git -C "$VENDOR" worktree remove --force "$WT" 2>/dev/null || true
  git -C "$VENDOR" worktree prune 2>/dev/null || true
  rm -rf "$SAVE" "$FARCC_DELTA" "$WT"
}
trap cleanup EXIT
GIT_ID=(-c user.email=patchgen@local -c user.name=patchgen)

mkwt() { WT="$(mktemp -d)"; git -C "$VENDOR" worktree add --detach "$WT" "$PRISTINE" >/dev/null; }
rmwt() { git -C "$VENDOR" worktree remove --force "$WT" 2>/dev/null || true; rm -rf "$WT"; WT=""; }

echo "==> [recon] pristine + 0001..0009 = live minus the new far-CC edits; save 0004's files"
mkwt
apply_seq "$WT" "${STACK_FULL[@]}"
for f in "${FARCC_FILES[@]}"; do mkdir -p "$SAVE/$(dirname "$f")"; cp "$WT/$f" "$SAVE/$f"; done
rmwt

echo "==> [delta] far-CC edits = diff(recon, live) over 0004's files"
: > "$FARCC_DELTA"
for f in "${FARCC_FILES[@]}"; do
  if ! diff -q "$SAVE/$f" "$VENDOR/$f" >/dev/null 2>&1; then
    diff -u --label "a/$f" --label "b/$f" "$SAVE/$f" "$VENDOR/$f" >> "$FARCC_DELTA" || true
    echo "    + $f"
  fi
done
[ -s "$FARCC_DELTA" ] && echo "    (captured new uncommitted far-CC edits)" || echo "    (no new far-CC edits — regenerating committed 0004 as-is)"

echo "==> [gen] pristine + 0001+0002(+0003) baseline, apply 0004 + far-CC delta -> new 0004"
mkwt
apply_seq "$WT" "${BASELINE_BELOW[@]}"
git -C "$WT" add -A
git "${GIT_ID[@]}" -C "$WT" commit -q --allow-empty -m "0001+0002(+0003) baseline"
git -C "$WT" apply "$P4"
[ -s "$FARCC_DELTA" ] && git -C "$WT" apply "$FARCC_DELTA"
git -C "$WT" add -A
git -C "$WT" diff --cached > "$P4"
echo "    wrote $P4 ($(wc -l < "$P4") lines, $(grep -c '^diff --git' "$P4") files)"
rmwt

echo "==> [verify] apply 0001+0002(+0003) + new 0004 + 0005..0009 to a fresh pristine worktree"
mkwt
apply_seq "$WT" "${STACK_FULL[@]}"
echo "==> [verify] diff -rq reapplied MOS dir vs live vendor MOS dir"
rc=0
diff -rq "$WT/$MOSREL" "$VENDOR/$MOSREL" || rc=1
rmwt
if [ $rc -eq 0 ]; then
  echo "RESULT: PASS — 0004 round-trips (reapplied 0001..0009 == live vendor MOS dir)"
else
  echo "RESULT: FAIL — round-trip mismatch (see diff above)"; exit 1
fi
