#!/usr/bin/env python3
"""Render the SNES compiler-defect discovery map from its registry."""

import json
from datetime import date
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
REGISTRY = ROOT / "docs/snes-demo-compiler-bug-pages.json"
OUTPUT = ROOT / "docs/snes-demo-compiler-bug-map.md"


def link(label, target):
    return f"[{label}]({target})"


def local_link(path):
    file = ROOT / path
    if not file.is_file():
        raise SystemExit(f"{REGISTRY}: missing artifact: {path}")
    return link(path, file.relative_to(OUTPUT.parent).as_posix())


def main():
    data = json.loads(REGISTRY.read_text(encoding="utf-8"))
    if data.get("schema") != 1 or not isinstance(data.get("records"), list):
        raise SystemExit(f"{REGISTRY}: expected schema 1 with records")
    rows, slugs = [], set()
    for record in sorted(data["records"], key=lambda item: (item.get("discovered", ""), item.get("slug", ""))):
        for field in ("slug", "page", "discovered", "defect", "evidence"):
            if not isinstance(record.get(field), str) or not record[field]:
                raise SystemExit(f"{REGISTRY}: missing text field {field}")
        slug = record["slug"]
        try:
            date.fromisoformat(record["discovered"])
        except ValueError:
            raise SystemExit(f"{REGISTRY}: {slug}.discovered must be an ISO date")
        if slug in slugs:
            raise SystemExit(f"{REGISTRY}: duplicate slug {slug}")
        slugs.add(slug)
        prs, simulations = record.get("prs"), record.get("pr_simulations")
        if not isinstance(prs, list) or not isinstance(simulations, list):
            raise SystemExit(f"{REGISTRY}: {slug} needs prs and pr_simulations arrays")
        if prs and not simulations:
            raise SystemExit(f"{REGISTRY}: {slug} has an upstream PR without an internal PR simulation")
        pr_links = []
        for pr in prs:
            if not isinstance(pr, dict) or not isinstance(pr.get("label"), str) or not isinstance(pr.get("url"), str):
                raise SystemExit(f"{REGISTRY}: malformed PR for {slug}")
            pr_links.append(link(pr["label"], pr["url"]))
        simulations = [local_link(path) for path in simulations if isinstance(path, str)]
        if len(simulations) != len(record["pr_simulations"]):
            raise SystemExit(f"{REGISTRY}: malformed simulation path for {slug}")
        entries = record.get("lines")
        if entries is None:
            entries = [{"discovered": record["discovered"], "defect": record["defect"],
                        "evidence": record["evidence"], "prs": pr_links,
                        "simulations": simulations}]
        else:
            if not isinstance(entries, list) or not entries:
                raise SystemExit(f"{REGISTRY}: {slug}.lines must be a nonempty array")
            expanded = []
            for entry in entries:
                if not isinstance(entry, dict) or not all(
                        isinstance(entry.get(field), str) and entry[field]
                        for field in ("defect", "evidence", "pr_simulation")):
                    raise SystemExit(f"{REGISTRY}: malformed defect line for {slug}")
                pr, simulation = entry.get("pr"), entry["pr_simulation"]
                if (pr is not None and pr not in prs) or simulation not in record["pr_simulations"]:
                    raise SystemExit(f"{REGISTRY}: {slug} line has an unregistered PR or simulation")
                expanded.append({**entry, "discovered": entry.get("discovered", record["discovered"]),
                                 "prs": [link(pr["label"], pr["url"])] if pr else [],
                                 "simulations": [local_link(simulation)]})
            entries = expanded
        for number, entry in enumerate(entries):
            try:
                date.fromisoformat(entry["discovered"])
            except (TypeError, ValueError):
                raise SystemExit(f"{REGISTRY}: {slug} line needs an ISO discovery date")
            row = "| {discovered} | {defect} | {rom} | {evidence} | {prs} | {simulations} |".format(
                discovered=entry["discovered"], defect=entry["defect"], rom=link(slug, record["page"]),
                evidence=local_link(entry["evidence"]),
                prs="<br>".join(entry["prs"]) if entry["prs"] else "Not posted",
                simulations="<br>".join(entry["simulations"]) if entry["simulations"] else "—")
            rows.append((entry["discovered"], slug, number, row))
    OUTPUT.write_text("\n".join([
        "# SNES compiler-defect discovery map", "",
        "Generated by `python3 dev/render-snes-demo-compiler-bug-map.py` from "
        "[`snes-demo-compiler-bug-pages.json`](snes-demo-compiler-bug-pages.json). It lists published "
        "SNES ROMs that originally exposed a defect; later guard-only ROMs are excluded.", "",
        "| Discovered | Compiler defect | Original SNES ROM | Technical record | Upstream PR | Internal PR simulation |",
        "| --- | --- | --- | --- | --- | --- |", *[row[-1] for row in sorted(rows)], ""]), encoding="utf-8")


if __name__ == "__main__":
    main()
