#!/usr/bin/env python3
"""Render the SNES compiler-defect discovery map from its registry."""

import json
from datetime import date
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
REGISTRY = ROOT / "docs/snes-demo-compiler-bug-pages.json"
OUTPUT = ROOT / "docs/snes-demo-compiler-bug-map.md"


def link(label, target):
    return f"[{label}]({target})"


def local_link(path):
    file = ROOT / path
    if not file.is_file():
        raise SystemExit(f"{REGISTRY}: missing artifact: {path}")
    return link(path, file.relative_to(OUTPUT.parent).as_posix())


def main():
    data = json.loads(REGISTRY.read_text(encoding="utf-8"))
    if data.get("schema") != 1 or not isinstance(data.get("records"), list):
        raise SystemExit(f"{REGISTRY}: expected schema 1 with records")
    rows, slugs = [], set()
    for record in sorted(data["records"], key=lambda item: (item.get("discovered", ""), item.get("slug", ""))):
        for field in ("slug", "page", "discovered", "defect", "evidence"):
            if not isinstance(record.get(field), str) or not record[field]:
                raise SystemExit(f"{REGISTRY}: missing text field {field}")
        slug = record["slug"]
        try:
            date.fromisoformat(record["discovered"])
        except ValueError:
            raise SystemExit(f"{REGISTRY}: {slug}.discovered must be an ISO date")
        if slug in slugs:
            raise SystemExit(f"{REGISTRY}: duplicate slug {slug}")
        slugs.add(slug)
        prs, simulations = record.get("prs"), record.get("pr_simulations")
        if not isinstance(prs, list) or not isinstance(simulations, list):
            raise SystemExit(f"{REGISTRY}: {slug} needs prs and pr_simulations arrays")
        if prs and not simulations:
            raise SystemExit(f"{REGISTRY}: {slug} has an upstream PR without an internal PR simulation")
        pr_links = []
        for pr in prs:
            if not isinstance(pr, dict) or not isinstance(pr.get("label"), str) or not isinstance(pr.get("url"), str):
                raise SystemExit(f"{REGISTRY}: malformed PR for {slug}")
            pr_links.append(link(pr["label"], pr["url"]))
        simulations = [local_link(path) for path in simulations if isinstance(path, str)]
        if len(simulations) != len(record["pr_simulations"]):
            raise SystemExit(f"{REGISTRY}: malformed simulation path for {slug}")
        rows.append("| {discovered} | {defect} | {rom} | {evidence} | {prs} | {simulations} |".format(
            discovered=record["discovered"], defect=record["defect"], rom=link(slug, record["page"]),
            evidence=local_link(record["evidence"]),
            prs="<br>".join(pr_links) if pr_links else "Not posted",
            simulations="<br>".join(simulations) if simulations else "—"))
    OUTPUT.write_text("\n".join([
        "# SNES compiler-defect discovery map", "",
        "Generated by `python3 dev/render-snes-demo-compiler-bug-map.py` from "
        "[`snes-demo-compiler-bug-pages.json`](snes-demo-compiler-bug-pages.json). It lists published "
        "SNES ROMs that originally exposed a defect; later guard-only ROMs are excluded.", "",
        "| Discovered | Compiler defect | Original SNES ROM | Technical record | Upstream PR | Internal PR simulation |",
        "| --- | --- | --- | --- | --- | --- |", *rows, ""]), encoding="utf-8")


if __name__ == "__main__":
    main()
