#!/usr/bin/env bash
# dev/title.sh — frame-sweep capture of the TitleLayer intro (examples/snes/snesgfx/title_layer.h).
#
# The title card is pure animation: no WRAM gate value can tell you whether it LOOKS right, and the
# defect class it regresses into (a line's wrapped copy bleeding into the other line's HDMA band —
# "both lines arrive from both edges") is only visible mid-slide. So this renders a minimal probe
# ROM that does nothing but title_begin16 → title_end, snapshots it at a spread of frames through
# fly-in / hold / fall, and tiles them into one labelled contact sheet.
#
# What a PASS looks like on the sheet:
#   fly-in  — line0 descending from the top edge, line1 rising from the bottom, ONE image of each,
#             line0 always above line1, nothing entering from the wrong edge;
#   rest    — both lines centred, 8 px apart, reading as a normal two-line title;
#   fall    — both lines descending together, spacing preserved, accelerating, leaving the bottom
#             edge with nothing reappearing at the top.
#
# Host-side tool (not a Docker dev/run.sh target): it drives the prebuilt toolchain and jgxcheck
# harness directly. Outputs build/title-f<NNN>.png plus build/title-sheet.png.
set -euo pipefail

case "${1-}" in -h|--help)
  cat <<'USAGE'
Usage: dev/title.sh [FRAMES...]

Render the TitleLayer intro in bsnes-jg and snapshot it at each frame number given (default: a
spread covering fly-in, rest, and the gravity fall). Writes build/title-f<NNN>.png for each and
build/title-sheet.png (labelled contact sheet).

Env overrides:
  MOS_TOOLCHAIN  toolchain prefix (default: build/llvm-mos-install)
  TITLE_LINE0    8x8 subtitle   (default: "COMPILER STRESS TEST")
  TITLE_LINE1    16x16 name     (default: "TITLE PROBE")
USAGE
  exit 0;; esac

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
BUILD="$ROOT/build"
TOOL="${MOS_TOOLCHAIN:-$BUILD/llvm-mos-install}/bin"
CFG="$BUILD/install/bin/mos-snes.cfg"
JGX="$BUILD/jgxcheck"
DB="$ROOT/vendor/bsnes-jg/Database"
L0="${TITLE_LINE0:-COMPILER STRESS TEST}"
L1="${TITLE_LINE1:-TITLE PROBE}"

[ -x "$TOOL/mos-clang" ] || { echo "FATAL: no toolchain at $TOOL (run: dev/run.sh toolchain)"; exit 1; }
[ -f "$CFG" ]            || { echo "FATAL: SDK/snes not built (run: dev/run.sh build)"; exit 1; }
[ -x "$JGX" ]            || { echo "FATAL: no jgxcheck harness at $JGX (run: dev/run.sh xcheck)"; exit 1; }
[ -d "$DB" ]             || { echo "FATAL: no bsnes-jg Database at $DB"; exit 1; }

# Default sweep. Timeline at 60 fps with the shipped tunables:
#   0..14 fade-in (lines off-screen) | 15..127 fly-in | 128..247 hold | 248..292 fall | 293.. fade-out
FRAMES=("$@")
[ ${#FRAMES[@]} -gt 0 ] || FRAMES=(12 30 50 70 90 110 128 180 250 260 270 280 290)

# The probe ROM: the title card and nothing else, so frame N always means the same point in the
# animation (a real demo's pre-loop compute would slide the timeline).
PROBE="$BUILD/title-probe.c"
# Escape for a C string literal, then emit with printf — a heredoc would eat `$` and be broken by
# the `"` and `\` that a symbol-coverage probe specifically wants to test.
cesc() { local s=${1//\\/\\\\}; printf '%s' "${s//\"/\\\"}"; }
{
  printf '/* generated by dev/title.sh — minimal TitleLayer exerciser */\n'
  printf '#include <snes.h>\n#include "snesgfx/display.h"\n#include "snesgfx/title_layer.h"\n\n'
  printf 'int main(void) {\n  static Display d;\n  display_init(&d);\n  static TitleLayer t;\n'
  printf '  title_begin16(&d, &t, "%s", "%s");\n' "$(cesc "$L0")" "$(cesc "$L1")"
  printf '  title_end(&d, &t, TITLE_HOLD_FRAMES);\n  for (;;) display_frame(&d);\n}\n'
} > "$PROBE"

echo "==> building title probe ROM (+mos-a16)"
"$TOOL/mos-clang" --config "$CFG" -mcpu=mosw65816 -Xclang -target-feature -Xclang +mos-a16 -Os \
  -I "$ROOT/examples/snes" -o "$BUILD/title-probe.sfc" "$PROBE"
python3 "$ROOT/tools/snes-checksum.py" "$BUILD/title-probe.sfc" >/dev/null

shots=()
for f in "${FRAMES[@]}"; do
  out=$(printf '%s/title-f%03d.png' "$BUILD" "$f")
  rm -f "$out"      # never let a previous run's snapshot pass for this one
  # jgxcheck also asserts a WRAM value; the probe has no gate word, so ignore its verdict.
  "$JGX" "$BUILD/title-probe.sfc" "$DB" 0 2 0 "$f" "$out" >/dev/null 2>&1 || true
  [ -f "$out" ] || { echo "FATAL: no snapshot at frame $f"; exit 1; }
  echo "    frame $f -> ${out#"$ROOT"/}"
  shots+=("-label" "f$f" "$out")
done

if command -v montage >/dev/null 2>&1; then
  montage "${shots[@]}" -tile 5x -geometry +4+4 -background '#202020' -fill white \
          -pointsize 16 "$BUILD/title-sheet.png"
  echo "==> contact sheet: build/title-sheet.png"
fi
