#!/usr/bin/env bash
# dev/toolchain.sh — build llvm-mos (clang/lld) FROM SOURCE, for M1 codegen work.
#
# The bench's default toolchain is a prebuilt, immutable tarball (/opt/llvm-mos);
# you cannot change codegen without building the compiler. This clones llvm-mos into
# vendor/ (gitignored), builds into build/llvm-mos, installs to build/llvm-mos-install,
# then point the bench at it with MOS_TOOLCHAIN=/work/build/llvm-mos-install:
#   MOS_TOOLCHAIN=/work/build/llvm-mos-install dev/run.sh build && ... corpus
# Runs INSIDE the dev container (clang/lld/ccache/cmake/ninja present). Drive from the
# host: dev/run.sh toolchain. See docs/plans/2026-06-14-m1-from-source-toolchain.md.
#
# RAM is the binding constraint (14 GiB host): Release + lld + a single link job keep
# peak memory down; ccache (persisted in build/.ccache) makes later rebuilds fast.
# Compile parallelism defaults conservative; raise/lower with BUILD_JOBS if it swaps.
set -euo pipefail

usage() {
  echo "Usage: dev/run.sh toolchain   # build llvm-mos clang/lld from source -> build/llvm-mos-install"
  echo "  also refreshes the lit tool set (llc/opt/llvm-mc/llvm-objdump/llvm-readobj/llvm-readelf/llvm-config/count/split-file/FileCheck/not)"
  echo "  in build/llvm-mos; run lit itself with: dev/run.sh lit [PATHS...]"
  echo "Env: BUILD_JOBS (compile parallelism, default 6 — lower if the 14 GiB host swaps)"
  echo "     LLVM_MOS_PIN (upstream SHA a FRESH vendor/ is checked out at; an existing"
  echo "                   vendor/ is never reset; mismatched revisions fail the build)"
  echo "     LLVM_MOS_SOURCE / LLVM_MOS_BUILDDIR / LLVM_MOS_INSTALL (isolated paths)"
  echo "     LLVM_MOS_URL (upstream remote, default github.com/llvm-mos/llvm-mos.git)"
  exit 0
}
[ "${1-}" = "-h" ] || [ "${1-}" = "--help" ] && usage

ROOT=/work
SRC="${LLVM_MOS_SOURCE:-$ROOT/vendor/llvm-mos}"
BUILDDIR="${LLVM_MOS_BUILDDIR:-$ROOT/build/llvm-mos}"
INSTALL="${LLVM_MOS_INSTALL:-$ROOT/build/llvm-mos-install}"
JOBS="${BUILD_JOBS:-6}"
# The upstream commit a fresh bootstrap checks out. PINNED, not `main`: the tracked
# patch stack is generated against exactly one base, so cloning whatever `main` happens
# to be that day silently produces a different compiler (or fails to apply at all) —
# the opposite of "a clean build reproduces our compiler".
#
# The pinned revision contains the merged compiler fixes tracked in
# docs/upstream-contribution-status.md. The patch stack applies to this base.
LLVM_MOS_PIN="${LLVM_MOS_PIN:-$(cat "$ROOT/dev/llvm-mos-pin")}"
LLVM_MOS_URL="${LLVM_MOS_URL:-https://github.com/llvm-mos/llvm-mos.git}"
# Keep shared source and build trees available when the default pin advances.
# A separate checkout/build at the new base preserves unpublished source work.
if [ -z "${LLVM_MOS_SOURCE:-}" ] && [ -e "$SRC/.git" ] &&
   [ "$(git -C "$SRC" rev-parse HEAD)" != "$LLVM_MOS_PIN" ]; then
  SRC="$ROOT/vendor/llvm-mos-${LLVM_MOS_PIN:0:12}"
  BUILDDIR="${LLVM_MOS_BUILDDIR:-$ROOT/build/llvm-mos-${LLVM_MOS_PIN:0:12}}"
fi

export CCACHE_DIR="$ROOT/build/.ccache"
# /opt/llvm-mos/bin (the mos CROSS toolchain) is first on the image PATH and shadows
# host tools — a bare clang/llvm-ar/assembler there targets mos, not x86-64. Put host
# /usr/bin first for this host build so every tool (incl. the .S assembler) is native.
export PATH="/usr/bin:$PATH"

echo "==> llvm-mos @ ${LLVM_MOS_PIN:0:12}: source $SRC; build $BUILDDIR"
if [ ! -e "$SRC/.git" ]; then
  # Fetch the pinned commit directly rather than cloning a branch tip. GitHub serves
  # arbitrary SHAs (uploadpack.allowAnySHA1InWant), so one shallow fetch is enough; if a
  # mirror refuses that, fall back to a full fetch and check the SHA out from history.
  git init -q "$SRC"
  git -C "$SRC" remote add origin "$LLVM_MOS_URL" 2>/dev/null || \
    git -C "$SRC" remote set-url origin "$LLVM_MOS_URL"
  if ! git -C "$SRC" fetch -q --depth 1 origin "$LLVM_MOS_PIN"; then
    echo "    shallow fetch of the pinned SHA was refused; falling back to a full fetch"
    git -C "$SRC" fetch -q origin
  fi
  git -C "$SRC" checkout -q --detach "$LLVM_MOS_PIN"
  # Fail loudly rather than silently building a different compiler.
  got="$(git -C "$SRC" rev-parse HEAD)"
  [ "$got" = "$LLVM_MOS_PIN" ] || {
    echo "FATAL: vendor/ checked out $got, expected $LLVM_MOS_PIN" >&2; exit 1; }
  # Apply our tracked backend patches to the fresh clone. These are the eventual
  # upstream PR diffs, kept in-repo so a clean build reproduces our compiler.
  #
  # NOT a blind `patches/llvm-mos/*.patch` glob. `0002-321-accum16.patch` is
  # regenerated by `dev/regen-patch.sh` as a full rsync mirror of the LIVE
  # llvm/lib/Target/MOS directory (see that script's MOSREL), so it already
  # contains our remaining native-width implementation and
  # the MOS-BACKEND-DIR hunks of 0004-0015 — reapplying those would double-insert
  # and fail. They stay on disk as standalone,
  # individually reviewable upstream-PR artifacts (several are still-unposted PR
  # drafts; see docs/upstream-contribution-status.md).
  #
  # CRITICAL: 0002's mirror covers ONLY llvm/lib/Target/MOS/. Any hunk a patch
  # makes OUTSIDE that directory (generic LLVM, clang) is NOT in 0002 and MUST
  # be applied here or the build breaks. Exactly two patches have such hunks:
  #   0001 - clang far-pointer support + TargetDataLayout (applied whole; its
  #          MOS-dir hunks are the base 0002 was mirrored on top of).
  #   0006 - packed-24: adds the generic AsmPrinter::emitNonStandardSizedConstant
  #          virtual hook (AsmPrinter.h + the emitGlobalConstantImpl call site)
  #          plus Clang and shared target data-layout declarations. MOSAsmPrinter.cpp overrides that
  #          hook, and that override lives in 0002 — so omitting 0006's generic
  #          half yields "only virtual member functions can be marked 'override'"
  #          at MOSAsmPrinter.cpp. Applied PATH-FILTERED to just the non-MOS-dir
  #          hunks (its MOS-dir half is already in 0002).
  # Merged fixes and their tests are supplied by the upstream pin.
  #
  # New optimization patches remain separate after 0002; regen-patch.sh
  # reverse-applies them before rebuilding the 0002 mirror.
  # See docs/plans/2026-07-25-llvm-mos-fork-patch-stack-upstream-rebase.md.
  apply_patch() {
    local p="$ROOT/patches/llvm-mos/$1.patch"; shift
    [ -e "$p" ] || { echo "FATAL: missing $p"; exit 1; }
    echo "    applying patch $(basename "$p")${1:+ (path-filtered)}"
    git -C "$SRC" apply --allow-empty "$@" "$p"
  }
  apply_patch 0001-320-far-addrspace
  apply_patch 0002-321-accum16
  # +mos-a16 regression for the 0011 scavenger-live-$p fix (downstream-only test; 0011's
  # actual code fix is folded into 0002 directly, not applied standalone). Its own file
  # was sitting loose in vendor/ with nothing recreating it on a fresh bootstrap; captured
  # here so dev/regen-patch.sh's TESTRELS cp step has something to find on any vendor/.
  apply_patch 0042-mos-scavenger-p-undef-a16-test
  apply_patch 0018-320-imag32-spill
  apply_patch 0020-mos-65816-block-move-bank-order
  # generic-LLVM + clang half only; the MOS-dir half is already inside 0002
  apply_patch 0006-320-packed24 \
    --include='clang/*' --include='llvm/include/*' --include='llvm/lib/CodeGen/*' --include='llvm/lib/TargetParser/*'
  # Preserve undef lanes when an allocated virtual COPY becomes a physical
  # identity copy; the generic rewriter keeps the definition as a KILL.
  apply_patch 0028-llvm-virtregrewriter-undef-lane-identity-copy-vendor
  # Keep call-argument registers available to constrained virtual operands
  # when the two-address pass considers moving a physical-register definition.
  apply_patch 0029-llvm-twoaddr-physreg-reschedule
  # Spill hoisting must not mint scratch vregs after allocation; also drops
  # the driver's blanket -disable-spill-hoist (generic LLVM + clang driver + test).
  apply_patch 0033-llvm-spill-hoist-no-new-vregs
  # GlobalISel inline asm: store indirect register outputs ("=*r", what clang
  # emits for "+g") through their pointer (generic lowering + MOS/AArch64 tests).
  # The vendor artifact applies to the pinned GlobalISel operand representation.
  apply_patch 0037-llvm-gisel-inline-asm-indirect-output-vendor
  # InlineSpiller::coalesceStackAccess must not erase a stack access that carries
  # extra virtual defs (MOS's reload hook mints an Imag16 scratch pointer): the
  # orphaned vreg keeps its assignment in the interference matrix over a SlotIndex
  # with no instruction, and the next region split faults in enterIntvAfter. Same
  # family as 0033, opposite end of the spiller (generic LLVM + MOS test).
  apply_patch 0040-llvm-inline-spiller-coalesce-scratch-vregs
  # GlobalISel inline asm: register operands that need more than one register
  # (anything wider than an int on MOS, since "r" is Imag8 outside i16). The
  # tied form asserted and the plain input/output forms were rejected; all three
  # now split/merge least significant piece first, as SelectionDAG's
  # RegsForValue does. Stacks on 0037 (same file). Generic LLVM + MOS/AArch64
  # tests, so no dev/regen-patch.sh entry.
  # The vendor artifact applies after the indirect-output carry above.
  apply_patch 0041-llvm-gisel-inline-asm-multi-register-vendor
  # Select native s32->s16 truncations and retain the s8->s1 selector fallback.
  apply_patch 0023-mos-trunc-selection-regclasses
  # Reused physical values stay live through copy expansion's added uses.
  apply_patch 0030-mos-copy-phys-reg-liveness
  # Copy expansion may reuse the destination of an earlier copy (stacked on 0030).
  apply_patch 0031-mos-copy-phys-reg-reuse-dst
  # Symbols that match register spellings need quotes in generated assembly.
  apply_patch 0032-mos-quote-register-named-symbols-vendor
  # G_PREFETCH is legalized by dropping it (a hint the 6502 cannot use).
  apply_patch 0034-mos-legalize-prefetch
  # An explicit width modifier (mos16(), mos24(), ...) on a constant no longer
  # matches a narrower operand: mos16(240) selected zero page,X and mos24() was
  # truncated to a byte, defeating MOSMCInstLower::wrapAbsoluteIdxBase. Stock-
  # llvm-mos assembler defect, so it stays a standalone artifact applied after
  # 0002 and reverse-applied out of every 0002 regeneration.
  apply_patch 0039-mos-asm-modifier-width
  # Indexed opcodes use the same zero-page classification as their operands.
  apply_patch 0036-mos-zero-page-indexed-globals
  # __builtin_return_address(0) / __builtin_frame_address(0): legalized (hard-
  # stack read expanded by MOSLowerReturnAddress; fixed frame object at offset 0).
  # Generated against pristine upstream; four of its registration hunks sit next
  # to 0002's REP/SEP lines, hence the reduced context (-C1). Same in regen-patch.sh.
  apply_patch 0038-mos-return-frame-address -C1
  # Inline-asm constraints naming an 8-bit data register (a/x/y/R/d) refuse an
  # operand too wide for it instead of dropping its high bits. Stock-llvm-mos
  # defect independent of +mos-a16, so it stays a standalone artifact applied
  # after 0002 and reverse-applied out of every 0002 regeneration.
  apply_patch 0043-mos-inline-asm-physreg-width
  # A 24-bit address operand prints an explicit mos24() width whenever the bare
  # text could be re-parsed narrower, so far loads/stores and the $5C long jump
  # survive a -S/reassemble round trip instead of silently collapsing to their
  # DBR-relative / bank-local 16-bit siblings. Stock-65816 printer defect (the
  # parser half is 0039), so it stays a standalone artifact applied after 0002
  # and reverse-applied out of every 0002 regeneration.
  apply_patch 0044-mos-asm-print-long-address
  # The same printer gap one width down: a 16-bit immediate that would fit an
  # 8-bit one prints an explicit mos16() width, so `adc #66` under M=0 cannot
  # re-parse as the two-byte form and desynchronise the instruction stream.
  # Unlike 0044 this is DOWNSTREAM-ONLY — upstream nothing builds an
  # Immediate16 MCInst holding a plain small immediate — so it has no upstream
  # target; it is standalone only to keep it reviewable apart from 0002.
  apply_patch 0045-mos-asm-print-a16-immediate
  # MOSFixupKinds.cpp's Infos[] had 14 initialisers for 15 fixup kinds -- the
  # AddrAsciz row was missing, so a lookup for it silently read the array's
  # value-initialised tail ({nullptr, 0, 0, 0}) instead of a real entry.
  # Harmless today (TargetSize == 0 already means "never relax", which is
  # correct for this variable-width data directive), but the table's own
  # "same order as the header" contract was silently violated. Pristine-
  # upstream one-liner; standalone so it stays reviewable apart from 0002.
  apply_patch 0046-mos-fixupkinds-addrasciz-row
  # `llvm-mc -show-encoding` (any non --filetype=obj run) crashed on a
  # symbolic `.mos_addr_asciz` operand: MCStreamer::emitValue's generic
  # fallback can't print a not-yet-resolved value at a non-power-of-two
  # width ("Don't know how to emit this value."), VK_ADDR_ASCIZ had no
  # textual modifier spelling, and evaluateAsInt64's VK_ADDR_ASCIZ case was
  # llvm_unreachable (UB, not a trap, in this no-asserts build). Applied
  # after 0039 since it touches the same file's parseDirectiveAddrAsciz.
  # Pristine-upstream, general MC-layer gap (not 24-bit-specific); standalone
  # so it stays reviewable apart from 0002.
  apply_patch 0047-mos-mc-addr-asciz-symbolic-crash
  # Fork-local lit coverage for the #320/#321 far + packed-24 codegen model:
  # far-addressing.ll ($af/$8f absolute-long, $a7/$87 direct-indirect-long),
  # far-call.ll ($22 JSL / $6b RTL / $5c TailJML), far-legalizer-bridges.ll
  # (p2<->s32 and p3<->3x s8) and far-phi.ll (the 0014 G_PHI(p2) custom
  # legalisation). TEST-ONLY — it touches no compiler source, so it is NOT in
  # regen-patch.sh's STANDALONE_MOSDIR/TESTRELS lists: neither the MOS-dir
  # mirror nor the focused-test copy reaches llvm/test/CodeGen/MOS/far-*.ll,
  # so 0002 can neither absorb nor drop it. Downstream-only — AS2 is not
  # upstream-standalone-testable until the far ABI is blessed.
  apply_patch 0048-mos-far-codegen-lit-tests
  # Vector operations scalarize before entering the MOS scalar rules.
  # The upstream pin supplies the integer and vector-memory rules.
  apply_patch 0050-mos-float-vector-arithmetic
  apply_patch 0051-mos-zp-byte-index
  apply_patch 0052-mos-bank-relax-section-offset
  # The 6502 scavenger regression is independent of the a16-only MIR witness.
  # Its implementation is part of 0002; import only the standalone test here.
  apply_patch 0011-mos-scavenger-live-p-save \
    --include='llvm/test/CodeGen/MOS/scavenger-p-undef-6502.ll'
  # Keep the computed-carry scheduling optimization as a standalone patch.
  apply_patch 0064-mos-computed-carry-scheduling
  # Far memop lowering is in 0002; retain its independent runtime-ABI test.
  apply_patch 0013-320-far-memops-vendor \
    --include='llvm/test/CodeGen/MOS/far-memset.ll'
  apply_patch 0053-mos-lit-expectations
  apply_patch 0054-llvm-scavenger-save-range
  apply_patch 0055-mos-native-wide-anyext-vendor
  apply_patch 0056-llvm-gisel-inline-asm-register-bounds-vendor
  apply_patch 0057-llvm-selectiondag-inline-asm-register-bounds-vendor
  apply_patch 0058-aarch64-inline-asm-unknown-type-vendor
  apply_patch 0059-llvm-selectiondag-vector-asm-parts-vendor
  apply_patch 0060-llvm-reduce-parallel-mir
  apply_patch 0061-mos-far-global-long-x
  apply_patch 0062-mos-native-far-word
  apply_patch 0063-mos-near-shared-store
  apply_patch 0065-mos-near-store-profitability
  apply_patch 0066-mos-far-extload-worklist
  apply_patch 0067-mos-competing-carry-gate
  apply_patch 0068-mos-null-output-streamer
  apply_patch 0069-mos-far-loop-range
  apply_patch 0070-mos-far-word-index-policy
  # An explicit accumulator pressure set for 8-bit mode (limit 1, every level).
  # The computed-carry scheduling of 0064/0067 relies on it; see
  # docs/plans/2026-10-01-carry-pressure-contract.md.
  apply_patch 0071-mos-accumulator-pressure-set
  apply_patch 0072-amdgpu-rci-test-template-spacing
fi
echo "    commit: $(git -C "$SRC" rev-parse --short HEAD 2>/dev/null || echo '?')$(git -C "$SRC" diff --quiet -- llvm/lib/Target/MOS 2>/dev/null || echo ' +patched')"
# Existing source trees can carry unpublished work. Require the recorded base
# without resetting those edits; LLVM_MOS_SOURCE can select a separate checkout.
vendor_head="$(git -C "$SRC" rev-parse HEAD 2>/dev/null || echo '?')"
if [ "$vendor_head" != "$LLVM_MOS_PIN" ]; then
  echo "FATAL: source is at $vendor_head, expected $LLVM_MOS_PIN." >&2
  echo "Select a fresh checkout with LLVM_MOS_SOURCE; existing source edits are preserved." >&2
  exit 1
fi

# Trim the upstream MOS distribution to just clang + lld + the mos builtins. The
# stock cache also builds clang-tools-extra (clangd, clang-tidy, include-fixer, …) —
# heavy and irrelevant to codegen. We only need a working mos cross-compiler. Idempotent
# (no-op once patched); vendor/ is gitignored and disposable. Drop the 5 clang-tools-extra
# distribution components so install-distribution doesn't reference unbuilt targets.
echo "==> trim distribution to clang+lld (drop clang-tools-extra)"
sed -i \
  -e 's/clang;clang-tools-extra;lld/clang;lld/' \
  -e '/^[[:space:]]*clang-apply-replacements[[:space:]]*$/d' \
  -e '/^[[:space:]]*clang-include-fixer[[:space:]]*$/d' \
  -e '/^[[:space:]]*clang-tidy[[:space:]]*$/d' \
  -e '/^[[:space:]]*clangd[[:space:]]*$/d' \
  -e '/^[[:space:]]*find-all-symbols[[:space:]]*$/d' \
  "$SRC/clang/cmake/caches/MOS.cmake"

echo "==> configure (MOS.cmake cache, Release, host clang+lld, 1 link job, ccache)"
# Absolute host-clang paths: /opt/llvm-mos/bin is first on PATH (it holds the mos
# CROSS compiler, which can't build host binaries), so a bare `clang` would resolve
# there and fail the compiler check. The apt-installed host clang lives in /usr/bin.
cmake -C "$SRC/clang/cmake/caches/MOS.cmake" -G Ninja \
  -S "$SRC/llvm" -B "$BUILDDIR" \
  -DCMAKE_BUILD_TYPE=Release \
  -DCMAKE_INSTALL_PREFIX="$INSTALL" \
  -DCMAKE_C_COMPILER=/usr/bin/clang -DCMAKE_CXX_COMPILER=/usr/bin/clang++ \
  -DCMAKE_ASM_COMPILER=/usr/bin/clang \
  -DLLVM_USE_LINKER=lld \
  -DLLVM_PARALLEL_LINK_JOBS=1 \
  -DLLVM_CCACHE_BUILD=On

echo "==> build the distribution target (-j$JOBS); first build is long (~30-90 min)"
cmake --build "$BUILDDIR" --target distribution --parallel "$JOBS"

echo "==> install-distribution -> $INSTALL"
cmake --build "$BUILDDIR" --target install-distribution

# The distribution installs clang+lld; lit also needs the codegen and MC tools,
# RUN-line helpers, and llvm-config. Build llvm-readelf explicitly: it is a
# separate alias target for llvm-readobj. llvm-lit is generated at configure
# time and has no build target. Keep this set in sync with dev/lit.sh.
echo "==> refresh the lit tool set in $BUILDDIR (-j$JOBS)"
cmake --build "$BUILDDIR" --target llc opt llvm-mc llvm-objdump llvm-readobj llvm-readelf llvm-config count split-file FileCheck not --parallel "$JOBS"

# llc is not an LLVM_DISTRIBUTION_COMPONENTS member, so install-distribution never refreshes it and
# $INSTALL/bin/llc went stale (the SDK stamp, dev/toolchain-stamp.sh, hashes it). Install it here.
# Copy to a temp name + mv so a hardlinked copy of the old inode (cp -al worktrees) is not rewritten.
echo "==> install llc -> $INSTALL/bin/llc"
install -m 755 "$BUILDDIR/bin/llc" "$INSTALL/bin/llc.new"
mv -f "$INSTALL/bin/llc.new" "$INSTALL/bin/llc"

echo "==> done in $((SECONDS/60))m $((SECONDS%60))s: $("$INSTALL/bin/mos-clang" --version | head -1)"
echo "    use it: MOS_TOOLCHAIN=/work/build/llvm-mos-install dev/run.sh build && ... corpus"
echo "    lit: dev/run.sh lit [PATHS...]   (runs llvm-lit -s against the MOS suites; refreshes these tools first)"
