#!/usr/bin/env bash
# dev/toolchain.sh — build llvm-mos (clang/lld) FROM SOURCE, for M1 codegen work.
#
# The bench's default toolchain is a prebuilt, immutable tarball (/opt/llvm-mos);
# you cannot change codegen without building the compiler. This clones llvm-mos into
# vendor/ (gitignored), builds into build/llvm-mos, installs to build/llvm-mos-install,
# then point the bench at it with MOS_TOOLCHAIN=/work/build/llvm-mos-install:
#   MOS_TOOLCHAIN=/work/build/llvm-mos-install dev/run.sh build && ... corpus
# Runs INSIDE the dev container (clang/lld/ccache/cmake/ninja present). Drive from the
# host: dev/run.sh toolchain. See docs/plans/2026-06-14-m1-from-source-toolchain.md.
#
# RAM is the binding constraint (14 GiB host): Release + lld + a single link job keep
# peak memory down; ccache (persisted in build/.ccache) makes later rebuilds fast.
# Compile parallelism defaults conservative; raise/lower with BUILD_JOBS if it swaps.
set -euo pipefail

usage() {
  echo "Usage: dev/run.sh toolchain   # build llvm-mos clang/lld from source -> build/llvm-mos-install"
  echo "  also refreshes the lit tool set (llc/opt/llvm-mc/llvm-objdump/llvm-readobj/FileCheck/not)"
  echo "  in build/llvm-mos; run lit itself with: dev/run.sh lit [PATHS...]"
  echo "Env: BUILD_JOBS (compile parallelism, default 6 — lower if the 14 GiB host swaps)"
  echo "     LLVM_MOS_PIN (upstream SHA a FRESH vendor/ is checked out at; an existing"
  echo "                   vendor/ is never reset, only warned about when it has drifted)"
  echo "     LLVM_MOS_URL (upstream remote, default github.com/llvm-mos/llvm-mos.git)"
  exit 0
}
[ "${1-}" = "-h" ] || [ "${1-}" = "--help" ] && usage

ROOT=/work
SRC="$ROOT/vendor/llvm-mos"
BUILDDIR="$ROOT/build/llvm-mos"
INSTALL="$ROOT/build/llvm-mos-install"
JOBS="${BUILD_JOBS:-6}"
# The upstream commit a fresh bootstrap checks out. PINNED, not `main`: the tracked
# patch stack is generated against exactly one base, so cloning whatever `main` happens
# to be that day silently produces a different compiler (or fails to apply at all) —
# the opposite of "a clean build reproduces our compiler".
#
# Why this SHA: `dev/regen-patch.sh` derives its baseline from `git -C vendor rev-parse
# HEAD`, so `0002-321-accum16.patch` is BY CONSTRUCTION a diff against whatever the live
# vendor/ checkout is — currently 8be0546 ("[MOS] Pass addrspace(1) … in an 8-bit
# register", #563). That makes 8be0546 the only base 0002 is known to apply to.
# `build/upstream-reference/742d554…` is a NEWER reference some per-patch validation used
# (and the live vendor/ clone is shallow, so it cannot even reach it). Moving this pin is
# therefore not a one-liner: regenerate 0002 against the new base, then re-verify every
# standalone patch applies. See docs/plans/2026-07-25-llvm-mos-fork-patch-stack-upstream-rebase.md.
LLVM_MOS_PIN="${LLVM_MOS_PIN:-8be0546128a55e78c63ca571d466aa72a782cd36}"
LLVM_MOS_URL="${LLVM_MOS_URL:-https://github.com/llvm-mos/llvm-mos.git}"
export CCACHE_DIR="$ROOT/build/.ccache"
# /opt/llvm-mos/bin (the mos CROSS toolchain) is first on the image PATH and shadows
# host tools — a bare clang/llvm-ar/assembler there targets mos, not x86-64. Put host
# /usr/bin first for this host build so every tool (incl. the .S assembler) is native.
export PATH="/usr/bin:$PATH"

echo "==> fetch llvm-mos @ ${LLVM_MOS_PIN:0:12} into vendor/ (gitignored, shallow, pinned)"
if [ ! -d "$SRC/.git" ]; then
  # Fetch the pinned commit directly rather than cloning a branch tip. GitHub serves
  # arbitrary SHAs (uploadpack.allowAnySHA1InWant), so one shallow fetch is enough; if a
  # mirror refuses that, fall back to a full fetch and check the SHA out from history.
  git init -q "$SRC"
  git -C "$SRC" remote add origin "$LLVM_MOS_URL" 2>/dev/null || \
    git -C "$SRC" remote set-url origin "$LLVM_MOS_URL"
  if ! git -C "$SRC" fetch -q --depth 1 origin "$LLVM_MOS_PIN"; then
    echo "    shallow fetch of the pinned SHA was refused; falling back to a full fetch"
    git -C "$SRC" fetch -q origin
  fi
  git -C "$SRC" checkout -q --detach "$LLVM_MOS_PIN"
  # Fail loudly rather than silently building a different compiler.
  got="$(git -C "$SRC" rev-parse HEAD)"
  [ "$got" = "$LLVM_MOS_PIN" ] || {
    echo "FATAL: vendor/ checked out $got, expected $LLVM_MOS_PIN" >&2; exit 1; }
  # Apply our tracked backend patches to the fresh clone. These are the eventual
  # upstream PR diffs, kept in-repo so a clean build reproduces our compiler.
  #
  # NOT a blind `patches/llvm-mos/*.patch` glob. `0002-321-accum16.patch` is
  # regenerated by `dev/regen-patch.sh` as a full rsync mirror of the LIVE
  # llvm/lib/Target/MOS directory (see that script's MOSREL), so it already
  # contains every MOS-BACKEND-DIR hunk that 0004-0015 carry (except 0010, which
  # is applied below like 0018-0025) — reapplying those here would double-insert
  # and fail. They stay on disk as standalone,
  # individually reviewable upstream-PR artifacts (several are still-unposted PR
  # drafts; see docs/upstream-contribution-status.md).
  #
  # CRITICAL: 0002's mirror covers ONLY llvm/lib/Target/MOS/. Any hunk a patch
  # makes OUTSIDE that directory (generic LLVM, clang) is NOT in 0002 and MUST
  # be applied here or the build breaks. Exactly two patches have such hunks:
  #   0001 - clang far-pointer support + TargetDataLayout (applied whole; its
  #          MOS-dir hunks are the base 0002 was mirrored on top of).
  #   0006 - packed-24: adds the generic AsmPrinter::emitNonStandardSizedConstant
  #          virtual hook (AsmPrinter.h + the emitGlobalConstantImpl call site)
  #          plus a clang Targets/MOS.cpp hunk. MOSAsmPrinter.cpp OVERRIDES that
  #          hook, and that override lives in 0002 — so omitting 0006's generic
  #          half yields "only virtual member functions can be marked 'override'"
  #          at MOSAsmPrinter.cpp. Applied PATH-FILTERED to just the non-MOS-dir
  #          hunks (its MOS-dir half is already in 0002).
  # (0015's only non-MOS file is a lit test — irrelevant to a build. 0016/0017
  # are MOS-dir-only and were folded into 0002 by the 2026-07-26 regen; their
  # files remain on disk as standalone upstream-PR artifacts like 0004-0015.)
  #
  # When adding a new patch: if it touches only llvm/lib/Target/MOS/, fold it
  # into 0002 via dev/regen-patch.sh and leave this list alone; if it touches
  # anything outside that dir, that portion must be added here.
  # See docs/plans/2026-07-25-llvm-mos-fork-patch-stack-upstream-rebase.md.
  apply_patch() {
    local p="$ROOT/patches/llvm-mos/$1.patch"; shift
    [ -e "$p" ] || { echo "FATAL: missing $p"; exit 1; }
    echo "    applying patch $(basename "$p")${1:+ (path-filtered)}"
    git -C "$SRC" apply "$@" "$p"
  }
  apply_patch 0001-320-far-addrspace
  apply_patch 0002-321-accum16
  # Upstream PR #578 (MOSCopyOpt loop live-in fixed point + its two lit tests).
  # Stock-llvm-mos defect, so it stays a standalone artifact applied after 0002
  # and listed in dev/regen-patch.sh's STANDALONE_MOSDIR. Drop on upstream merge.
  apply_patch 0010-coalesce-rotate-ac
  apply_patch 0018-320-imag32-spill
  apply_patch 0019-mos-branch-range-diagnostic
  apply_patch 0020-mos-65816-block-move-bank-order
  apply_patch 0021-mos-zp-alloc-deterministic
  # generic-LLVM + clang half only; the MOS-dir half is already inside 0002
  apply_patch 0006-320-packed24 \
    --include='clang/*' --include='llvm/include/*' --include='llvm/lib/CodeGen/*'
  # Preserve undef lanes when an allocated virtual COPY becomes a physical
  # identity copy; the generic rewriter keeps the definition as a KILL.
  apply_patch 0028-llvm-virtregrewriter-undef-lane-identity-copy
  # Keep call-argument registers available to constrained virtual operands
  # when the two-address pass considers moving a physical-register definition.
  apply_patch 0029-llvm-twoaddr-physreg-reschedule
  # Spill hoisting must not mint scratch vregs after allocation; also drops
  # the driver's blanket -disable-spill-hoist (generic LLVM + clang driver + test).
  apply_patch 0033-llvm-spill-hoist-no-new-vregs
  # __builtin_prefetch: clang emits the rw/locality operands as i32 on
  # 16-bit-int targets (generic clang fix, aimed at llvm/llvm-project).
  # -vendor twin: the upstream form targets the 742d554 validation tree (Clang's
  # EmitScalarOrConstFoldImmArg/ICEArguments shape); the pin still has EmitScalarExpr.
  apply_patch 0035-clang-prefetch-int16-operands-vendor
  # GlobalISel inline asm: store indirect register outputs ("=*r", what clang
  # emits for "+g") through their pointer (generic lowering + MOS/AArch64 tests).
  # -vendor twin: the upstream form targets the 742d554 validation tree (whose
  # GISelAsmOperandInfo already carries the RegClass member); the pin does not.
  apply_patch 0037-llvm-gisel-inline-asm-indirect-output-vendor
  # InlineSpiller::coalesceStackAccess must not erase a stack access that carries
  # extra virtual defs (MOS's reload hook mints an Imag16 scratch pointer): the
  # orphaned vreg keeps its assignment in the interference matrix over a SlotIndex
  # with no instruction, and the next region split faults in enterIntvAfter. Same
  # family as 0033, opposite end of the spiller (generic LLVM + MOS test).
  apply_patch 0040-llvm-inline-spiller-coalesce-scratch-vregs
  # GlobalISel inline asm: register operands that need more than one register
  # (anything wider than an int on MOS, since "r" is Imag8 outside i16). The
  # tied form asserted and the plain input/output forms were rejected; all three
  # now split/merge least significant piece first, as SelectionDAG's
  # RegsForValue does. Stacks on 0037 (same file). Generic LLVM + MOS/AArch64
  # tests, so no dev/regen-patch.sh entry.
  # -vendor twin: the upstream form targets the 742d554 validation tree (it also
  # deletes an arm64-fallback.ll case that does not exist at the pin).
  apply_patch 0041-llvm-gisel-inline-asm-multi-register-vendor
  # Upstream-bound standalone fix, carried until it merges — the same slot and
  # lifecycle as the retired 0003-late-opt-txy-dead-flag (-> PR #562). Applies
  # after 0002 because both touch MOSLateOptimization.cpp, and it is BAKED INTO
  # THE BASELINE by dev/regen-patch.sh so a 0002 regen never absorbs it. Drop
  # this line and the patch file once it lands upstream and the vendor pin moves.
  apply_patch 0003-late-opt-nongpr-ldimm-dest
  # Same slot lifecycle as 0003: upstream PR #589 — CmpZero is a terminator,
  # lowerCmpZeros scans MBB.terminators() and tracks each pseudo's fold with a
  # per-instruction flag so every CmpZero is either folded or lowered. Touches
  # MOSLateOptimization.cpp + MOSInstrPseudos.td; reproduces on pristine
  # upstream. Listed in dev/regen-patch.sh's STANDALONE_MOSDIR. Drop on merge.
  apply_patch 0022-mos-late-opt-cmpzero-lowering
  # Far-pointer-order demo finding: select legal truncations whose source bank
  # is Imag8 (s8->s1) or Imag32 (s32->s16 under +mos-a16).
  apply_patch 0023-mos-trunc-selection-regclasses
  # Baseline MOS assembler: BRK carries its architectural signature byte.
  apply_patch 0024-mos-brk-signature-operand
  apply_patch 0025-llvm-mc-preserve-motorola-default
  # Reused physical values stay live through copy expansion's added uses.
  apply_patch 0030-mos-copy-phys-reg-liveness
  # Copy expansion may reuse the destination of an earlier copy (stacked on 0030).
  apply_patch 0031-mos-copy-phys-reg-reuse-dst
  # Symbols that match register spellings need quotes in generated assembly.
  apply_patch 0032-mos-quote-register-named-symbols-vendor
  # G_PREFETCH is legalized by dropping it (a hint the 6502 cannot use).
  apply_patch 0034-mos-legalize-prefetch
  # Indexed opcodes use the same zero-page classification as their operands.
  apply_patch 0036-mos-zero-page-indexed-globals
  # __builtin_return_address(0) / __builtin_frame_address(0): legalized (hard-
  # stack read expanded by MOSLowerReturnAddress; fixed frame object at offset 0).
  # Generated against pristine upstream; four of its registration hunks sit next
  # to 0002's REP/SEP lines, hence the reduced context (-C1). Same in regen-patch.sh.
  apply_patch 0038-mos-return-frame-address -C1
fi
echo "    commit: $(git -C "$SRC" rev-parse --short HEAD 2>/dev/null || echo '?')$(git -C "$SRC" diff --quiet -- llvm/lib/Target/MOS 2>/dev/null || echo ' +patched')"
# An EXISTING vendor/ tree is never re-cloned or reset (it is shared, edited in place, and
# carries in-progress work). Say so loudly when it has drifted off the pin, so a build that
# is not reproducible from the patch stack is at least not a silent one.
vendor_head="$(git -C "$SRC" rev-parse HEAD 2>/dev/null || echo '?')"
if [ "$vendor_head" != "$LLVM_MOS_PIN" ]; then
  echo "    WARNING: vendor/ is at ${vendor_head:0:12}, not the pin ${LLVM_MOS_PIN:0:12}."
  echo "             This build is NOT reproducible from patches/llvm-mos/ alone. Either move"
  echo "             LLVM_MOS_PIN (and regenerate 0002 against the new base), or rebuild from a"
  echo "             fresh vendor/ checkout."
fi

# Trim the upstream MOS distribution to just clang + lld + the mos builtins. The
# stock cache also builds clang-tools-extra (clangd, clang-tidy, include-fixer, …) —
# heavy and irrelevant to codegen. We only need a working mos cross-compiler. Idempotent
# (no-op once patched); vendor/ is gitignored and disposable. Drop the 5 clang-tools-extra
# distribution components so install-distribution doesn't reference unbuilt targets.
echo "==> trim distribution to clang+lld (drop clang-tools-extra)"
sed -i \
  -e 's/clang;clang-tools-extra;lld/clang;lld/' \
  -e '/^[[:space:]]*clang-apply-replacements[[:space:]]*$/d' \
  -e '/^[[:space:]]*clang-include-fixer[[:space:]]*$/d' \
  -e '/^[[:space:]]*clang-tidy[[:space:]]*$/d' \
  -e '/^[[:space:]]*clangd[[:space:]]*$/d' \
  -e '/^[[:space:]]*find-all-symbols[[:space:]]*$/d' \
  "$SRC/clang/cmake/caches/MOS.cmake"

echo "==> configure (MOS.cmake cache, Release, host clang+lld, 1 link job, ccache)"
# Absolute host-clang paths: /opt/llvm-mos/bin is first on PATH (it holds the mos
# CROSS compiler, which can't build host binaries), so a bare `clang` would resolve
# there and fail the compiler check. The apt-installed host clang lives in /usr/bin.
cmake -C "$SRC/clang/cmake/caches/MOS.cmake" -G Ninja \
  -S "$SRC/llvm" -B "$BUILDDIR" \
  -DCMAKE_BUILD_TYPE=Release \
  -DCMAKE_INSTALL_PREFIX="$INSTALL" \
  -DCMAKE_C_COMPILER=/usr/bin/clang -DCMAKE_CXX_COMPILER=/usr/bin/clang++ \
  -DCMAKE_ASM_COMPILER=/usr/bin/clang \
  -DLLVM_USE_LINKER=lld \
  -DLLVM_PARALLEL_LINK_JOBS=1 \
  -DLLVM_CCACHE_BUILD=On

echo "==> build the distribution target (-j$JOBS); first build is long (~30-90 min)"
cmake --build "$BUILDDIR" --target distribution --parallel "$JOBS"

echo "==> install-distribution -> $INSTALL"
cmake --build "$BUILDDIR" --target install-distribution

# The "distribution" component list above is clang+lld only (see the trim step),
# so it never rebuilds the tools llvm/test/CodeGen/MOS + llvm/test/MC/MOS lit
# suites actually invoke in their RUN lines: llc, opt, llvm-mc, llvm-objdump,
# llvm-readobj, FileCheck, not (checked by grepping the RUN lines — not guessed;
# llvm-lit itself is a configure-time-generated script, not a build target, so
# it needs no rebuild here). A green toolchain build could leave $BUILDDIR/bin/llc
# months stale while clang/lld moved on, producing a false lit reading (it did,
# during the 0040 work: 13-vs-9). Same in-tree build dir, same container
# invocation, so this stays incremental (ccache-warm, ninja no-ops anything
# already current) — see docs/agent-handoff.md SECOND GOTCHA / dev/run.sh lit.
echo "==> refresh the lit tool set in $BUILDDIR (-j$JOBS)"
cmake --build "$BUILDDIR" --target llc opt llvm-mc llvm-objdump llvm-readobj FileCheck not --parallel "$JOBS"

echo "==> done in $((SECONDS/60))m $((SECONDS%60))s: $("$INSTALL/bin/mos-clang" --version | head -1)"
echo "    use it: MOS_TOOLCHAIN=/work/build/llvm-mos-install dev/run.sh build && ... corpus"
echo "    lit: dev/run.sh lit [PATHS...]   (runs llvm-lit -s against the MOS suites; refreshes these tools first)"
