#!/usr/bin/env bash
# dev/toolchain.sh — build llvm-mos (clang/lld) FROM SOURCE, for M1 codegen work.
#
# The bench's default toolchain is a prebuilt, immutable tarball (/opt/llvm-mos);
# you cannot change codegen without building the compiler. This clones llvm-mos into
# vendor/ (gitignored), builds into build/llvm-mos, installs to build/llvm-mos-install,
# then point the bench at it with MOS_TOOLCHAIN=/work/build/llvm-mos-install:
#   MOS_TOOLCHAIN=/work/build/llvm-mos-install dev/run.sh build && ... corpus
# Runs INSIDE the dev container (clang/lld/ccache/cmake/ninja present). Drive from the
# host: dev/run.sh toolchain. See docs/plans/2026-06-14-m1-from-source-toolchain.md.
#
# RAM is the binding constraint (14 GiB host): Release + lld + a single link job keep
# peak memory down; ccache (persisted in build/.ccache) makes later rebuilds fast.
# Compile parallelism defaults conservative; raise/lower with BUILD_JOBS if it swaps.
set -euo pipefail

usage() {
  echo "Usage: dev/run.sh toolchain   # build llvm-mos clang/lld from source -> build/llvm-mos-install"
  echo "Env: BUILD_JOBS (compile parallelism, default 6 — lower if the 14 GiB host swaps)"
  exit 0
}
[ "${1-}" = "-h" ] || [ "${1-}" = "--help" ] && usage

ROOT=/work
SRC="$ROOT/vendor/llvm-mos"
BUILDDIR="$ROOT/build/llvm-mos"
INSTALL="$ROOT/build/llvm-mos-install"
JOBS="${BUILD_JOBS:-6}"
export CCACHE_DIR="$ROOT/build/.ccache"
# /opt/llvm-mos/bin (the mos CROSS toolchain) is first on the image PATH and shadows
# host tools — a bare clang/llvm-ar/assembler there targets mos, not x86-64. Put host
# /usr/bin first for this host build so every tool (incl. the .S assembler) is native.
export PATH="/usr/bin:$PATH"

echo "==> clone llvm-mos (shallow main) into vendor/ (gitignored)"
if [ ! -d "$SRC/.git" ]; then
  git clone --depth 1 https://github.com/llvm-mos/llvm-mos.git "$SRC"
  # Apply our tracked backend patches to the fresh clone. These are the eventual
  # upstream PR diffs, kept in-repo so a clean build reproduces our compiler.
  #
  # NOT a blind `patches/llvm-mos/*.patch` glob. `0002-321-accum16.patch` is
  # regenerated by `dev/regen-patch.sh` as a full rsync mirror of the LIVE
  # llvm/lib/Target/MOS directory (see that script's MOSREL), so it already
  # contains every MOS-BACKEND-DIR hunk that 0004-0015 carry — reapplying those
  # here would double-insert and fail. They stay on disk as standalone,
  # individually reviewable upstream-PR artifacts (several are still-unposted PR
  # drafts; see docs/upstream-contribution-status.md).
  #
  # CRITICAL: 0002's mirror covers ONLY llvm/lib/Target/MOS/. Any hunk a patch
  # makes OUTSIDE that directory (generic LLVM, clang) is NOT in 0002 and MUST
  # be applied here or the build breaks. Exactly two patches have such hunks:
  #   0001 - clang far-pointer support + TargetDataLayout (applied whole; its
  #          MOS-dir hunks are the base 0002 was mirrored on top of).
  #   0006 - packed-24: adds the generic AsmPrinter::emitNonStandardSizedConstant
  #          virtual hook (AsmPrinter.h + the emitGlobalConstantImpl call site)
  #          plus a clang Targets/MOS.cpp hunk. MOSAsmPrinter.cpp OVERRIDES that
  #          hook, and that override lives in 0002 — so omitting 0006's generic
  #          half yields "only virtual member functions can be marked 'override'"
  #          at MOSAsmPrinter.cpp. Applied PATH-FILTERED to just the non-MOS-dir
  #          hunks (its MOS-dir half is already in 0002).
  # (0015's only non-MOS file is a lit test — irrelevant to a build. 0016/0017
  # are MOS-dir-only and were folded into 0002 by the 2026-07-26 regen; their
  # files remain on disk as standalone upstream-PR artifacts like 0004-0015.)
  #
  # When adding a new patch: if it touches only llvm/lib/Target/MOS/, fold it
  # into 0002 via dev/regen-patch.sh and leave this list alone; if it touches
  # anything outside that dir, that portion must be added here.
  # See docs/plans/2026-07-25-llvm-mos-fork-patch-stack-upstream-rebase.md.
  apply_patch() {
    local p="$ROOT/patches/llvm-mos/$1.patch"; shift
    [ -e "$p" ] || { echo "FATAL: missing $p"; exit 1; }
    echo "    applying patch $(basename "$p")${1:+ (path-filtered)}"
    git -C "$SRC" apply "$@" "$p"
  }
  apply_patch 0001-320-far-addrspace
  apply_patch 0002-321-accum16
  # generic-LLVM + clang half only; the MOS-dir half is already inside 0002
  apply_patch 0006-320-packed24 \
    --include='clang/*' --include='llvm/include/*' --include='llvm/lib/CodeGen/*'
fi
echo "    commit: $(git -C "$SRC" rev-parse --short HEAD 2>/dev/null || echo '?')$(git -C "$SRC" diff --quiet -- llvm/lib/Target/MOS 2>/dev/null || echo ' +patched')"

# Trim the upstream MOS distribution to just clang + lld + the mos builtins. The
# stock cache also builds clang-tools-extra (clangd, clang-tidy, include-fixer, …) —
# heavy and irrelevant to codegen. We only need a working mos cross-compiler. Idempotent
# (no-op once patched); vendor/ is gitignored and disposable. Drop the 5 clang-tools-extra
# distribution components so install-distribution doesn't reference unbuilt targets.
echo "==> trim distribution to clang+lld (drop clang-tools-extra)"
sed -i \
  -e 's/clang;clang-tools-extra;lld/clang;lld/' \
  -e '/^[[:space:]]*clang-apply-replacements[[:space:]]*$/d' \
  -e '/^[[:space:]]*clang-include-fixer[[:space:]]*$/d' \
  -e '/^[[:space:]]*clang-tidy[[:space:]]*$/d' \
  -e '/^[[:space:]]*clangd[[:space:]]*$/d' \
  -e '/^[[:space:]]*find-all-symbols[[:space:]]*$/d' \
  "$SRC/clang/cmake/caches/MOS.cmake"

echo "==> configure (MOS.cmake cache, Release, host clang+lld, 1 link job, ccache)"
# Absolute host-clang paths: /opt/llvm-mos/bin is first on PATH (it holds the mos
# CROSS compiler, which can't build host binaries), so a bare `clang` would resolve
# there and fail the compiler check. The apt-installed host clang lives in /usr/bin.
cmake -C "$SRC/clang/cmake/caches/MOS.cmake" -G Ninja \
  -S "$SRC/llvm" -B "$BUILDDIR" \
  -DCMAKE_BUILD_TYPE=Release \
  -DCMAKE_INSTALL_PREFIX="$INSTALL" \
  -DCMAKE_C_COMPILER=/usr/bin/clang -DCMAKE_CXX_COMPILER=/usr/bin/clang++ \
  -DCMAKE_ASM_COMPILER=/usr/bin/clang \
  -DLLVM_USE_LINKER=lld \
  -DLLVM_PARALLEL_LINK_JOBS=1 \
  -DLLVM_CCACHE_BUILD=On

echo "==> build the distribution target (-j$JOBS); first build is long (~30-90 min)"
cmake --build "$BUILDDIR" --target distribution --parallel "$JOBS"

echo "==> install-distribution -> $INSTALL"
cmake --build "$BUILDDIR" --target install-distribution

echo "==> done in $((SECONDS/60))m $((SECONDS%60))s: $("$INSTALL/bin/mos-clang" --version | head -1)"
echo "    use it: MOS_TOOLCHAIN=/work/build/llvm-mos-install dev/run.sh build && ... corpus"
