; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=mos -mcpu=mos6502 -verify-machineinstrs < %s | FileCheck %s --check-prefix=MOS6502
; RUN: llc -mtriple=mos -mcpu=mosw65816 -verify-machineinstrs < %s | FileCheck %s --check-prefix=W65816

; The opt-in 65816 native-width registers must not change register pressure,
; and so code, for subtargets that don't enable them. Pressure sets derived
; from Ac16, Xc16 and Yc16 would move the low-byte subtraction of this compare
; in both modes. The expected output is the one without those registers.

target datalayout = "e-m:e-p:16:8-p1:8:8-i16:8-i32:8-i64:8-f32:8-f64:8-a:8-Fi8-n8"

define i16 @scmp_i16_i32(i32 %a, i32 %b) {
; MOS6502-LABEL: scmp_i16_i32:
; MOS6502:       ; %bb.0:
; MOS6502-NEXT:    sta __rc9
; MOS6502-NEXT:    stx __rc8
; MOS6502-NEXT:    ldy __rc7
; MOS6502-NEXT:    pha
; MOS6502-NEXT:    lda __rc4
; MOS6502-NEXT:    sta __rc11
; MOS6502-NEXT:    pla
; MOS6502-NEXT:    cmp __rc4
; MOS6502-NEXT:    txa
; MOS6502-NEXT:    ldx __rc5
; MOS6502-NEXT:    stx __rc10
; MOS6502-NEXT:    sbc __rc5
; MOS6502-NEXT:    lda __rc2
; MOS6502-NEXT:    sbc __rc6
; MOS6502-NEXT:    lda __rc3
; MOS6502-NEXT:    sty __rc5
; MOS6502-NEXT:    sty __rc4
; MOS6502-NEXT:    sbc __rc4
; MOS6502-NEXT:    bvc .LBB0_2
; MOS6502-NEXT:  ; %bb.1:
; MOS6502-NEXT:    eor #128
; MOS6502-NEXT:  .LBB0_2:
; MOS6502-NEXT:    ldx #255
; MOS6502-NEXT:    ldy #255
; MOS6502-NEXT:    cmp #0
; MOS6502-NEXT:    bmi .LBB0_9
; MOS6502-NEXT:  ; %bb.3:
; MOS6502-NEXT:    ldx __rc11
; MOS6502-NEXT:    cpx __rc9
; MOS6502-NEXT:    lda __rc10
; MOS6502-NEXT:    sbc __rc8
; MOS6502-NEXT:    lda __rc6
; MOS6502-NEXT:    sbc __rc2
; MOS6502-NEXT:    lda __rc5
; MOS6502-NEXT:    sbc __rc3
; MOS6502-NEXT:    bvc .LBB0_5
; MOS6502-NEXT:  ; %bb.4:
; MOS6502-NEXT:    eor #128
; MOS6502-NEXT:  .LBB0_5:
; MOS6502-NEXT:    tax
; MOS6502-NEXT:    bpl .LBB0_7
; MOS6502-NEXT:  ; %bb.6:
; MOS6502-NEXT:    ldy #1
; MOS6502-NEXT:    jmp .LBB0_8
; MOS6502-NEXT:  .LBB0_7:
; MOS6502-NEXT:    ldy #0
; MOS6502-NEXT:  .LBB0_8:
; MOS6502-NEXT:    ldx #0
; MOS6502-NEXT:  .LBB0_9:
; MOS6502-NEXT:    tya
; MOS6502-NEXT:    rts
;
; W65816-LABEL: scmp_i16_i32:
; W65816:       ; %bb.0:
; W65816-NEXT:    sta __rc9
; W65816-NEXT:    stx __rc8
; W65816-NEXT:    ldy __rc7
; W65816-NEXT:    pha
; W65816-NEXT:    lda __rc4
; W65816-NEXT:    sta __rc11
; W65816-NEXT:    pla
; W65816-NEXT:    cmp __rc4
; W65816-NEXT:    txa
; W65816-NEXT:    ldx __rc5
; W65816-NEXT:    stx __rc10
; W65816-NEXT:    sbc __rc5
; W65816-NEXT:    lda __rc2
; W65816-NEXT:    sbc __rc6
; W65816-NEXT:    lda __rc3
; W65816-NEXT:    sty __rc5
; W65816-NEXT:    sty __rc4
; W65816-NEXT:    sbc __rc4
; W65816-NEXT:    bvc .LBB0_2
; W65816-NEXT:  ; %bb.1:
; W65816-NEXT:    eor #128
; W65816-NEXT:  .LBB0_2:
; W65816-NEXT:    ldx #255
; W65816-NEXT:    txy
; W65816-NEXT:    cmp #0
; W65816-NEXT:    bmi .LBB0_9
; W65816-NEXT:  ; %bb.3:
; W65816-NEXT:    ldx __rc11
; W65816-NEXT:    cpx __rc9
; W65816-NEXT:    lda __rc10
; W65816-NEXT:    sbc __rc8
; W65816-NEXT:    lda __rc6
; W65816-NEXT:    sbc __rc2
; W65816-NEXT:    lda __rc5
; W65816-NEXT:    sbc __rc3
; W65816-NEXT:    bvc .LBB0_5
; W65816-NEXT:  ; %bb.4:
; W65816-NEXT:    eor #128
; W65816-NEXT:  .LBB0_5:
; W65816-NEXT:    tax
; W65816-NEXT:    bpl .LBB0_7
; W65816-NEXT:  ; %bb.6:
; W65816-NEXT:    ldy #1
; W65816-NEXT:    bra .LBB0_8
; W65816-NEXT:  .LBB0_7:
; W65816-NEXT:    ldy #0
; W65816-NEXT:  .LBB0_8:
; W65816-NEXT:    ldx #0
; W65816-NEXT:  .LBB0_9:
; W65816-NEXT:    tya
; W65816-NEXT:    rts
  %r = call i16 @llvm.scmp.i16.i32(i32 %a, i32 %b)
  ret i16 %r
}

declare i16 @llvm.scmp.i16.i32(i32, i32)
