#!/usr/bin/env python3
# tools/gen-65816-oracle.py — normalise the 65c816 opcode matrix from the (CC0)
# GTE/WDC G65SC816 datasheet text into a flat TSV oracle used to audit the
# llvm-mos backend's 65816 encodings (tools/gen-65816-ref.py).
#
# Source: larsbrinkhoff/awesome-cpus MCS6500/65c816.txt — released CC0 (public
# domain); a text transcription of the datasheet's "Table 8. Opcode Matrix".
# Provenance + sha256: docs/refs/65816/SOURCES.md. Fetch the raw file with
# dev/fetch-65816-oracle.sh (it lands gitignored under docs/refs/65816/oracle/).
#
# The matrix is a 16x16 grid (MSD rows x LSD columns); each cell is "MNEM mode"
# over a "bytes cycles" line. We emit one TSV row per defined opcode:
#     OPCODEHEX <tab> MNEMONIC <tab> MODE <tab> BYTES
#
#   tools/gen-65816-oracle.py docs/refs/65816/oracle/65c816-datasheet.txt \
#       > docs/refs/65816/oracle-65c816-opcodes.tsv
import re
import sys

ROW = re.compile(r"^([0-9A-Fa-f]) \|(.*)\| [0-9A-Fa-f]\s*$")


def cells(line: str) -> list[str]:
    return [c.strip() for c in line.split("|")][1:17]


def main(argv: list[str]) -> int:
    if len(argv) != 2 or argv[1] in ("-h", "--help"):
        print(__doc__)
        return 0 if len(argv) == 2 and argv[1] in ("-h", "--help") else 2

    lines = open(argv[1], encoding="latin-1").read().splitlines()
    rows: list[tuple[int, str, str, int]] = []
    for i, line in enumerate(lines):
        m = ROW.match(line)
        if not m:
            continue
        if i + 1 >= len(lines):
            break
        msd = int(m.group(1), 16)
        mnem_cells = cells(line)
        cyc_cells = cells(lines[i + 1])
        if len(mnem_cells) != 16 or len(cyc_cells) != 16:
            continue
        for col in range(16):
            cell = mnem_cells[col]
            if not cell or cell.lower().startswith("reserve"):
                continue
            mnem = cell[:3].upper()
            if not mnem.isalpha():
                continue
            mode = cell[3:].strip() or "i"   # bare mnemonic = implied
            cyc = cyc_cells[col].split()
            nbytes = int(cyc[0]) if cyc and cyc[0].isdigit() else 0
            rows.append((msd * 16 + col, mnem, mode, nbytes))

    if len(rows) < 200:
        sys.exit(f"only parsed {len(rows)} opcodes — matrix format unexpected?")

    rows.sort()
    print("# opcode\tmnemonic\tmode\tbytes  — generated by tools/gen-65816-oracle.py")
    print("# canonical 65c816 opcode matrix (CC0 GTE/WDC datasheet); audit oracle, NOT redistributed verbatim")
    for op, mnem, mode, nbytes in rows:
        print(f"{op:02X}\t{mnem}\t{mode}\t{nbytes}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
