#!/usr/bin/env python3
# tools/gen-sqrt-lut.py — emit the Q8.8 integer square-root lookup table baked into
# examples/65816/k_hopalong.c (the Hopalong / Blossom attractor kernel).
#
# The Hopalong step needs sqrt(|b*x - c|). With no FPU on the 65816 we follow the
# 1989 Blossom approach (BLOSSOM.TBL): a precomputed sqrt table indexed by the
# INTEGER part of the (non-negative) Q8.8 argument, i.e. `arg >> FRAC`. Entry i is
# round(sqrt(i) * 2**FRAC) — itself a Q8.8 value. 256 entries x 2 bytes = 512 B rodata.
#
# Deterministic and host/target-identical by construction (pure integer table), so it
# is safe inside the differential gate (host == default == +mos-a16, both emulators).
#
# Regenerate the array in k_hopalong.c with:
#   tools/gen-sqrt-lut.py                # 256 entries, Q8.8  (default)
#   tools/gen-sqrt-lut.py --entries 256 --frac 8
import argparse
import math
import sys


def build(entries: int, frac: int) -> list[int]:
    scale = 1 << frac
    lut = []
    for i in range(entries):
        v = round(math.sqrt(i) * scale)
        if v > 0xFFFF:
            sys.exit(f"entry {i} = {v} overflows uint16 (raise frac headroom or lower entries)")
        lut.append(v)
    return lut


def emit(lut: list[int], frac: int) -> str:
    out = [
        f"// Q{16 - frac}.{frac} sqrt LUT, {len(lut)} entries — generated by tools/gen-sqrt-lut.py.",
        f"// SQRT_LUT[i] = round(sqrt(i) * {1 << frac}); index with `|b*x - c| >> {frac}` (integer part).",
        f"static const unsigned short SQRT_LUT[{len(lut)}] = {{",
    ]
    for r in range(0, len(lut), 8):
        row = ", ".join(f"0x{v:04X}" for v in lut[r:r + 8])
        out.append(f"  {row},")
    out.append("};")
    return "\n".join(out)


def main() -> None:
    ap = argparse.ArgumentParser(description="Emit the Q8.8 integer sqrt LUT for k_hopalong.c")
    ap.add_argument("--entries", type=int, default=256, help="table size (default 256)")
    ap.add_argument("--frac", type=int, default=8, help="fractional bits / Q-format (default 8)")
    args = ap.parse_args()
    print(emit(build(args.entries, args.frac), args.frac))


if __name__ == "__main__":
    main()
