#!/usr/bin/env python3
# Generate examples/65816/epicycles_tables.h — the baked Fourier (DFT) coefficients of a target
# outline for the #10 Fourier-epicycles SNES demo. A sum of rotating vectors
#   P(t) = Σ_k c_k · exp(i·2π·f_k·t)
# traces the shape; each c_k = (re,im) is one epicycle's vector at t=0. We sample a closed path,
# take its DFT, and keep the frequencies in [-NHARM, NHARM] as fixed-point coefficients.
#
# Fixed point: coefficients are stored as round(Re/Im(c_k) · 2^CBITS) in PIXEL units, so the target
# renderer computes  tip = Σ (re·cos_Q8.8 − im·sin_Q8.8) >> (8 + CBITS)  → pixels.  cos/sin are the
# Q8.8 LUT (256 = 1.0). The coefficient order is by |c_k| descending so a truncated prefix is the
# best low-order approximation (and the demo can grow the vector count for a nice reveal).
#
# Usage: python3 tools/gen-epicycles-tables.py > examples/65816/epicycles_tables.h
import math

RO     = 46     # 5-pointed star outer radius (px) — within the 128px canvas (centre ±63)
RI     = 18     # inner radius (px)
M      = 512    # path samples for the DFT
NHARM  = 20     # keep frequencies -NHARM..NHARM
CBITS  = 6      # extra fractional bits on each coefficient (precision for small harmonics)

# 10 alternating outer/inner vertices of a 5-pointed star, traced CCW. Rotated ~23° off vertical
# (ROT) to break the y-axis symmetry — otherwise every coefficient is purely imaginary and the
# real-part multiplies (re·cos, re·sin) fold to ×0, halving the very stress this demo exists for.
ROT = 0.40
_VERTS = []
for i in range(10):
    ang = math.pi / 2 + ROT + i * (math.pi / 5)   # 36° steps
    r = RO if i % 2 == 0 else RI
    _VERTS.append(complex(r * math.cos(ang), r * math.sin(ang)))

def star_path(t):  # t in [0,1) → CCW star perimeter, complex x+iy, centred on origin
    s = (t % 1.0) * 10.0
    i = int(s) % 10
    f = s - int(s)
    a, b = _VERTS[i], _VERTS[(i + 1) % 10]
    return a + (b - a) * f

# DFT: c_k = (1/M) Σ_s path(s/M) · exp(-i·2π·k·s/M)
samples = [star_path(s / M) for s in range(M)]
coeffs = []
for k in range(-NHARM, NHARM + 1):
    acc = 0j
    for s in range(M):
        acc += samples[s] * complex(math.cos(-2*math.pi*k*s/M), math.sin(-2*math.pi*k*s/M))
    coeffs.append((k, acc / M))

# Order by magnitude (largest vector first) so a prefix is the best approximation.
coeffs.sort(key=lambda kc: -abs(kc[1]))

scale = 1 << CBITS
rows = []
for f, c in coeffs:
    re = round(c.real * scale)
    im = round(c.imag * scale)
    if re == 0 and im == 0:
        continue                       # drop vanishing harmonics
    rows.append((f, re, im, abs(c)))

N = len(rows)
mx = max(max(abs(r), abs(i)) for _, r, i, _ in rows)
assert mx < 32768, f"coefficient {mx} overflows int16 — lower CBITS or A"

print("// AUTO-GENERATED by tools/gen-epicycles-tables.py — do not edit by hand.")
print("// Fourier (DFT) coefficients of a 5-pointed-star outline for the #10 epicycles demo.")
print(f"// {N} harmonics; coefficients = round(c_k * 2^{CBITS}) in pixels; star outer radius {RO}px.")
print("#ifndef EPICYCLES_TABLES_H")
print("#define EPICYCLES_TABLES_H")
print("#include <stdint.h>")
print(f"#define EPI_NHARM   {N}u    // number of rotating vectors (epicycles)")
print(f"#define EPI_CBITS   {CBITS} // coefficient fractional bits (tip shift = 8 + EPI_CBITS)")
print(f"#define EPI_SHIFT   {8 + CBITS}")
print("// Per harmonic: signed integer frequency (cycles per period), and the Q-coefficient (re,im).")
print("static const int8_t  EPI_FREQ[EPI_NHARM] = {", ", ".join(str(f) for f, _, _, _ in rows), "};")
print("static const int16_t EPI_RE[EPI_NHARM]   = {", ", ".join(str(r) for _, r, _, _ in rows), "};")
print("static const int16_t EPI_IM[EPI_NHARM]   = {", ", ".join(str(i) for _, _, i, _ in rows), "};")
print("#endif /* EPICYCLES_TABLES_H */")
