#!/usr/bin/env python3
# tools/gen-cordic-tables.py — generate the Q2.14 CORDIC constant tables for the Phase 2
# trig compiler-test (examples/65816/k_trig16.c via examples/65816/cordic16.h).
#
# CORDIC is a SHIFT-AND-ADD algorithm: no multiply, no divide. The only precomputed data is
# the per-iteration rotation-angle table atan(2^-i) and the inverse-gain constant 1/An. This
# script derives both from the standard math (deterministic, no magic numbers) and emits a
# committed, regenerable C header. Re-run after changing N or the fixed-point format:
#
#     python3 tools/gen-cordic-tables.py            # -> examples/65816/cordic16_tables.h
#     python3 tools/gen-cordic-tables.py --check    # verify the committed header is in sync
#
# Format: Q2.14 (int16_t, 14 fractional bits). ONE = 1<<14 = 16384, value = raw/ONE,
# representable range [-2, +2). sin/cos outputs in [-1,1] fit; angles must stay in
# [-pi/2, +pi/2] (< the CORDIC convergence radius sum(atan 2^-i) ~ 1.7433 rad).
#
# Plan: docs/plans/2026-06-26-trig-phase2-q214-cordic.md.
import argparse
import math
import os
import sys

FRAC = 14                       # fractional bits  -> Q2.14
ONE = 1 << FRAC                 # 16384
N = 15                          # iterations: one per fractional bit (+1); shift i runs 0..N-1
HEADER = os.path.join(os.path.dirname(__file__), "..", "examples", "65816", "cordic16_tables.h")


def q214(x):
    """Round a real to a Q2.14 raw int16, asserting it is representable."""
    r = int(round(x * ONE))
    if not (-32768 <= r <= 32767):
        sys.exit(f"FATAL: {x} -> {r} does not fit int16 Q2.14")
    return r


def derive():
    atan = [q214(math.atan(2.0 ** -i)) for i in range(N)]
    An = 1.0
    for i in range(N):
        An *= math.sqrt(1.0 + 2.0 ** (-2 * i))
    k = q214(1.0 / An)                       # inverse CORDIC gain (rotation-mode x0)
    half_pi = q214(math.pi / 2.0)            # convergence/range reference (fits: 25736)
    conv = sum(math.atan(2.0 ** -i) for i in range(N))   # convergence radius, real radians
    return atan, k, half_pi, An, conv


def hyper_schedule(maxi=14):
    """Hyperbolic CORDIC iteration index schedule. Steps i=4,13,40,... must REPEAT for the
    product to converge (the standard correction); shifts start at i=1 (atanh(2^0) diverges)."""
    sched, i, repeat_at = [], 1, 4
    while i <= maxi:
        sched.append(i)
        if i == repeat_at:
            sched.append(i)
            repeat_at = 3 * repeat_at + 1
        i += 1
    return sched


def derive_h():
    sched = hyper_schedule()
    atanh = [q214(math.atanh(2.0 ** -i)) for i in sched]
    An = 1.0
    for i in sched:
        An *= math.sqrt(1.0 - 2.0 ** (-2 * i))
    hgain = q214(1.0 / An)                    # post-scale: result *= 1/An_h (seed x0 = ONE)
    conv = sum(math.atanh(2.0 ** -i) for i in sched)
    return sched, atanh, hgain, An, conv


def render():
    atan, k, half_pi, An, conv = derive()
    rows = "\n".join(
        f"  {v:6d},   // atan(2^-{i:<2d}) = {math.atan(2.0**-i):.10f} rad" for i, v in enumerate(atan)
    )
    sched, atanh, hgain, anh, convh = derive_h()
    nh = len(sched)
    hrows = "\n".join(
        f"  {v:6d},   // atanh(2^-{i:<2d}) = {math.atanh(2.0**-i):.10f}" for i, v in zip(sched, atanh)
    )
    sched_row = ", ".join(str(i) for i in sched)
    return f"""\
// examples/65816/cordic16_tables.h — GENERATED by tools/gen-cordic-tables.py. DO NOT EDIT.
// Q2.14 CORDIC constants for the Phase 2 (circular) + Phase 3 (hyperbolic) trig compiler-test.
// Regenerate with:
//     python3 tools/gen-cordic-tables.py
// Plans: docs/plans/2026-06-26-trig-phase2-q214-cordic.md,
//        docs/plans/2026-06-26-trig-phase3-derived-hyperbolic.md.
#ifndef CORDIC16_TABLES_H
#define CORDIC16_TABLES_H
#include <stdint.h>

// Q2.14 fixed point: value = raw / CORDIC16_ONE, representable range [-2, +2).
#define CORDIC16_FRAC     {FRAC}
#define CORDIC16_ONE      {ONE}        // 1.0 in Q2.14
#define CORDIC16_N        {N}          // CORDIC iterations (shift i = 0 .. N-1)
#define CORDIC16_HALFPI   {half_pi}        // pi/2 in Q2.14 (rotation input bound)

// Per-iteration rotation angle atan(2^-i), Q2.14. CORDIC convergence radius =
// sum(atan 2^-i) = {conv:.6f} rad (> pi/2 = {math.pi/2:.6f}), so any angle in
// [-pi/2, pi/2] converges. Inverse gain 1/An with An = {An:.10f}.
static const int16_t cordic16_atan_tbl[CORDIC16_N] = {{
{rows}
}};

// Rotation-mode seed x0 = 1/An (gain compensation): after N rotations of (x0, 0) by `angle`,
// (x, y) = (cos angle, sin angle) with unit magnitude in Q2.14.
#define CORDIC16_K        {k}        // round(ONE / An)

// ---- Phase 3: HYPERBOLIC CORDIC ------------------------------------------------------------
// Hyperbolic mode rotates by atanh(2^-i). Steps i=4,13,40,... must REPEAT for convergence, and
// shifts start at i=1 (atanh(2^0) diverges). Convergence radius sum(atanh 2^-i) = {convh:.6f}
// (> 1.0), so any angle in [-1, 1] converges. Unlike circular mode the seed is x0 = ONE (NOT
// 1/An_h) to keep the fast-growing cosh inside int16; the result is gain-corrected by *CORDIC16_HGAIN
// at the end (tanh = y/x needs no correction — the gain cancels). An_h = {anh:.10f}.
#define CORDIC16_NH       {nh}          // hyperbolic schedule length (with repeats)
static const uint8_t cordic16_hsched[CORDIC16_NH] = {{ {sched_row} }};   // shift index per step
static const int16_t cordic16_atanh_tbl[CORDIC16_NH] = {{
{hrows}
}};
#define CORDIC16_HGAIN    {hgain}        // round(ONE / An_h): post-scale cosh/sinh (seed x0 = ONE)

#endif // CORDIC16_TABLES_H
"""


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="verify the committed header matches")
    args = ap.parse_args()
    text = render()
    path = os.path.normpath(HEADER)
    if args.check:
        cur = open(path).read() if os.path.exists(path) else ""
        if cur != text:
            sys.exit(f"OUT OF SYNC: {path} differs from generator output; re-run without --check")
        print(f"in sync: {path}")
        return
    with open(path, "w") as f:
        f.write(text)
    atan, k, half_pi, An, conv = derive()
    sched, atanh, hgain, anh, convh = derive_h()
    print(f"wrote {path}: N={N} ONE={ONE} K={k} HALFPI={half_pi} conv={conv:.6f}rad")
    print(f"  hyperbolic: NH={len(sched)} sched={sched} HGAIN={hgain} convh={convh:.6f}")


if __name__ == "__main__":
    main()
