#!/usr/bin/env python3
"""Emit the libfixmath sin LUT as a .far_rodata assembly object for the SNES HiROM target.

The mos frontend's size_t is 16-bit, so a single C array > 64 KiB is rejected ("array is too
large"). libfixmath's _fix16_sin_lut is 102688 x uint16 (~200 KiB), so on the target it can't be a
C array. Instead we declare it `extern const FAR uint16_t _fix16_sin_lut[]` (incomplete -> no size
check) and provide the bytes from this generated .s, placed in .far_rodata (HiROM banks $C1+).

The values are parsed from the SAME header the host oracle compiles inline
(examples/65816/libfixmath/fix16_trig_sin_lut.h), so host (inline array) == target (asm data)
bit-for-bit — which the differential requires.

Usage: gen-sin-lut-asm.py <fix16_trig_sin_lut.h> <out.s>
"""
import re
import sys


def main(argv: list[str]) -> int:
    if len(argv) != 3 or argv[1] in ("-h", "--help"):
        print(__doc__)
        return 0 if len(argv) >= 2 and argv[1] in ("-h", "--help") else 2

    src, out = argv[1], argv[2]
    text = open(src).read()
    # Extract the initializer body of _fix16_sin_lut[...] = { ... };
    m = re.search(r"_fix16_sin_lut\[\d+\]\s*(?:[A-Za-z_()0-9 ]*)?=\s*\{(.*?)\}", text, re.S)
    if not m:
        print("error: could not find _fix16_sin_lut initializer", file=sys.stderr)
        return 1
    vals = [int(v) for v in re.findall(r"-?\d+", m.group(1))]
    if not vals:
        print("error: no LUT values parsed", file=sys.stderr)
        return 1

    lines = [
        "; Generated by tools/gen-sin-lut-asm.py from fix16_trig_sin_lut.h — do not edit.",
        "; libfixmath's sin LUT (102688 x uint16, ~200 KiB) in HiROM far rodata; the C side",
        "; declares `extern const FAR uint16_t _fix16_sin_lut[]` (see the header, TRIG_FAR_LUT).",
        '.section .far_rodata,"a",@progbits',
        ".global _fix16_sin_lut",
        ".balign 2",
        "_fix16_sin_lut:",
    ]
    # Emit 16 little-endian halfwords per line for compactness.
    for i in range(0, len(vals), 16):
        chunk = ", ".join("0x%04x" % (v & 0xFFFF) for v in vals[i:i + 16])
        lines.append("  .2byte " + chunk)
    lines.append("")
    open(out, "w").write("\n".join(lines))
    print(f"{out}: {len(vals)} entries ({len(vals) * 2} bytes) -> .far_rodata")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
