#!/usr/bin/env python3
"""Emit the far cross-bank test table `tbl` as a .far_rodata assembly object (HiROM banks $C1+).

The mos frontend's size_t is 16-bit, so a single C array > 64 KiB is rejected ("array is too
large"). This table is 98304 x uint16 (= 3 x 32768 = 192 KiB), so on the target it can't be a C
array. examples/65816/farindex.c instead declares `extern const FAR uint16_t tbl[]` (incomplete ->
no size check) and reads its bytes from this generated .s, placed in .far_rodata (HiROM banks $C1+).

VALUE CONTRACT (must stay in lockstep with farindex.c's -DHOST `READ` macro):

    tbl[i] = (i + (i >> 16)) & 0xFFFF

The host oracle computes the identical closed form, so host (formula) == target (asm data)
bit-for-bit — which the differential requires. Crucially the `+ (i >> 16)` term makes the stored
value depend on the BANK ordinal of the element, so a far read whose `index*2` mis-carries into the
wrong bank reads a DIFFERENT value: each of the three probe reads independently catches the bug that
"far data > 2 banks" was deferred on (the clang far-subscript bank-byte carry, fixed in
patches/llvm-mos/0001). With a plain `i & 0xFFFF` the bank-$C3 probe would alias its own bug
(90000 truncated to i16 = 24464 == 90000 & 0xFFFF) and fail to regress-detect.

N = 98304 places the three probe indices in three distinct banks (tbl based at $C10000):
    tbl[100]    off $000C8 -> $C100C8  bank $C1   (within-first-bank control)
    tbl[50000]  off $186A0 -> $C286A0  bank $C2
    tbl[90000]  off $2BF20 -> $C3BF20  bank $C3

Usage: gen-farindex-lut-asm.py <out.s> [N]
"""
import sys


def main(argv: list[str]) -> int:
    if len(argv) < 2 or argv[1] in ("-h", "--help"):
        print(__doc__)
        return 0 if len(argv) >= 2 and argv[1] in ("-h", "--help") else 2

    out = argv[1]
    n = int(argv[2]) if len(argv) > 2 else 98304
    vals = [(i + (i >> 16)) & 0xFFFF for i in range(n)]

    lines = [
        "; Generated by tools/gen-farindex-lut-asm.py — do not edit.",
        "; tbl[i] = (i + (i>>16)) & 0xFFFF, 98304 x uint16 (3 banks $C1..$C3) in HiROM far rodata.",
        "; Value contract is shared with examples/65816/farindex.c (-DHOST READ macro).",
        '.section .far_rodata,"a",@progbits',
        ".global tbl",
        ".balign 2",
        "tbl:",
    ]
    # Emit 16 little-endian halfwords per line for compactness.
    for i in range(0, n, 16):
        chunk = ", ".join("0x%04x" % v for v in vals[i:i + 16])
        lines.append("  .2byte " + chunk)
    lines.append("")
    open(out, "w").write("\n".join(lines))
    print(f"{out}: {n} entries ({n * 2} bytes) -> .far_rodata (banks $C1..$C3)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
