// Host-side "bake" tool for the interactive SNES Mandelbrot demo.
//
// Runs the SHARED fixed-point kernel (examples/65816/mandel.h — the exact code the SNES target
// compiles) once at 128x128, rearranges the raster image into Mode 7 CHARACTER ORDER host-side,
// and emits a generated C header (examples/snes/mandel_image.h) holding:
//   * MANDEL_CHR[128*128]   the 8bpp image already tiled into 256 8x8 Mode 7 characters
//                           (chr[tile*64 + r*8 + c]) — DMA'd straight ROM->VRAM at boot, so the
//                           machine shows the Mandelbrot INSTANTLY (no on-console fractal compute
//                           AND no on-console de-linearize loop — both are the slow parts).
//   * MANDEL_PAL[NCOL]      the BGR555 CGRAM palette (from the shared mandel_palette).
//   * SINCOS[256]           an 8.8 sine table (full circle = 256); cos(a)=SINCOS[(a+64)&255].
//                           Drives the per-frame Mode 7 rotate/zoom matrix (view.h).
//   * MANDEL_CHR_CRC        the host-reference CRC16 of MANDEL_CHR — the boot gate value the ROM
//                           asserts on both emulators (the displayed character data is verified).
//
// The image is precomputed because the on-console fractal compute is ~4 min of emulated time;
// the DEMO's interactivity is Mode 7 hardware pan/zoom/rotate over this baked image, 60 fps. The
// on-target +mos-a16 fractal math is already differentially proven by dev/run.sh k_mandel /
// mandel-far; the NEW +mos-a16 customer here is the per-frame matrix math (view.h), gated
// separately. Because the upload is now a plain ROM->VRAM DMA (no far pointer), the demo builds
// BOTH default-8bit and +mos-a16 — a host==default==+mos-a16 differential.
// See docs/plans/2026-06-25-321-interactive-mandelbrot-mode7.md.
//
// Build (host): cc -O2 -I examples/65816 tools/mandel-bake.c -o build/mandel-bake -lm
// Usage: mandel-bake <out.h> [W H N]    (defaults: 128 128 32)
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>

#include "mandel.h"   // shared kernel: mandel_fill, mandel_palette, mandel_crc (-I examples/65816)

int main(int argc, char **argv) {
  if (argc < 2) { fprintf(stderr, "usage: %s <out.h> [W H N]\n", argv[0]); return 2; }
  const char *out = argv[1];
  int W = (argc >= 5) ? atoi(argv[2]) : 128;
  int H = (argc >= 5) ? atoi(argv[3]) : 128;
  int N = (argc >= 5) ? atoi(argv[4]) : 32;
  // Mode 7 character data is linear 8bpp with a 256-tile cap => 128x128 max (16x16 tiles);
  // the escape count indexes CGRAM directly, so N (and thus NCOL=N+1) must fit a byte.
  if (W != 128 || H != 128) { fprintf(stderr, "this demo bakes 128x128 (Mode 7 256-tile cap)\n"); return 2; }
  if (N < 1 || N > 254) { fprintf(stderr, "N must be 1..254 (8bpp palette index)\n"); return 2; }
  int NCOL = N + 1;   // escape counts 0..N (N == interior == black)

  uint8_t *img = (uint8_t *)malloc((size_t)W * H);
  uint8_t *chr = (uint8_t *)malloc((size_t)W * H);
  if (!img || !chr) { fprintf(stderr, "oom\n"); return 1; }
  mandel_fill(img, (uint8_t)W, (uint8_t)H, (uint8_t)N);   // SHARED kernel — host == target

  // Rearrange the raster image into Mode 7 character order: 256 tiles of 8x8, linear within a
  // tile. chr[tile*64 + r*8 + c] = raster[(tile_row*8 + r)*W + (tile_col*8 + c)], tile = row*16+col.
  // This is the de-linearize the ON-CONSOLE build_vbuf used to do per word — now free, host-side.
  for (int tile = 0; tile < 256; tile++) {
    int trow = tile / 16, tcol = tile % 16;
    for (int r = 0; r < 8; r++)
      for (int c = 0; c < 8; c++)
        chr[tile * 64 + r * 8 + c] = img[(trow * 8 + r) * W + (tcol * 8 + c)];
  }

  // Fast rolling hash over the tiled character data (the boot gate value — the ROM recomputes it
  // over its ROM copy and asserts equality). W*H = 16384 fits a uint16 length.
  uint16_t crc = img_hash16(chr, (uint16_t)(W * H));

  FILE *f = fopen(out, "w");
  if (!f) { fprintf(stderr, "cannot write %s\n", out); return 1; }

  fprintf(f,
    "// AUTO-GENERATED by tools/mandel-bake.c — DO NOT EDIT.\n"
    "// Regenerated by dev/mandel-interactive.sh. %dx%d Mandelbrot (N=%d), tiled into Mode 7\n"
    "// character order and baked into ROM for the instant-boot interactive demo\n"
    "// (examples/snes/mandel-interactive.c).\n"
    "//\n"
    "// Host includers that only need the tables (SINCOS) can #define MANDEL_IMAGE_NO_IMG\n"
    "// before including this header to skip the 16 KiB character + palette arrays.\n"
    "#ifndef MANDEL_IMAGE_H\n"
    "#define MANDEL_IMAGE_H\n"
    "#include <stdint.h>\n\n"
    "#define MANDEL_IMG_W    %d\n"
    "#define MANDEL_IMG_H    %d\n"
    "#define MANDEL_N        %d\n"
    "#define MANDEL_NCOL     %d\n"
    "#define MANDEL_CHR_HASH 0x%04X\n\n",
    W, H, N, W, H, N, NCOL, crc);

  // SINCOS: 8.8 signed sine, full circle = 256 entries. cos(a) = SINCOS[(a+64)&255].
  // Amplitude 256 == 1.0 in 8.8. Emitted first so MANDEL_IMAGE_NO_IMG includers still get it.
  fprintf(f, "// 8.8 signed sine, 256 steps/circle; cos(a) = SINCOS[(a+64)&255].\n");
  fprintf(f, "static const int16_t SINCOS[256] = {\n  ");
  for (int a = 0; a < 256; a++) {
    int v = (int)lround(256.0 * sin(2.0 * M_PI * (double)a / 256.0));
    fprintf(f, "%d,%s", v, ((a & 15) == 15) ? "\n  " : " ");
  }
  fprintf(f, "\n};\n\n");

  fprintf(f, "#ifndef MANDEL_IMAGE_NO_IMG\n");

  // BGR555 palette: escape count -> colour (8bpp indexes CGRAM directly), 0..N.
  fprintf(f, "// BGR555 CGRAM palette; index = escape count (%d == interior == black).\n", N);
  fprintf(f, "static const uint16_t MANDEL_PAL[MANDEL_NCOL] = {\n  ");
  for (int n = 0; n < NCOL; n++) {
    uint8_t r5, g5, b5;
    mandel_palette((uint8_t)n, (uint8_t)N, &r5, &g5, &b5);
    uint16_t c = (uint16_t)(((b5 & 0x1F) << 10) | ((g5 & 0x1F) << 5) | (r5 & 0x1F));  // SNES_RGB
    fprintf(f, "0x%04X,%s", c, ((n & 7) == 7) ? "\n  " : " ");
  }
  fprintf(f, "\n};\n\n");

  // The tiled character data, ready to DMA straight into Mode 7 VRAM high bytes.
  fprintf(f, "// %dx%d image in Mode 7 character order (256 8x8 tiles). 16 KiB -> ROM .rodata.\n", W, H);
  fprintf(f, "static const uint8_t MANDEL_CHR[MANDEL_IMG_W * MANDEL_IMG_H] = {\n  ");
  for (int p = 0; p < W * H; p++)
    fprintf(f, "%u,%s", chr[p], ((p & 31) == 31) ? "\n  " : " ");
  fprintf(f, "\n};\n");

  fprintf(f, "#endif /* MANDEL_IMAGE_NO_IMG */\n");
  fprintf(f, "\n#endif /* MANDEL_IMAGE_H */\n");
  fclose(f);

  printf("baked %s  %dx%d N=%d NCOL=%d  CHR HASH16=0x%04X\n", out, W, H, N, NCOL, crc);
  free(img); free(chr);
  return 0;
}
