// tools/seamdemo-sim.c — host harness for the Act 1 bytecode VM.
//
// Runs examples/65816/seamdemo_vm.h — the SAME source the SNES ROM runs —
// against a built .sfc on the host, and prints the fold. Three implementations
// have to agree for the differential to mean anything:
//
//   this (host C)                    == tools/snes_seamdemo_oracle.py (Python)
//                                    == examples/snes/seamdemo.c @ bsnes-jg
//
// and this leg is the cheap one: it catches an ISA transcription slip in the
// shared header before any emulator run, which is exactly the failure the C and
// Python implementations exist to cross-check.
//
// Build + run:
//   cc -O2 -I examples/65816 -I <dir with generated seamdemo-data.h>
//      -o build/seamdemo-sim tools/seamdemo-sim.c
//   build/seamdemo-sim build/seamdemo.sfc
//
// Driven by dev/seamdemo.sh step 6b.
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// Generated by tools/snes-seamdemo-gen.py: VMOP_*/VMALU_*, seamdemo_xlat_*,
// seamdemo_dir16, SEAMDEMO_ACT1_*, SEAMDEMO_SEAM0_FILE.
#include "seamdemo-data.h"

static uint8_t *g_rom;
static unsigned long g_size;

// The host reads the FILE directly, but it must still route through the SAME
// file->CPU->file round trip the console performs, or it would not be testing
// the translation the ROM depends on. `far_of` reproduces the generated table;
// `host_mem8` then inverts it exactly the way the cartridge decoder does for the
// canonical windows, and fails loudly if the two disagree.
static unsigned long far_of(unsigned long file) {
  for (int i = 0; i < SEAMDEMO_XLAT_COUNT; i++)
    if (file >= seamdemo_xlat_lo[i] && file < seamdemo_xlat_hi[i])
      return (file + seamdemo_xlat_delta[i]) & 0xFFFFFFUL;
  fprintf(stderr, "seamdemo-sim: file $%06lX has no CPU window\n", file);
  exit(2);
}

// Inverse of far_of, derived from the same generated table rather than written
// down, so the two cannot drift. Subtract each range's delta and keep the
// candidate that lands back inside that range's FILE extent: the ranges are
// disjoint in file space and each map is a bijection, so at most one matches.
// (The subtraction has to be modulo 24 bits — region A's CPU window is
// $C00000-$FFFFFF, whose top wraps to zero.)
static unsigned long file_of(unsigned long far) {
  for (int i = 0; i < SEAMDEMO_XLAT_COUNT; i++) {
    unsigned long d = seamdemo_xlat_delta[i];
    unsigned long cand = (far - d) & 0xFFFFFFUL;
    if (cand >= seamdemo_xlat_lo[i] && cand < seamdemo_xlat_hi[i]
        && ((cand + d) & 0xFFFFFFUL) == far)
      return cand;
  }
  fprintf(stderr, "seamdemo-sim: CPU $%06lX is not cartridge ROM\n", far);
  exit(2);
}

static uint8_t host_mem8(unsigned long file) {
  unsigned long far = far_of(file);
  unsigned long back = file_of(far);
  if (back != file) {
    fprintf(stderr, "seamdemo-sim: file $%06lX -> CPU $%06lX -> file $%06lX\n",
            file, far, back);
    exit(2);
  }
  if (back >= g_size) {
    fprintf(stderr, "seamdemo-sim: file $%06lX past the image\n", back);
    exit(2);
  }
  return g_rom[back];
}

#define SEAMVM_MEM8(f) host_mem8(f)
#include "seamdemo_vm.h"

// --- act 2 needs the MIRROR-aware decode ---------------------------------
// Act 2's node addresses are deliberately a mix of canonical and mirror CPU
// addresses. The console gets that decode free from the cartridge; the host does
// not, and must not re-derive it here -- tools/snes_cartmap.py is the one model.
// So the generator emits its decode-cell table and this walks it.
#include "seamdemo-decode.h"

static uint8_t host_far8(unsigned long far) {
  unsigned bank = (unsigned)((far >> 16) & 0xFFUL);
  unsigned half = (unsigned)((far >> 15) & 1UL);
  for (int i = 0; i < SEAMDEMO_CELL_COUNT; i++) {
    if (seamdemo_cell_bank[i] == bank && seamdemo_cell_half[i] == half) {
      unsigned long off = seamdemo_cell_file[i] + (far & 0x7FFFUL);
      if (off >= g_size) {
        fprintf(stderr, "seamdemo-sim: CPU $%06lX -> file $%06lX past the image\n", far, off);
        exit(2);
      }
      return g_rom[off];
    }
  }
  fprintf(stderr, "seamdemo-sim: CPU $%06lX is not a decode cell\n", far);
  exit(2);
}

#define SEAMGRAPH_FAR8(a) host_far8(a)
#include "seamdemo_graph.h"

#define SEAMATLAS_FILE8(o) host_mem8(o)
#include "seamdemo_atlas.h"

int main(int argc, char **argv) {
  if (argc < 2) {
    fprintf(stderr, "Usage: %s <rom.sfc>\n", argv[0]);
    return 2;
  }
  FILE *f = fopen(argv[1], "rb");
  if (!f) {
    perror(argv[1]);
    return 2;
  }
  fseek(f, 0, SEEK_END);
  g_size = (unsigned long)ftell(f);
  fseek(f, 0, SEEK_SET);
  g_rom = malloc(g_size);
  if (!g_rom || fread(g_rom, 1, g_size, f) != g_size) {
    fprintf(stderr, "seamdemo-sim: short read\n");
    return 2;
  }
  fclose(f);
  if (g_size != SEAMDEMO_IMAGE_BYTES) {
    fprintf(stderr, "seamdemo-sim: image is %lu bytes, header says %lu\n",
            g_size, (unsigned long)SEAMDEMO_IMAGE_BYTES);
    return 2;
  }

  SeamVm v;
  v.status = 0;
  if (host_mem8(SEAMDEMO_SEAM0_FILE - 1UL) != VMOP_SYNC) v.status |= SEAMVM_ST_SEAM_SHAPE;
  seamvm_init(&v);

  unsigned long seams = 0, syncs = 0;
  while (!v.halted) {
    seamvm_step(&v, NULL);
    if (v.seam_hit) { v.seam_hit = 0; seams++; }
    if (v.yield) { syncs++; v.yield = 0; }
    if (v.ops > SEAMDEMO_ACT1_OP_BUDGET) {
      v.status |= SEAMVM_ST_BUDGET;
      break;
    }
  }
  uint16_t crc = seamvm_final_crc(&v);
  if (crc != SEAMDEMO_ACT1_CRC) v.status |= SEAMVM_ST_CRC;

  printf("act1 CRC $%04X (want $%04X)  ops=%lu segments=%u syncs=%lu seam-hits=%lu status=$%04X\n",
         crc, (unsigned)SEAMDEMO_ACT1_CRC, v.ops, (unsigned)v.nseg, syncs, seams,
         (unsigned)v.status);

  // --- act 2 ---------------------------------------------------------------
  SeamGraph g;
  g.status = 0;
  seamgraph_init(&g);
  while (!g.done) {
    seamgraph_step(&g, NULL);
    if (g.visited > SEAMDEMO_ACT2_NODES) break;  // cannot happen; cheap guard
  }
  uint16_t g2 = seamgraph_final_crc(&g);
  if (g2 != SEAMDEMO_ACT2_CRC) g.status |= SEAMGRAPH_ST_CRC;
  printf("act2 CRC $%04X (want $%04X)  nodes=%u edges=%u seam=%u mirror=%u status=$%04X\n",
         g2, (unsigned)SEAMDEMO_ACT2_CRC, (unsigned)g.visited, (unsigned)g.edges,
         (unsigned)g.seam_edges, (unsigned)g.mirror_edges, (unsigned)g.status);

  // --- act 3 ---------------------------------------------------------------
  SeamAtlas at;
  at.status = 0;
  seamatlas_init(&at);
  while (!at.done) seamatlas_step(&at, NULL);
  uint16_t a3 = seamatlas_final_crc(&at);
  if (a3 != SEAMDEMO_ACT3_CRC) at.status |= SEAMATLAS_ST_CRC;
  if (at.samples != SEAMDEMO_ACT3_SAMPLES) at.status |= SEAMATLAS_ST_PAGES;
  printf("act3 CRC $%04X (want $%04X)  samples=%u (want %lu) pages=%u status=$%04X\n",
         a3, (unsigned)SEAMDEMO_ACT3_CRC, (unsigned)at.samples,
         (unsigned long)SEAMDEMO_ACT3_SAMPLES, (unsigned)at.pages, (unsigned)at.status);

  unsigned corpus12 = 0;
  {
    uint16_t h = 0;
    uint16_t acts[2] = { crc, g2 };
    for (int i = 0; i < 2; i++) {
      h = seamvm_fold(h, (uint8_t)(acts[i] & 0xFFu));
      h = seamvm_fold(h, (uint8_t)(acts[i] >> 8));
    }
    corpus12 = h;
  }
  printf("corpus(act1,act2) $%04X (want $%04X)\n",
         corpus12, (unsigned)SEAMDEMO_CORPUS_ACT12);

  unsigned corpus123 = 0;
  {
    uint16_t h = 0;
    uint16_t acts[3] = { crc, g2, a3 };
    for (int i = 0; i < 3; i++) {
      h = seamvm_fold(h, (uint8_t)(acts[i] & 0xFFu));
      h = seamvm_fold(h, (uint8_t)(acts[i] >> 8));
    }
    corpus123 = h;
  }
  printf("corpus(act1,act2,act3) $%04X (want $%04X)\n",
         corpus123, (unsigned)SEAMDEMO_CORPUS_RESULT);

  if (v.status || g.status || at.status || corpus12 != SEAMDEMO_CORPUS_ACT12
      || corpus123 != SEAMDEMO_CORPUS_RESULT) {
    printf("FAIL: act1 status $%04X, act2 status $%04X, act3 status $%04X\n",
           (unsigned)v.status, (unsigned)g.status, (unsigned)at.status);
    return 1;
  }
  printf("PASS: host C == the generated oracle (all three acts)\n");
  return 0;
}
