// tools/seamdemo-sim.c — host harness for the Act 1 bytecode VM.
//
// Runs examples/65816/seamdemo_vm.h — the SAME source the SNES ROM runs —
// against a built .sfc on the host, and prints the fold. Three implementations
// have to agree for the differential to mean anything:
//
//   this (host C)                    == tools/snes_seamdemo_oracle.py (Python)
//                                    == examples/snes/seamdemo.c @ bsnes-jg
//
// and this leg is the cheap one: it catches an ISA transcription slip in the
// shared header before any emulator run, which is exactly the failure the C and
// Python implementations exist to cross-check.
//
// Build + run:
//   cc -O2 -I examples/65816 -I <dir with generated seamdemo-data.h>
//      -o build/seamdemo-sim tools/seamdemo-sim.c
//   build/seamdemo-sim build/seamdemo.sfc
//
// Driven by dev/seamdemo.sh step 6b.
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// Generated by tools/snes-seamdemo-gen.py: VMOP_*/VMALU_*, seamdemo_xlat_*,
// seamdemo_dir16, SEAMDEMO_ACT1_*, SEAMDEMO_SEAM0_FILE.
#include "seamdemo-data.h"

static uint8_t *g_rom;
static unsigned long g_size;

// The host reads the FILE directly, but it must still route through the SAME
// file->CPU->file round trip the console performs, or it would not be testing
// the translation the ROM depends on. `far_of` reproduces the generated table;
// `host_mem8` then inverts it exactly the way the cartridge decoder does for the
// canonical windows, and fails loudly if the two disagree.
static unsigned long far_of(unsigned long file) {
  for (int i = 0; i < SEAMDEMO_XLAT_COUNT; i++)
    if (file >= seamdemo_xlat_lo[i] && file < seamdemo_xlat_hi[i])
      return (file + seamdemo_xlat_delta[i]) & 0xFFFFFFUL;
  fprintf(stderr, "seamdemo-sim: file $%06lX has no CPU window\n", file);
  exit(2);
}

// Inverse of far_of, derived from the same generated table rather than written
// down, so the two cannot drift. Subtract each range's delta and keep the
// candidate that lands back inside that range's FILE extent: the ranges are
// disjoint in file space and each map is a bijection, so at most one matches.
// (The subtraction has to be modulo 24 bits — region A's CPU window is
// $C00000-$FFFFFF, whose top wraps to zero.)
static unsigned long file_of(unsigned long far) {
  for (int i = 0; i < SEAMDEMO_XLAT_COUNT; i++) {
    unsigned long d = seamdemo_xlat_delta[i];
    unsigned long cand = (far - d) & 0xFFFFFFUL;
    if (cand >= seamdemo_xlat_lo[i] && cand < seamdemo_xlat_hi[i]
        && ((cand + d) & 0xFFFFFFUL) == far)
      return cand;
  }
  fprintf(stderr, "seamdemo-sim: CPU $%06lX is not cartridge ROM\n", far);
  exit(2);
}

static uint8_t host_mem8(unsigned long file) {
  unsigned long far = far_of(file);
  unsigned long back = file_of(far);
  if (back != file) {
    fprintf(stderr, "seamdemo-sim: file $%06lX -> CPU $%06lX -> file $%06lX\n",
            file, far, back);
    exit(2);
  }
  if (back >= g_size) {
    fprintf(stderr, "seamdemo-sim: file $%06lX past the image\n", back);
    exit(2);
  }
  return g_rom[back];
}

#define SEAMVM_MEM8(f) host_mem8(f)
#include "seamdemo_vm.h"

int main(int argc, char **argv) {
  if (argc < 2) {
    fprintf(stderr, "Usage: %s <rom.sfc>\n", argv[0]);
    return 2;
  }
  FILE *f = fopen(argv[1], "rb");
  if (!f) {
    perror(argv[1]);
    return 2;
  }
  fseek(f, 0, SEEK_END);
  g_size = (unsigned long)ftell(f);
  fseek(f, 0, SEEK_SET);
  g_rom = malloc(g_size);
  if (!g_rom || fread(g_rom, 1, g_size, f) != g_size) {
    fprintf(stderr, "seamdemo-sim: short read\n");
    return 2;
  }
  fclose(f);
  if (g_size != SEAMDEMO_IMAGE_BYTES) {
    fprintf(stderr, "seamdemo-sim: image is %lu bytes, header says %lu\n",
            g_size, (unsigned long)SEAMDEMO_IMAGE_BYTES);
    return 2;
  }

  SeamVm v;
  v.status = 0;
  if (host_mem8(SEAMDEMO_SEAM0_FILE - 1UL) != VMOP_SYNC) v.status |= SEAMVM_ST_SEAM_SHAPE;
  seamvm_init(&v);

  unsigned long seams = 0, syncs = 0;
  while (!v.halted) {
    seamvm_step(&v, NULL);
    if (v.seam_hit) { v.seam_hit = 0; seams++; }
    if (v.yield) { syncs++; v.yield = 0; }
    if (v.ops > SEAMDEMO_ACT1_OP_BUDGET) {
      v.status |= SEAMVM_ST_BUDGET;
      break;
    }
  }
  uint16_t crc = seamvm_final_crc(&v);
  if (crc != SEAMDEMO_ACT1_CRC) v.status |= SEAMVM_ST_CRC;

  printf("act1 CRC $%04X (want $%04X)  ops=%lu segments=%u syncs=%lu seam-hits=%lu status=$%04X\n",
         crc, (unsigned)SEAMDEMO_ACT1_CRC, v.ops, (unsigned)v.nseg, syncs, seams,
         (unsigned)v.status);
  if (v.status) {
    printf("FAIL: status $%04X\n", (unsigned)v.status);
    return 1;
  }
  printf("PASS: host C == the generated oracle\n");
  return 0;
}
