#!/usr/bin/env python3
"""Emit a small, deterministic SVX2 reel as a C header."""

from __future__ import annotations

import argparse
from pathlib import Path

from snes_video_codec import FRAME_SIZE, decode_xor_frame, encode_xor_frame


def byte_rows(data: bytes) -> str:
    return ",\n    ".join(
        ", ".join(f"0x{value:02x}" for value in data[offset:offset + 16])
        for offset in range(0, len(data), 16)
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("tiles", type=Path, help="concatenated 4480-byte tile-major frames")
    parser.add_argument("palette", type=Path, help="448-byte BGR555 palette")
    parser.add_argument("output", type=Path, help="generated C header")
    parser.add_argument("--frames", type=int, default=4)
    parser.add_argument("--packed-far", action="store_true",
                        help="emit one contiguous HiROM far-data stream and offsets")
    parser.add_argument("--stream-output", type=Path,
                        help="write packed bytes separately instead of a C initializer")
    args = parser.parse_args()

    data = args.tiles.read_bytes()
    palette = args.palette.read_bytes()
    if not data or len(data) % FRAME_SIZE:
        parser.error("tile corpus must contain whole 4480-byte frames")
    if len(palette) != 448:
        parser.error(f"palette must be exactly 448 bytes, got {len(palette)}")
    if palette[:4] != bytes((0x00, 0x00, 0xff, 0x7f)):
        parser.error("palette entries 0/1 must remain dashboard black/white")
    available = len(data) // FRAME_SIZE
    if args.frames < 2 or args.frames > available:
        parser.error(f"--frames must be between 2 and {available}")

    frames = [data[i * FRAME_SIZE:(i + 1) * FRAME_SIZE] for i in range(args.frames)]
    packets: list[bytes] = []
    previous = None
    for index, frame in enumerate(frames):
        packet = encode_xor_frame(frame, previous, keyframe=index == 0)
        if decode_xor_frame(packet, previous) != frame:
            raise RuntimeError(f"frame {index}: SVX2 host round trip failed")
        packets.append(packet)
        previous = frame

    maximum = max(map(len, packets))
    lines = [
        "// GENERATED by tools/snes-video-reel-assets.py; do not edit.",
        "#ifndef SNES_VIDEO_REEL_ASSETS_H",
        "#define SNES_VIDEO_REEL_ASSETS_H",
        "#include <stdint.h>",
        f"#define VIDEO_REEL_FRAME_COUNT {len(frames)}u",
        f"#define VIDEO_REEL_PACKET_CAPACITY {maximum}u",
        f"#define VIDEO_REEL_TOTAL_PACKET_BYTES {sum(map(len, packets))}u",
        "static const uint8_t reel_palette[448] = {",
        f"    {byte_rows(palette)}",
        "};",
    ]
    if args.packed_far:
        stream = b"".join(packets)
        if args.stream_output:
            args.stream_output.write_bytes(stream)
        offsets = [0]
        for packet in packets:
            offsets.append(offsets[-1] + len(packet))
        if not args.stream_output:
            lines.extend((
                "static const uint8_t reel_packet_stream[]",
                "    __attribute__((section(\".far_rodata\"))) = {",
                f"    {byte_rows(stream)}",
                "};",
            ))
        lines.extend((
            "#define VIDEO_REEL_PACKED_FAR 1",
            "#define VIDEO_REEL_HIROM_BASE_BANK 0xc1u",
            f"static const uint32_t reel_packet_offsets[{len(offsets)}] = {{",
            "  " + ", ".join(f"{offset}ul" for offset in offsets),
            "};",
        ))
    else:
        lines.append(f"static const uint8_t reel_packets[{len(frames)}][{maximum}] = {{")
        for packet in packets:
            lines.extend(("  {", f"    {byte_rows(packet)}", "  },"))
        lines.extend((
            "};",
            f"static const uint16_t reel_packet_sizes[{len(frames)}] = {{",
            "  " + ", ".join(f"{len(packet)}u" for packet in packets),
            "};",
        ))
    lines.extend((
        f"static const uint16_t reel_frame_crcs[{len(frames)}] = {{",
        "  " + ", ".join(f"0x{packet[7] | (packet[8] << 8):04x}u" for packet in packets),
        "};",
        "#endif",
        "",
    ))
    args.output.write_text("\n".join(lines))
    print(f"frames={len(frames)} packets={sum(map(len, packets))} max={maximum}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
