#!/usr/bin/env python3
"""Generate a visual LoROM cartridge map from an lld map and gallery report."""
import argparse
import json
import re
from pathlib import Path

p = argparse.ArgumentParser()
p.add_argument("map")
p.add_argument("report")
p.add_argument("output")
a = p.parse_args()

sections = {}
for line in Path(a.map).read_text().splitlines():
    m = re.match(r"^\s*([0-9a-f]+)\s+[0-9a-f]+\s+([0-9a-f]+)\s+1\s+(\.\S+)$", line)
    if m:
        sections[m.group(3)] = (int(m.group(1), 16), int(m.group(2), 16))

works = json.loads(Path(a.report).read_text())
bank_count = max(max(work["stream_bank"], work["palette_bank"]) for work in works)
if bank_count > 31:
    raise SystemExit("too many gallery banks for 1 MiB LoROM")

rows = []
nodes = ['  B00["$00<br/>CODE / RODATA / HEADER"]']
for bank in range(1, bank_count + 1):
    stream_items = [work for work in works if work["stream_bank"] == bank]
    palette_items = [work for work in works if work["palette_bank"] == bank]
    sec = f".gallery_{bank:02X}"
    if sec not in sections:
        raise SystemExit(f"missing linked section {sec}")
    addr, linked = sections[sec]
    if addr >> 16 != bank or linked > 32768:
        raise SystemExit(f"{sec}: invalid bank/size {addr:06X}/{linked}")
    stream = sum(work["compressed_bytes"] for work in stream_items)
    expected = stream + 512 * len(palette_items)
    if linked != expected:
        raise SystemExit(f"{sec}: linked {linked}, expected stream+palette {expected}")
    free = 32768 - linked
    labels = [work["slug"].replace("-", " ").upper()+" LZ" for work in stream_items]
    labels += [work["slug"].replace("-", " ").upper()+" PAL" for work in palette_items]
    label = " + ".join(labels)
    nodes.append(f'  B{bank:02X}["${bank:02X}<br/>{label}<br/>{linked:,} B"]')
    detail = [f"{work['title']} stream — {work['compressed_bytes']:,}" for work in stream_items]
    detail += [f"{work['title']} palette — 512" for work in palette_items]
    contents = "<br/>".join(detail)
    rows.append(f"| `${bank:02X}` | {contents} | {stream:,} | {512*len(palette_items):,} | {linked:,} | {free:,} |")

last = bank_count
pad = 31 - last
nodes.append(f'  PAD["${last+1:02X}-$1F<br/>{pad} EMPTY PADDING BANKS<br/>{pad*32768:,} B"]')
links = " --> ".join(["B00"] + [f"B{i:02X}" for i in range(1, last + 1)] + ["PAD"])
out = [
    "<!-- GENERATED by tools/snes-rom-map.py; do not edit. -->",
    "```mermaid", "flowchart LR", *nodes, f"  {links}", "```", "",
    "| Bank | Contents | Stream | Palette | Used | Free |",
    "|---:|---|---:|---:|---:|---:|", *rows,
    f"| `${last+1:02X}-$1F` | Explicit power-of-two padding | 0 | 0 | 0 each | 32,768 each |", "",
]
Path(a.output).write_text("\n".join(out))
