#!/usr/bin/env python3
"""Select median/worst real-video packets and emit a deterministic C benchmark header."""

from __future__ import annotations

import argparse
from pathlib import Path

from snes_video_codec import (FRAME_SIZE, encode_frame, encode_xor_frame, lzss_encode)


def c_array(name: str, data: bytes) -> str:
    rows = [", ".join(f"0x{value:02x}" for value in data[i:i + 16])
            for i in range(0, len(data), 16)]
    body = ",\n  ".join(rows)
    return f"static const uint8_t {name}[{len(data)}] = {{\n  {body}\n}};\n"


def select(encoded: list[tuple[int, bytes, bytes | None, bytes]]) -> dict[str, tuple[int, bytes, bytes | None, bytes]]:
    ordered = sorted(encoded, key=lambda item: (len(item[1]), item[0]))
    return {"MEDIAN": ordered[len(ordered) // 2], "WORST": ordered[-1]}


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("tiles", type=Path, help="concatenated 4480-byte tile-major frames")
    parser.add_argument("output", type=Path)
    parser.add_argument("--palette", type=Path,
                        help="optional 448-byte SNES palette for a visible benchmark ROM")
    parser.add_argument("--keyframe-interval", type=int, default=60)
    args = parser.parse_args()
    data = args.tiles.read_bytes()
    if not data or len(data) % FRAME_SIZE:
        parser.error("tile corpus size is not a positive multiple of 4480")
    frames = [data[i:i + FRAME_SIZE] for i in range(0, len(data), FRAME_SIZE)]
    packets: dict[str, list[tuple[int, bytes, bytes | None, bytes]]] = {
        "SVX": [], "SVC": [], "LZSS": []}
    for index, frame in enumerate(frames):
        previous = frames[index - 1] if index else None
        keyframe = index % args.keyframe_interval == 0
        packets["SVX"].append((index, encode_xor_frame(frame, previous, keyframe=keyframe),
                               None if keyframe else previous, frame))
        packet, _ = encode_frame(frame, previous, keyframe=keyframe)
        packets["SVC"].append((index, packet, None if keyframe else previous, frame))
        packets["LZSS"].append((index, lzss_encode(frame), None, frame))

    lines = ["// GENERATED by tools/snes-video-bench-assets.py; do not edit.",
             "#ifndef SNES_VIDEO_BENCH_ASSETS_H", "#define SNES_VIDEO_BENCH_ASSETS_H", ""]
    if args.palette:
        palette = args.palette.read_bytes()
        if len(palette) != 448:
            parser.error(f"palette must be exactly 448 bytes, got {len(palette)}")
        lines.append(c_array("bench_palette", palette))
        lines.append("#define VIDEO_BENCH_HAS_PALETTE 1\n")
    case = 0
    for codec in ("SVX", "SVC", "LZSS"):
        for rank, (frame_index, packet, previous, expected) in select(packets[codec]).items():
            macro = f"BENCH_{codec}_{rank}"
            lines.extend((f"#if VIDEO_BENCH_CASE == {case}", f"#define VIDEO_BENCH_NAME \"{codec.lower()}-{rank.lower()}\"",
                          f"#define VIDEO_BENCH_CODEC_{codec} 1", f"#define VIDEO_BENCH_FRAME {frame_index}u",
                          f"#define VIDEO_BENCH_PACKET_SIZE {len(packet)}u"))
            lines.append(c_array("bench_packet", packet))
            if previous is not None:
                lines.append(c_array("bench_previous", previous))
                lines.append("#define VIDEO_BENCH_PREVIOUS bench_previous")
            else:
                lines.append("#define VIDEO_BENCH_PREVIOUS ((const uint8_t *)0)")
            lines.append(c_array("bench_expected", expected))
            lines.append(f"#define {macro} 1\n#endif\n")
            case += 1
    raw = frames[len(frames) // 2]
    lines.extend((f"#if VIDEO_BENCH_CASE == {case}", '#define VIDEO_BENCH_NAME "raw-copy"',
                  "#define VIDEO_BENCH_CODEC_RAW 1", f"#define VIDEO_BENCH_FRAME {len(frames) // 2}u",
                  f"#define VIDEO_BENCH_PACKET_SIZE {len(raw)}u", c_array("bench_packet", raw),
                  "#define VIDEO_BENCH_PREVIOUS ((const uint8_t *)0)", c_array("bench_expected", raw),
                  "#endif", ""))
    lines.extend(("#if VIDEO_BENCH_CASE < 0 || VIDEO_BENCH_CASE > 6", '#error "VIDEO_BENCH_CASE must be 0..6"',
                  "#endif", "#endif"))
    args.output.write_text("\n".join(lines) + "\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
