// examples/65816/cordic16_tables.h — GENERATED by tools/gen-cordic-tables.py. DO NOT EDIT.
// Q2.14 CORDIC constants for the Phase 2 trig compiler-test. Regenerate with:
//     python3 tools/gen-cordic-tables.py
// Plan: docs/plans/2026-06-26-trig-phase2-q214-cordic.md.
#ifndef CORDIC16_TABLES_H
#define CORDIC16_TABLES_H
#include <stdint.h>

// Q2.14 fixed point: value = raw / CORDIC16_ONE, representable range [-2, +2).
#define CORDIC16_FRAC     14
#define CORDIC16_ONE      16384        // 1.0 in Q2.14
#define CORDIC16_N        15          // CORDIC iterations (shift i = 0 .. N-1)
#define CORDIC16_HALFPI   25736        // pi/2 in Q2.14 (rotation input bound)

// Per-iteration rotation angle atan(2^-i), Q2.14. CORDIC convergence radius =
// sum(atan 2^-i) = 1.743226 rad (> pi/2 = 1.570796), so any angle in
// [-pi/2, pi/2] converges. Inverse gain 1/An with An = 1.6467602571.
static const int16_t cordic16_atan_tbl[CORDIC16_N] = {
   12868,   // atan(2^-0 ) = 0.7853981634 rad
    7596,   // atan(2^-1 ) = 0.4636476090 rad
    4014,   // atan(2^-2 ) = 0.2449786631 rad
    2037,   // atan(2^-3 ) = 0.1243549945 rad
    1023,   // atan(2^-4 ) = 0.0624188100 rad
     512,   // atan(2^-5 ) = 0.0312398334 rad
     256,   // atan(2^-6 ) = 0.0156237286 rad
     128,   // atan(2^-7 ) = 0.0078123411 rad
      64,   // atan(2^-8 ) = 0.0039062301 rad
      32,   // atan(2^-9 ) = 0.0019531225 rad
      16,   // atan(2^-10) = 0.0009765622 rad
       8,   // atan(2^-11) = 0.0004882812 rad
       4,   // atan(2^-12) = 0.0002441406 rad
       2,   // atan(2^-13) = 0.0001220703 rad
       1,   // atan(2^-14) = 0.0000610352 rad
};

// Rotation-mode seed x0 = 1/An (gain compensation): after N rotations of (x0, 0) by `angle`,
// (x, y) = (cos angle, sin angle) with unit magnitude in Q2.14.
#define CORDIC16_K        9949        // round(ONE / An)

#endif // CORDIC16_TABLES_H
