// AUTO-GENERATED by tools/gen-epicycles-tables.py — do not edit by hand.
// Fourier (DFT) coefficients of a 5-pointed-star outline for the #10 epicycles demo.
// 8 harmonics; coefficients = round(c_k * 2^6) in pixels; star outer radius 46px.
#ifndef EPICYCLES_TABLES_H
#define EPICYCLES_TABLES_H
#include <stdint.h>
#define EPI_NHARM   8u    // number of rotating vectors (epicycles)
#define EPI_CBITS   6 // coefficient fractional bits (tip shift = 8 + EPI_CBITS)
#define EPI_SHIFT   14
// Per harmonic: signed integer frequency (cycles per period), and the Q-coefficient (re,im).
static const int8_t  EPI_FREQ[EPI_NHARM] = { 1, -4, 6, -14, 16, -9, 11, -19 };
static const int16_t EPI_RE[EPI_NHARM]   = { -772, -200, -89, -16, -12, -10, -6, -2 };
static const int16_t EPI_IM[EPI_NHARM]   = { 1825, 473, 210, 39, 30, 23, 15, 5 };
#endif /* EPICYCLES_TABLES_H */
