// Shared, PURE Hopalong-attractor math — the single source of truth for both the headless
// kernel (examples/65816/k_hopalong.c, the 0x1BBC orbit-fold gate) and the on-screen Blossom
// renderer (examples/snes/blossom.c). Like examples/65816/mandel.h and examples/snes/view.h,
// this is the code under test for the +mos-a16 differential: the SAME body runs on the host
// oracle (int = 32) and the 65816 target (int = 16), so host == target bit-for-bit by
// construction. Keep every width cast load-bearing.
//
//   x' = y - sign(x) * sqrt(|b*x - c|)        y' = a - x        (iterate from (0,0))
//
// The renderer plots each visited orbit point by INCREMENTING a per-pixel hit counter in a
// "shadow" grid; over many points the characteristic Hopalong cloud accumulates. The grid is a
// far (high-WRAM) buffer on target and a near array on the host — HOP_DEFINE_{CLEAR,PLOT,HASH}
// stamp the identical loop body over a pointer qualifier (the examples/snes/mode7.h
// M7_DEFINE_BUILD_VBUF idiom), so the host needs no address_space(2) and the two agree exactly.
//
// NO hardware here (no snes.h, no MMIO) — host-linkable. See
// docs/plans/2026-06-24-3-snes-blossom-on-screen-interactive-hopalong-attr.md.
#ifndef HOPALONG_H
#define HOPALONG_H

#include <stdint.h>

// Classic Hopalong parameters (Blossom's default), Q8.8. A demo declares VOLATILE globals
// initialised to these so the optimiser can't fold the orbit to a literal (cf. k_fxmul.c).
#define HOP_A_CLASSIC 0x072C   /* a = 7.17 */
#define HOP_B_CLASSIC 0x0871   /* b = 8.44 */
#define HOP_C_CLASSIC 0x028F   /* c = 2.56 */

// Force the per-iteration math into a separate function on the pressure-prone +mos-a16 far path
// (handoff §4: a function holding the orbit intermediates AND a 32-bit far pointer live at once can
// overflow the imaginary-register file). A demo that wants that splits defines HOP_NOINLINE before
// including; the headless kernel leaves it empty to keep its original inlined shape.
#ifndef HOP_NOINLINE
#define HOP_NOINLINE
#endif

// The grid clear/plot/hash loops each hold a far (32-bit) pointer plus loop/accumulator state live;
// at -Os the compiler otherwise inlines all three into one giant main(), and the combined +mos-a16
// pressure derails at runtime (a clean -verify-machineinstrs build that nonetheless crashes — the
// handoff §4 far-pointer pressure trap). Keep each a separate noinline callee so the far-pointer
// live range is bounded per function. (On the host this is a harmless attribute.)
#ifndef HOP_FN
#define HOP_FN __attribute__((noinline)) static
#endif

// Q8.8 sqrt LUT, 256 entries — generated by tools/gen-sqrt-lut.py.
// SQRT_LUT[i] = round(sqrt(i) * 256); index with `|b*x - c| >> 8` (integer part).
static const unsigned short HOP_SQRT_LUT[256] = {
  0x0000, 0x0100, 0x016A, 0x01BB, 0x0200, 0x023C, 0x0273, 0x02A5,
  0x02D4, 0x0300, 0x032A, 0x0351, 0x0377, 0x039B, 0x03BE, 0x03DF,
  0x0400, 0x0420, 0x043E, 0x045C, 0x0479, 0x0495, 0x04B1, 0x04CC,
  0x04E6, 0x0500, 0x0519, 0x0532, 0x054B, 0x0563, 0x057A, 0x0591,
  0x05A8, 0x05BF, 0x05D5, 0x05EB, 0x0600, 0x0615, 0x062A, 0x063F,
  0x0653, 0x0667, 0x067B, 0x068F, 0x06A2, 0x06B5, 0x06C8, 0x06DB,
  0x06EE, 0x0700, 0x0712, 0x0724, 0x0736, 0x0748, 0x0759, 0x076B,
  0x077C, 0x078D, 0x079E, 0x07AE, 0x07BF, 0x07CF, 0x07E0, 0x07F0,
  0x0800, 0x0810, 0x0820, 0x082F, 0x083F, 0x084E, 0x085E, 0x086D,
  0x087C, 0x088B, 0x089A, 0x08A9, 0x08B8, 0x08C6, 0x08D5, 0x08E3,
  0x08F2, 0x0900, 0x090E, 0x091C, 0x092A, 0x0938, 0x0946, 0x0954,
  0x0961, 0x096F, 0x097D, 0x098A, 0x0997, 0x09A5, 0x09B2, 0x09BF,
  0x09CC, 0x09D9, 0x09E6, 0x09F3, 0x0A00, 0x0A0D, 0x0A19, 0x0A26,
  0x0A33, 0x0A3F, 0x0A4C, 0x0A58, 0x0A64, 0x0A71, 0x0A7D, 0x0A89,
  0x0A95, 0x0AA1, 0x0AAD, 0x0AB9, 0x0AC5, 0x0AD1, 0x0ADD, 0x0AE9,
  0x0AF4, 0x0B00, 0x0B0C, 0x0B17, 0x0B23, 0x0B2E, 0x0B3A, 0x0B45,
  0x0B50, 0x0B5C, 0x0B67, 0x0B72, 0x0B7D, 0x0B88, 0x0B93, 0x0B9E,
  0x0BA9, 0x0BB4, 0x0BBF, 0x0BCA, 0x0BD5, 0x0BE0, 0x0BEB, 0x0BF5,
  0x0C00, 0x0C0B, 0x0C15, 0x0C20, 0x0C2A, 0x0C35, 0x0C3F, 0x0C4A,
  0x0C54, 0x0C5F, 0x0C69, 0x0C73, 0x0C7D, 0x0C88, 0x0C92, 0x0C9C,
  0x0CA6, 0x0CB0, 0x0CBA, 0x0CC4, 0x0CCE, 0x0CD8, 0x0CE2, 0x0CEC,
  0x0CF6, 0x0D00, 0x0D0A, 0x0D14, 0x0D1D, 0x0D27, 0x0D31, 0x0D3B,
  0x0D44, 0x0D4E, 0x0D57, 0x0D61, 0x0D6B, 0x0D74, 0x0D7E, 0x0D87,
  0x0D91, 0x0D9A, 0x0DA3, 0x0DAD, 0x0DB6, 0x0DBF, 0x0DC9, 0x0DD2,
  0x0DDB, 0x0DE4, 0x0DEE, 0x0DF7, 0x0E00, 0x0E09, 0x0E12, 0x0E1B,
  0x0E24, 0x0E2D, 0x0E36, 0x0E3F, 0x0E48, 0x0E51, 0x0E5A, 0x0E63,
  0x0E6C, 0x0E75, 0x0E7E, 0x0E87, 0x0E8F, 0x0E98, 0x0EA1, 0x0EAA,
  0x0EB2, 0x0EBB, 0x0EC4, 0x0ECC, 0x0ED5, 0x0EDE, 0x0EE6, 0x0EEF,
  0x0EF7, 0x0F00, 0x0F09, 0x0F11, 0x0F1A, 0x0F22, 0x0F2A, 0x0F33,
  0x0F3B, 0x0F44, 0x0F4C, 0x0F54, 0x0F5D, 0x0F65, 0x0F6D, 0x0F76,
  0x0F7E, 0x0F86, 0x0F8E, 0x0F97, 0x0F9F, 0x0FA7, 0x0FAF, 0x0FB7,
  0x0FBF, 0x0FC8, 0x0FD0, 0x0FD8, 0x0FE0, 0x0FE8, 0x0FF0, 0x0FF8,
};

// Orbit point (Q8.8). For the bounded classic params the orbit stays at maxabs ~5857 (~22.9 world
// units), well inside int16, so every `short` op is value-preserving and host == target.
typedef struct { short x, y; } hop_pt;

// Host-only orbit diagnostics (range + LUT-saturation), mirroring k_hopalong.c's g_maxabs/g_clamps.
// Defined here so the SHARED hop_step carries them under HOST without changing the computed x,y
// (the clamp branch never fires for bounded params). The target never sees these.
#ifdef HOST
extern long g_hop_maxabs;
extern int  g_hop_clamps;
#endif

// One Hopalong iteration with Q8.8 params a,b,c. Updates *p. Pure; value-preserving host==target.
HOP_NOINLINE static void hop_step(hop_pt *p, short a, short b, short c) {
  short x = p->x, y = p->y;
  int32_t bx   = ((int32_t)b * (int32_t)x) >> 8;     // b*x, Q8.8 (32-bit intermediate)
  int32_t arg  = bx - (int32_t)c;                    // b*x - c
  int32_t aarg = arg < 0 ? -arg : arg;               // |b*x - c|
  unsigned short idx = (unsigned short)(aarg >> 8);  // integer part -> LUT index
  if (idx > 255) {
    idx = 255;                                       // defensive: bounded orbit never hits this
#ifdef HOST
    g_hop_clamps++;
#endif
  }
  short s = (short)HOP_SQRT_LUT[idx];                 // sqrt(|b*x - c|), Q8.8 (>= 0)
  // sign(x)*sqrt is a conditional negate (branch), NOT a general multiply — saves a __mulhi3/iter.
  short term = x > 0 ? s : (x < 0 ? (short)-s : (short)0);
  p->x = (short)(y - term);                          // x' = y - sign(x)*sqrt(|b*x - c|)
  p->y = (short)(a - x);                             // y' = a - x
#ifdef HOST
  {
    long ax = p->x < 0 ? -(long)p->x : (long)p->x;
    long ay = p->y < 0 ? -(long)p->y : (long)p->y;
    if (ax > g_hop_maxabs) g_hop_maxabs = ax;
    if (ay > g_hop_maxabs) g_hop_maxabs = ay;
  }
#endif
}

// --- Coordinate map: Q8.8 orbit value -> grid pixel. Constant-coefficient so it folds identically
// on host (int=32) and target (int=16). HOP_GRID is the square grid edge (128 = "Rung A" de-risk in
// $7E2000; 256 = "Rung B" target 64 KB in $7F). HOP_GAIN scales maxabs (~5857) to ~0.93*(GRID/2) px
// from the centre, leaving a margin; chosen per grid (256-grid gain is 2x the 128-grid's). ---
#ifndef HOP_GRID
#define HOP_GRID 128
#endif
#define HOP_CENTER (HOP_GRID / 2)
#if   HOP_GRID == 256
#define HOP_GAIN 1342
#elif HOP_GRID == 128
#define HOP_GAIN 671
#else
#error "hopalong.h: define HOP_GAIN for this HOP_GRID"
#endif
#define HOP_GSHIFT 16
// Total cells, as a uint16_t. The (uint32_t) multiply avoids 16-bit-int overflow at compile time;
// for HOP_GRID==256 the product 65536 wraps to 0 — and the do/while loops below run until ++i wraps
// back to 0, covering the full 0..65535 (for 128 it is a plain 16384-iteration loop).
#define HOP_NCELLS ((uint16_t)((uint32_t)HOP_GRID * (uint32_t)HOP_GRID))

static inline int16_t hop_map(short v) {
  return (int16_t)((int16_t)(((int32_t)v * HOP_GAIN) >> HOP_GSHIFT) + HOP_CENTER);
}

// Stamp `NAME(QUAL uint8_t *grid)` — zero the whole grid. The far grid in WRAM is NOT linker-zeroed
// (it's a runtime far pointer, not .bss), and bsnes randomises WRAM, so the target MUST clear it
// before accumulating. (On host the static array is already 0; calling this is harmless and keeps
// host/target structurally identical.)
//
// VOLATILE store (the `g` alias) is load-bearing on the far path: a non-volatile constant fill of a
// far (address_space(2)) buffer is coalesced by the optimizer into the NEAR `__memset` libcall, which
// ignores the 24-bit bank byte and writes bank $00 ($002000 = MMIO/open-bus) instead of $7E2000 — a
// silent far-pointer miscompile (repro: examples/65816/far_memset.c; diagnosis +
// workaround: docs/320-far-memset-miscompile.md). A volatile store is never coalesced, so each stays a
// real indirect-long `sta [dp]`. The per-element plot RMW and the hash read don't coalesce, so only
// the clear needs this.
#define HOP_DEFINE_CLEAR(NAME, QUAL)                                       \
  HOP_FN void NAME(QUAL uint8_t *grid) {                                   \
    volatile QUAL uint8_t *g = grid;                                       \
    uint16_t i = 0;                                                        \
    do { g[i] = 0; } while (++i != HOP_NCELLS);                            \
  }

// Stamp `NAME(QUAL uint8_t *grid, short a, short b, short c, uint16_t n)` — iterate the orbit n
// points from (0,0), map each to a grid pixel, DROP out-of-range points (a smear-free border; a pure
// unsigned compare, identical both sides), and SATURATINGLY increment the hit counter (far RMW on
// target: lda [dp] / compare / inc / sta [dp]).
#define HOP_DEFINE_PLOT(NAME, QUAL)                                        \
  HOP_FN void NAME(QUAL uint8_t *grid, short a, short b, short c, uint16_t n) { \
    hop_pt p = { 0, 0 };                                                   \
    for (uint16_t i = 0; i < n; i++) {                                     \
      hop_step(&p, a, b, c);                                               \
      int16_t px = hop_map(p.x), py = hop_map(p.y);                        \
      if ((uint16_t)px < (uint16_t)HOP_GRID &&                            \
          (uint16_t)py < (uint16_t)HOP_GRID) {                            \
        uint16_t idx = (uint16_t)((unsigned)py * HOP_GRID + (unsigned)px); \
        uint8_t hv = grid[idx];                       /* FAR LOAD */       \
        if (hv != 255) grid[idx] = (uint8_t)(hv + 1); /* FAR STORE */      \
      }                                                                    \
    }                                                                      \
  }

// Stamp `NAME(QUAL uint8_t *grid) -> uint16_t` — a fast rotate-xor rolling hash over the whole grid
// (HOP_GRID*HOP_GRID bytes), the img_hash16 idiom (mandel.h): far loads on target, cheap enough to
// run at boot. The proof channel: host oracle hash == target hash over the same K_GATE accumulation.
#define HOP_DEFINE_HASH(NAME, QUAL)                                        \
  HOP_FN uint16_t NAME(QUAL uint8_t *grid) {                               \
    uint16_t h = 0, i = 0;                                                 \
    do {                                                                   \
      unsigned hi = ((unsigned)h >> 15) & 1u;                             \
      h = (uint16_t)((((unsigned)h << 1) | hi) ^ (unsigned)grid[i]);       \
    } while (++i != HOP_NCELLS);                                           \
    return h;                                                              \
  }

#endif /* HOPALONG_H */
