// #321 realistic kernel — Barry Martin's "Hopalong" strange attractor in Q8.8
// fixed point. This is the math heart of Blossom (the 1989 Turbo Pascal "wallpaper
// for the mind" shareware, and its 2026 web recreation), ported to the 65816 the way
// the original ran on a 286: no FPU, fixed-point integer math, and a precomputed
// square-root table (BLOSSOM.TBL). Phase 1 of the SNES port is HEADLESS — it runs the
// orbit and folds it to a checksum; the on-screen Mode-7 renderer is TODO (#3).
// Plan: docs/plans/2026-06-24-blossom-snes.md.
//
//   x' = y - sign(x) * sqrt(|b*x - c|)      y' = a - x        (iterate from 0,0)
//
// Per iteration: one 16x16 multiply (b*x), a table sqrt, a sign, two subtracts, and a
// rotate-xor fold — a realistic 16-bit-ambient workload for +mos-a16. a,b,c are
// VOLATILE so the whole loop can't be constant-folded away (cf. k_fxmul.c). All
// intermediates that can exceed 16 bits use int32_t; for the bounded classic params
// below the orbit stays well inside int16 (verified by the HOST oracle's range track),
// so every short op is value-preserving and host == target bit-for-bit.
//
// Differential: host == default(8-bit) == +mos-a16, on MAME and bsnes-jg.
// Driven by dev/run.sh k_hopalong.
#include <stdint.h>

// Q8.8 sqrt LUT, 256 entries — generated by tools/gen-sqrt-lut.py.
// SQRT_LUT[i] = round(sqrt(i) * 256); index with `|b*x - c| >> 8` (integer part).
static const unsigned short SQRT_LUT[256] = {
  0x0000, 0x0100, 0x016A, 0x01BB, 0x0200, 0x023C, 0x0273, 0x02A5,
  0x02D4, 0x0300, 0x032A, 0x0351, 0x0377, 0x039B, 0x03BE, 0x03DF,
  0x0400, 0x0420, 0x043E, 0x045C, 0x0479, 0x0495, 0x04B1, 0x04CC,
  0x04E6, 0x0500, 0x0519, 0x0532, 0x054B, 0x0563, 0x057A, 0x0591,
  0x05A8, 0x05BF, 0x05D5, 0x05EB, 0x0600, 0x0615, 0x062A, 0x063F,
  0x0653, 0x0667, 0x067B, 0x068F, 0x06A2, 0x06B5, 0x06C8, 0x06DB,
  0x06EE, 0x0700, 0x0712, 0x0724, 0x0736, 0x0748, 0x0759, 0x076B,
  0x077C, 0x078D, 0x079E, 0x07AE, 0x07BF, 0x07CF, 0x07E0, 0x07F0,
  0x0800, 0x0810, 0x0820, 0x082F, 0x083F, 0x084E, 0x085E, 0x086D,
  0x087C, 0x088B, 0x089A, 0x08A9, 0x08B8, 0x08C6, 0x08D5, 0x08E3,
  0x08F2, 0x0900, 0x090E, 0x091C, 0x092A, 0x0938, 0x0946, 0x0954,
  0x0961, 0x096F, 0x097D, 0x098A, 0x0997, 0x09A5, 0x09B2, 0x09BF,
  0x09CC, 0x09D9, 0x09E6, 0x09F3, 0x0A00, 0x0A0D, 0x0A19, 0x0A26,
  0x0A33, 0x0A3F, 0x0A4C, 0x0A58, 0x0A64, 0x0A71, 0x0A7D, 0x0A89,
  0x0A95, 0x0AA1, 0x0AAD, 0x0AB9, 0x0AC5, 0x0AD1, 0x0ADD, 0x0AE9,
  0x0AF4, 0x0B00, 0x0B0C, 0x0B17, 0x0B23, 0x0B2E, 0x0B3A, 0x0B45,
  0x0B50, 0x0B5C, 0x0B67, 0x0B72, 0x0B7D, 0x0B88, 0x0B93, 0x0B9E,
  0x0BA9, 0x0BB4, 0x0BBF, 0x0BCA, 0x0BD5, 0x0BE0, 0x0BEB, 0x0BF5,
  0x0C00, 0x0C0B, 0x0C15, 0x0C20, 0x0C2A, 0x0C35, 0x0C3F, 0x0C4A,
  0x0C54, 0x0C5F, 0x0C69, 0x0C73, 0x0C7D, 0x0C88, 0x0C92, 0x0C9C,
  0x0CA6, 0x0CB0, 0x0CBA, 0x0CC4, 0x0CCE, 0x0CD8, 0x0CE2, 0x0CEC,
  0x0CF6, 0x0D00, 0x0D0A, 0x0D14, 0x0D1D, 0x0D27, 0x0D31, 0x0D3B,
  0x0D44, 0x0D4E, 0x0D57, 0x0D61, 0x0D6B, 0x0D74, 0x0D7E, 0x0D87,
  0x0D91, 0x0D9A, 0x0DA3, 0x0DAD, 0x0DB6, 0x0DBF, 0x0DC9, 0x0DD2,
  0x0DDB, 0x0DE4, 0x0DEE, 0x0DF7, 0x0E00, 0x0E09, 0x0E12, 0x0E1B,
  0x0E24, 0x0E2D, 0x0E36, 0x0E3F, 0x0E48, 0x0E51, 0x0E5A, 0x0E63,
  0x0E6C, 0x0E75, 0x0E7E, 0x0E87, 0x0E8F, 0x0E98, 0x0EA1, 0x0EAA,
  0x0EB2, 0x0EBB, 0x0EC4, 0x0ECC, 0x0ED5, 0x0EDE, 0x0EE6, 0x0EEF,
  0x0EF7, 0x0F00, 0x0F09, 0x0F11, 0x0F1A, 0x0F22, 0x0F2A, 0x0F33,
  0x0F3B, 0x0F44, 0x0F4C, 0x0F54, 0x0F5D, 0x0F65, 0x0F6D, 0x0F76,
  0x0F7E, 0x0F86, 0x0F8E, 0x0F97, 0x0F9F, 0x0FA7, 0x0FAF, 0x0FB7,
  0x0FBF, 0x0FC8, 0x0FD0, 0x0FD8, 0x0FE0, 0x0FE8, 0x0FF0, 0x0FF8,
};

#define ITERS 1024              // codegen is identical for any N>=1; N only sets runtime
                               // + how well the checksum mixes. 1024 finishes well inside
                               // the MAME settle window (~1 s) with headroom.

// Classic Hopalong parameters (Blossom's default), as Q8.8 constants. Volatile so the
// optimizer must actually run the orbit instead of folding it to a literal.
volatile short pa = 0x072C;    // a = 7.17  (round(7.17*256)=1836)
volatile short pb = 0x0871;    // b = 8.44  (round(8.44*256)=2161)
volatile short pc = 0x028F;    // c = 2.56  (round(2.56*256)=655)

#ifdef HOST
static long g_maxabs = 0;      // host-only: largest |x|,|y| seen (must stay < 32768)
static int  g_clamps = 0;      // host-only: times the LUT index saturated (want 0)
#endif

static unsigned short hopalong_run(void) {
  short x = 0, y = 0;
  unsigned short acc = 0xACE1;                     // checksum seed (cf. k_isort.c)
  for (unsigned short i = 0; i < ITERS; i++) {
    short a = pa, b = pb, c = pc;                  // volatile reads each iteration
    int32_t bx = ((int32_t)b * (int32_t)x) >> 8;   // b*x, Q8.8 (32-bit intermediate)
    int32_t arg = bx - (int32_t)c;                 // b*x - c
    int32_t aarg = arg < 0 ? -arg : arg;           // |b*x - c|
    unsigned short idx = (unsigned short)(aarg >> 8);  // integer part -> LUT index
    if (idx > 255) {
      idx = 255;                                   // defensive: bounded orbit never hits this
#ifdef HOST
      g_clamps++;
#endif
    }
    short s = (short)SQRT_LUT[idx];                // sqrt(|b*x - c|), Q8.8 (>= 0)
    // x' = y - sign(x)*sqrt(...). sign(x)*s is a conditional negate, not a general
    // multiply — branch instead, saving a __mulhi3 per iteration.
    short term = x > 0 ? s : (x < 0 ? (short)-s : (short)0);
    short nx = (short)(y - term);                  // x' = y - sign(x)*sqrt(|b*x - c|)
    short ny = (short)(a - x);                     // y' = a - x
    x = nx; y = ny;
    // rotate-left-1 then xor in the new point (x, and y<<1) — the k_isort rotate-xor
    // idiom; sensitive to any single-bit arithmetic divergence between builds.
    acc = (unsigned short)(((unsigned)acc << 1) | ((unsigned)acc >> 15));
    acc = (unsigned short)(acc ^ (unsigned short)x ^
                           (unsigned short)((unsigned)(unsigned short)y << 1));
#ifdef HOST
    {
      long ax = x < 0 ? -(long)x : (long)x;
      long ay = y < 0 ? -(long)y : (long)y;
      if (ax > g_maxabs) g_maxabs = ax;
      if (ay > g_maxabs) g_maxabs = ay;
    }
#endif
  }
  return acc;
}

#ifdef HOST
#include <stdio.h>
int main(void) {
  unsigned short r = hopalong_run();
  fprintf(stderr, "host oracle: maxabs=%ld (Q8.8 ~ %.2f world units), clamps=%d\n",
          g_maxabs, g_maxabs / 256.0, g_clamps);
  printf("0x%04X\n", r);                           // the golden corpus_result
  return 0;
}
#else
volatile unsigned short corpus_result;
int main(void) {
  corpus_result = hopalong_run();
  for (;;) {}
}
#endif
