// #321 realistic kernel — 16-bit Q2.14 trig via a FRESH CORDIC re-implementation
// (examples/65816/cordic16.h + the generated cordic16_tables.h), NOT a vendored library. This is
// Phase 2 of the trig compiler-test and the deliberate COMPLEMENT of Phase 1 (k_trig32.c):
//
//   Phase 1 (Q16.16 libfixmath): 32-bit fixed point -> exercises the s32 libcall paths
//                                (__mulsi3 / __divsi3 / __udivsi3) and 16x16->32 products.
//   Phase 2 (Q2.14 CORDIC):      pure 16-bit shift-and-add -> exercises NATIVE 16-bit codegen
//                                with ZERO arithmetic libcalls (no __*si3, no __*hi3 mul/div).
//
// So under +mos-a16 this kernel is almost entirely rep/sep-bracketed native 16-bit ALU work —
// the surface Phase 1's 32-bit bulk only grazed. Functions: sin, cos, atan, atan2.
//
// TWO checks, kept separate (same discipline as k_trig32.c):
//  1. DIFFERENTIAL (the compiler bar): host == default(8-bit) == +mos-a16, on MAME and bsnes-jg,
//     BIT-EXACT. Works because the CORDIC is pure int16 with no intermediate leaving the int16
//     range, so host (32-bit int) and target (16-bit int) agree down to the LSB.
//  2. ACCURACY (host-only, #ifdef HOST): each Q2.14 result vs libm double, within the precision
//     a 15-iteration Q2.14 CORDIC actually achieves (a few LSB; see dev/k_trig16.sh for bounds).
//
// Q2.14 range is [-2, +2), so pi does NOT fit and angles are kept in-format (see cordic16.h):
// sin/cos angles in [-pi/2, pi/2]; atan input in (-2, 2); atan2 in the right half-plane (x > 0,
// |x|,|y| <= 1). The sweep below is generated by pure ADDITION of volatile steps (no multiply),
// so the kernel stays libcall-free end to end.
//
// Driven by dev/run.sh k_trig16.
#include <stdint.h>
#include "cordic16.h"

#define NSTEP 32   // samples per function; inputs accumulate across the sweep (both signs, all
                   // representable quadrants). VOLATILE steps below block constant-folding.

// Per-function sweep increments as Q2.14 constants, VOLATILE so the optimizer cannot fold the
// orbit and must actually run the CORDIC each iteration (cf. k_trig32's volatile step_*). Pure
// int16 adds — no multiply reaches target codegen, keeping the kernel arithmetic-libcall-free.
volatile int16_t d_ang  = 1500;   // sin/cos angle step  (~0.0916 rad); 32 samples span ~[-1.47, 1.37]
volatile int16_t d_atan = 1900;   // atan input step     (~0.1160 Q2.14); spans ~[-1.83, 1.76]
volatile int16_t d_y    = 1000;   // atan2 y step        (both signs);   spans ~[-0.92, 0.98]
volatile int16_t d_x    = 380;    // atan2 x step (SUBTRACTED, stays > 0); spans ~[0.26, 0.98]

// Sweep state: one accumulator per function input. Identical updates feed BOTH the checksum loop
// and the HOST accuracy loop, so the two can never drift (the k_trig32 "single source of truth").
typedef struct { int16_t ang, xat, ya, xa; } sweep_t;

static inline void sweep_init(sweep_t *s) {
  s->ang = -24000;   // start of the sin/cos angle sweep (|ang| stays < CORDIC16_HALFPI)
  s->xat = -30000;   // start of the atan input sweep    (|xat| stays < 2*ONE)
  s->ya  = -15000;   // start of the atan2 y sweep
  s->xa  =  16000;   // start of the atan2 x sweep (positive; decreases but stays > 0)
}
static inline void sweep_next(sweep_t *s) {
  s->ang = (int16_t)(s->ang + d_ang);
  s->xat = (int16_t)(s->xat + d_atan);
  s->ya  = (int16_t)(s->ya  + d_y);
  s->xa  = (int16_t)(s->xa  - d_x);
}

// rotate-left-1 then xor over 32 bits (the k_isort/k_hopalong/k_trig32 fold). int16 results are
// value-converted to uint32 (sign-extended identically on host and target), so a one-LSB codegen
// divergence in ANY function surfaces as a checksum mismatch.
static inline uint32_t fold(uint32_t acc, int16_t v) {
  acc = (uint32_t)((acc << 1) | (acc >> 31));
  return acc ^ (uint32_t)v;
}

static uint32_t trig_run(void) {
  uint32_t acc = 0xACE1ACE1u;   // checksum seed (cf. k_isort/k_hopalong/k_trig32)
  sweep_t s;
  sweep_init(&s);
  for (int k = 0; k < NSTEP; k++) {
    acc = fold(acc, cordic16_sin  (s.ang));
    acc = fold(acc, cordic16_cos  (s.ang));
    acc = fold(acc, cordic16_atan (s.xat));
    acc = fold(acc, cordic16_atan2(s.ya, s.xa));
    sweep_next(&s);
  }
  return acc;
}

#ifndef TRIG_NO_MAIN
#ifdef HOST
// ---- host oracle: prints the golden checksum, plus a libm accuracy report ------------------
#include <stdio.h>
#include <math.h>

#define Q214 16384.0
static double q(int16_t v) { return (double)v / Q214; }

// Per-function absolute-error ceilings vs libm. These bound what a 15-iteration Q2.14 CORDIC
// actually achieves over the swept domain (a few LSB; LSB = 1/16384 = 6.1e-5), calibrated ~1.5x
// above the measured max (shown in comments). atan2 is coarser because its inputs are pre-halved
// (the overflow-guard prescale) before the vectoring sweep.
#define EPS_SIN   5.0e-4   // measured ~2.4e-4
#define EPS_COS   5.0e-4   // measured ~3.1e-4
#define EPS_ATAN  5.0e-4   // measured ~2.5e-4
#define EPS_ATAN2 1.5e-3   // measured ~8.2e-4

static void check1(const char *name, double got, double truev, double eps,
                   double *worst, int *fail) {
  (void)name;
  double e = got - truev; if (e < 0) e = -e;
  if (e > *worst) *worst = e;
  if (e > eps) *fail = 1;
}

int main(void) {
  uint32_t golden = trig_run();

  double w_sin = 0, w_cos = 0, w_atan = 0, w_at2 = 0;
  int fail = 0;
  sweep_t s;
  sweep_init(&s);
  for (int k = 0; k < NSTEP; k++) {
    check1("sin",   q(cordic16_sin  (s.ang)),     sin  (q(s.ang)),          EPS_SIN,   &w_sin,  &fail);
    check1("cos",   q(cordic16_cos  (s.ang)),     cos  (q(s.ang)),          EPS_COS,   &w_cos,  &fail);
    check1("atan",  q(cordic16_atan (s.xat)),     atan (q(s.xat)),          EPS_ATAN,  &w_atan, &fail);
    check1("atan2", q(cordic16_atan2(s.ya, s.xa)), atan2(q(s.ya), q(s.xa)), EPS_ATAN2, &w_at2,  &fail);
    sweep_next(&s);
  }

  fprintf(stderr, "host accuracy (Q2.14 CORDIC vs libm, %d samples/fn, max |err|):\n", NSTEP);
  fprintf(stderr, "  sin   %.2e  (eps %.2e)\n", w_sin,  (double)EPS_SIN);
  fprintf(stderr, "  cos   %.2e  (eps %.2e)\n", w_cos,  (double)EPS_COS);
  fprintf(stderr, "  atan  %.2e  (eps %.2e)\n", w_atan, (double)EPS_ATAN);
  fprintf(stderr, "  atan2 %.2e  (eps %.2e)\n", w_at2,  (double)EPS_ATAN2);
  fprintf(stderr, "ACCURACY: %s\n", fail ? "FAIL (a function exceeded its eps)" : "PASS");

  printf("0x%08lX\n", (unsigned long)golden);   // the golden corpus_result (stdout)
  return 0;
}
#else
// ---- target: write the checksum to WRAM and spin while the emulator settles ----------------
volatile uint32_t corpus_result;
int main(void) {
  corpus_result = trig_run();
  for (;;) { }
}
#endif
#endif /* TRIG_NO_MAIN */
