// #321 realistic kernel — Phase 3 of the trig compiler-test: the DERIVED 16-bit functions
// (tan/asin/acos) and the HYPERBOLIC functions (sinh/cosh/tanh), all Q2.14, built on the Phase 2
// CORDIC primitives (examples/65816/cordic16.h). Companion to k_trig16.c (Phase 2 direct
// sin/cos/atan/atan2) and k_trig32.c (Phase 1 Q16.16 libfixmath).
//
// What this adds over Phase 2:
//  - DERIVED: tan = sin/cos (a Q2.14 divide), asin/acos = atan2 of a sqrt(1-x^2) (a Q2.14 sqrt) —
//    so this kernel DOES exercise the s32 mul/div libcalls (__mulsi3/__divsi3), unlike Phase 2's
//    pure shift-add. It is the 16-bit analogue of Phase 1's 32-bit-libcall payload.
//  - HYPERBOLIC: sinh/cosh/tanh via CORDIC *hyperbolic* mode (the repeated i=4,13 schedule) — a
//    code path neither Phase 1 nor Phase 2 reaches.
//
// TWO checks, kept separate (same discipline as k_trig16/k_trig32):
//  1. DIFFERENTIAL (the compiler bar): host == default(8-bit) == +mos-a16, on MAME and bsnes-jg,
//     BIT-EXACT. The int32 intermediates have identical value semantics both legs and the integer
//     sqrt is pure shift/compare, so the results match down to the LSB.
//  2. ACCURACY (host-only, #ifdef HOST): each Q2.14 result vs libm double, within a few-LSB CORDIC
//     precision (see dev/k_trig16x.sh for the bounds).
//
// Q2.14 range is [-2, +2), so every sweep is domain-restricted to keep results in-format (see
// cordic16.h): tan |x|<=1.04; asin |x|<=0.95; acos x in (0,1]; sinh/cosh/tanh |x|<=0.97. The sweep
// is generated by pure ADDITION of volatile steps (the input gen adds no libcalls of its own).
//
// Driven by dev/run.sh k_trig16x.
#include <stdint.h>
#include "cordic16.h"

#define NSTEP 32

// Per-function sweep increments (Q2.14), VOLATILE so the optimizer can't fold the orbit.
volatile int16_t d_tan  = 1075;   // tan angle step;   32 samples span ~[-1.04, 1.00] (|tan|<2, cos>0)
volatile int16_t d_asin =  973;   // asin x step;      spans ~[-0.95, 0.90]  (sqrt(1-x^2) > 0)
volatile int16_t d_acos =  480;   // acos x step (SUBTRACTED, stays > 0); spans ~(1.0, 0.07]
volatile int16_t d_hyp  =  993;   // sinh/cosh/tanh angle step; spans ~[-0.97, 0.91] (cosh<2)

typedef struct { int16_t ta, aa, ca, ha; } sweep_t;

static inline void sweep_init(sweep_t *s) {
  s->ta = -17000;   // tan angle start   (|ta| stays < 1.1*ONE)
  s->aa = -15500;   // asin x start      (|aa| stays < 0.98*ONE)
  s->ca =  16000;   // acos x start      (positive; decreases but stays > 0)
  s->ha = -15900;   // hyperbolic angle start (|ha| stays < ONE)
}
static inline void sweep_next(sweep_t *s) {
  s->ta = (int16_t)(s->ta + d_tan);
  s->aa = (int16_t)(s->aa + d_asin);
  s->ca = (int16_t)(s->ca - d_acos);
  s->ha = (int16_t)(s->ha + d_hyp);
}

static inline uint32_t fold(uint32_t acc, int16_t v) {
  acc = (uint32_t)((acc << 1) | (acc >> 31));
  return acc ^ (uint32_t)v;
}

static uint32_t trig_run(void) {
  uint32_t acc = 0xACE1ACE1u;
  sweep_t s;
  sweep_init(&s);
  for (int k = 0; k < NSTEP; k++) {
    acc = fold(acc, cordic16_tan (s.ta));
    acc = fold(acc, cordic16_asin(s.aa));
    acc = fold(acc, cordic16_acos(s.ca));
    acc = fold(acc, cordic16_sinh(s.ha));
    acc = fold(acc, cordic16_cosh(s.ha));
    acc = fold(acc, cordic16_tanh(s.ha));
    sweep_next(&s);
  }
  return acc;
}

#ifndef TRIG_NO_MAIN
#ifdef HOST
// ---- host oracle: prints the golden checksum, plus a libm accuracy report ------------------
#include <stdio.h>
#include <math.h>

#define Q214 16384.0
static double q(int16_t v) { return (double)v / Q214; }

// Per-function ceilings vs libm — a few LSB of Q2.14 CORDIC precision (LSB = 6.1e-5), ~1.5x over
// the measured max (in comments). tan/tanh are coarser (they compound a divide).
#define EPS_TAN   1.2e-3   // measured ~7.7e-4
#define EPS_ASIN  6.0e-4   // measured ~3.3e-4
#define EPS_ACOS  7.0e-4   // measured ~4.0e-4
#define EPS_SINH  7.0e-4   // measured ~4.6e-4
#define EPS_COSH  6.0e-4   // measured ~3.7e-4
#define EPS_TANH  8.0e-4   // measured ~5.0e-4

static void check1(double got, double truev, double eps, double *worst, int *fail) {
  double e = got - truev; if (e < 0) e = -e;
  if (e > *worst) *worst = e;
  if (e > eps) *fail = 1;
}

int main(void) {
  uint32_t golden = trig_run();

  double w_tan = 0, w_asin = 0, w_acos = 0, w_sinh = 0, w_cosh = 0, w_tanh = 0;
  int fail = 0;
  sweep_t s;
  sweep_init(&s);
  for (int k = 0; k < NSTEP; k++) {
    check1(q(cordic16_tan (s.ta)), tan (q(s.ta)), EPS_TAN,  &w_tan,  &fail);
    check1(q(cordic16_asin(s.aa)), asin(q(s.aa)), EPS_ASIN, &w_asin, &fail);
    check1(q(cordic16_acos(s.ca)), acos(q(s.ca)), EPS_ACOS, &w_acos, &fail);
    check1(q(cordic16_sinh(s.ha)), sinh(q(s.ha)), EPS_SINH, &w_sinh, &fail);
    check1(q(cordic16_cosh(s.ha)), cosh(q(s.ha)), EPS_COSH, &w_cosh, &fail);
    check1(q(cordic16_tanh(s.ha)), tanh(q(s.ha)), EPS_TANH, &w_tanh, &fail);
    sweep_next(&s);
  }

  fprintf(stderr, "host accuracy (Q2.14 derived+hyperbolic CORDIC vs libm, %d samples/fn, max |err|):\n", NSTEP);
  fprintf(stderr, "  tan   %.2e  (eps %.2e)\n", w_tan,  (double)EPS_TAN);
  fprintf(stderr, "  asin  %.2e  (eps %.2e)\n", w_asin, (double)EPS_ASIN);
  fprintf(stderr, "  acos  %.2e  (eps %.2e)\n", w_acos, (double)EPS_ACOS);
  fprintf(stderr, "  sinh  %.2e  (eps %.2e)\n", w_sinh, (double)EPS_SINH);
  fprintf(stderr, "  cosh  %.2e  (eps %.2e)\n", w_cosh, (double)EPS_COSH);
  fprintf(stderr, "  tanh  %.2e  (eps %.2e)\n", w_tanh, (double)EPS_TANH);
  fprintf(stderr, "ACCURACY: %s\n", fail ? "FAIL (a function exceeded its eps)" : "PASS");

  printf("0x%08lX\n", (unsigned long)golden);
  return 0;
}
#else
// ---- target: write the checksum to WRAM and spin while the emulator settles ----------------
volatile uint32_t corpus_result;
int main(void) {
  corpus_result = trig_run();
  for (;;) __asm__ volatile("wai");
}
#endif
#endif /* TRIG_NO_MAIN */
