// Shared, PURE LZ77/LZSS byte-stream decoder — host-linkable, no hardware.  Demo #49.
//
// The codegen corner: a **decode state machine that copies back-references from its OWN output** — the
// LZ77 sliding window.  A flag-driven token stream mixes literal bytes with (offset, length) matches;
// each match copies `length` bytes from `output[pos - offset]` forward, byte-by-byte, so an overlapping
// copy (offset < length) RLE-expands a run.  The hot path is output-relative pointer arithmetic reading
// bytes the loop itself just wrote — a self-referential decoder no other demo runs.
//
// Width discipline (host int=32 / target int=16 must agree byte-for-byte):
//   - all offsets/indices are uint16_t, bytes uint8_t; the compressed stream + its decoding are
//     deterministic so host and target produce identical output; the fold masks to uint16_t.
// See docs/plans/2026-06-30-49-snes-lzdec.md.
#ifndef LZDEC_H
#define LZDEC_H

#include <stdint.h>

#define LZ_MINMATCH 3u

// LZSS-compressed 16x16 diamond "image" (256 colour cells 0..3 -> 56 bytes).  Generated by
// tools/lzgen.py; decode() below reproduces the 256-byte cell buffer exactly (roundtrip-verified).
#define LZ_SRCLEN 56u
#define LZ_OUTLEN 256u
static const uint8_t LZ_STREAM[LZ_SRCLEN] = {
  0x10, 0x00, 0x03, 0x02, 0x01, 0x04, 0x02, 0x01, 0x02, 0x03, 0x3F, 0x04, 0x01, 0x0F, 0x05, 0x0D,
  0x02, 0x04, 0x00, 0x0F, 0x05, 0x1E, 0x03, 0x00, 0x01, 0xFB, 0x0F, 0x05, 0x2F, 0x04, 0x00, 0x40,
  0x0F, 0x40, 0x0F, 0x40, 0x0F, 0x40, 0x0F, 0x40, 0x05, 0x7F, 0x20, 0x0D, 0x40, 0x0D, 0x60, 0x0D,
  0x40, 0x0F, 0x40, 0x0F, 0x40, 0x0F, 0x40, 0x07,
};

// Decode the LZSS stream into dst (capacity dstcap).  Returns the number of bytes written.  Token
// format: a flag byte, then 8 tokens (LSB-first): flag bit 0 = literal (1 byte); flag bit 1 = match
// (2 bytes: b0=low-8 offset, b1 = (hi-4 offset << 4) | (length-MINMATCH)).
static uint16_t lz_decode(const uint8_t *src, uint16_t srclen, uint8_t *dst, uint16_t dstcap) {
    uint16_t sp = 0, dp = 0;
    while (sp < srclen && dp < dstcap) {
        uint8_t flags = src[sp++];
        for (uint8_t b = 0; b < 8u && sp < srclen && dp < dstcap; b++) {
            if (flags & (uint8_t)(1u << b)) {
                uint8_t b0 = src[sp++];
                uint8_t b1 = src[sp++];
                uint16_t offset = (uint16_t)(((uint16_t)(b1 >> 4) << 8) | b0);   // 12-bit distance
                uint8_t length = (uint8_t)((b1 & 0x0Fu) + LZ_MINMATCH);
                uint16_t from = (uint16_t)(dp - offset);                          // back-reference
                for (uint8_t k = 0; k < length && dp < dstcap; k++)
                    dst[dp++] = dst[from++];      // copy from our OWN output (overlap RLE-expands)
            } else {
                dst[dp++] = src[sp++];            // literal
            }
        }
    }
    return dp;
}

// ---------------------------------------------------------------------------------------------
// Differential gate: decode the stream and fold the whole output.

static inline uint16_t lz_fold(uint16_t h, uint16_t x) {
    return (uint16_t)((((uint16_t)(h << 1)) | (uint16_t)((h >> 15) & 1u)) ^ x);
}

static uint16_t lzdec_gate_crc(void) {
    static uint8_t out[LZ_OUTLEN];
    uint16_t n = lz_decode(LZ_STREAM, LZ_SRCLEN, out, LZ_OUTLEN);
    uint16_t h = n;
    for (uint16_t i = 0; i < LZ_OUTLEN; i++)
        h = lz_fold(h, (uint16_t)out[i]);
    return h;
}

#endif /* LZDEC_H */
